/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_CHASSISGACA13SERVICEINTERFACE_COMMON_H
#define ARA_CHASSISGACA13_CHASSISGACA13SERVICEINTERFACE_COMMON_H

#include "ara/com/types.h"
#include "ara/chassisgaca13/impl_type_chassisgaca13statusmsg.h"

namespace ara {
namespace chassisgaca13 {
class ChassisGacA13ServiceInterface {
public:
    constexpr ChassisGacA13ServiceInterface() = default;
    constexpr static ara::com::ServiceIdentifierType ServiceIdentifier = ara::com::ServiceIdentifierType("/HuaweiMDC/PlatformServiceInterface/ChassisGacA13ServiceInterface/ChassisGacA13ServiceInterface");
    constexpr static ara::com::ServiceVersionType ServiceVersion = ara::com::ServiceVersionType("1.1");
};
} // namespace chassisgaca13
} // namespace ara

#endif // ARA_CHASSISGACA13_CHASSISGACA13SERVICEINTERFACE_COMMON_H
