/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_GWBCMRLS1BA_H
#define ARA_CHASSISGACA13_IMPL_TYPE_GWBCMRLS1BA_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"
#include "impl_type_uint16.h"

namespace ara {
namespace chassisgaca13 {
struct GwBcmRls1BA {
    ::UInt8 rlsRainfallLevel;
    ::UInt16 rlsAmbbrightness;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(rlsRainfallLevel);
        fun(rlsAmbbrightness);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(rlsRainfallLevel);
        fun(rlsAmbbrightness);
    }

    bool operator == (const ::ara::chassisgaca13::GwBcmRls1BA& t) const
    {
        return (rlsRainfallLevel == t.rlsRainfallLevel) && (rlsAmbbrightness == t.rlsAmbbrightness);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_GWBCMRLS1BA_H
