/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_EBB1A_H
#define ARA_CHASSISGACA13_IMPL_TYPE_EBB1A_H
#include <cfloat>
#include <cmath>
#include "impl_type_float.h"
#include "impl_type_uint8.h"
#include "impl_type_uint16.h"

namespace ara {
namespace chassisgaca13 {
struct Ebb1A {
    ::Float ebbActOutputRodTravel;
    ::UInt8 ebbActOutputRodTravelSt;
    ::UInt8 ebb1AMsgCounter;
    ::UInt16 ebb1AChecksum;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(ebbActOutputRodTravel);
        fun(ebbActOutputRodTravelSt);
        fun(ebb1AMsgCounter);
        fun(ebb1AChecksum);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(ebbActOutputRodTravel);
        fun(ebbActOutputRodTravelSt);
        fun(ebb1AMsgCounter);
        fun(ebb1AChecksum);
    }

    bool operator == (const ::ara::chassisgaca13::Ebb1A& t) const
    {
        return (fabs(ebbActOutputRodTravel - t.ebbActOutputRodTravel) < FLT_EPSILON) && (ebbActOutputRodTravelSt == t.ebbActOutputRodTravelSt) && (ebb1AMsgCounter == t.ebb1AMsgCounter) && (ebb1AChecksum == t.ebb1AChecksum);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_EBB1A_H
