/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_FRRNMACAN_H
#define ARA_CHASSISGACA13_IMPL_TYPE_FRRNMACAN_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint16.h"
#include "impl_type_uint64.h"

namespace ara {
namespace chassisgaca13 {
struct FrrNmAcan {
    ::UInt16 frrNodeAddress;
    ::UInt64 frrNmdataField;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(frrNodeAddress);
        fun(frrNmdataField);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(frrNodeAddress);
        fun(frrNmdataField);
    }

    bool operator == (const ::ara::chassisgaca13::FrrNmAcan& t) const
    {
        return (frrNodeAddress == t.frrNodeAddress) && (frrNmdataField == t.frrNmdataField);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_FRRNMACAN_H
