/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_GWICM1A_H
#define ARA_CHASSISGACA13_IMPL_TYPE_GWICM1A_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"

namespace ara {
namespace chassisgaca13 {
struct GwIcm1A {
    ::UInt8 icmMfsbuttonSt;
    ::UInt8 icmSetIaccst;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(icmMfsbuttonSt);
        fun(icmSetIaccst);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(icmMfsbuttonSt);
        fun(icmSetIaccst);
    }

    bool operator == (const ::ara::chassisgaca13::GwIcm1A& t) const
    {
        return (icmMfsbuttonSt == t.icmMfsbuttonSt) && (icmSetIaccst == t.icmSetIaccst);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_GWICM1A_H
