/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_GWACU11A_H
#define ARA_CHASSISGACA13_IMPL_TYPE_GWACU11A_H
#include <cfloat>
#include <cmath>
#include "impl_type_float.h"

namespace ara {
namespace chassisgaca13 {
struct GwAcu11A {
    ::Float acuLongitude;
    ::Float acuLatitude;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(acuLongitude);
        fun(acuLatitude);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(acuLongitude);
        fun(acuLatitude);
    }

    bool operator == (const ::ara::chassisgaca13::GwAcu11A& t) const
    {
        return (fabs(acuLongitude - t.acuLongitude) < FLT_EPSILON) && (fabs(acuLatitude - t.acuLatitude) < FLT_EPSILON);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_GWACU11A_H
