/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_GWACU10AA_H
#define ARA_CHASSISGACA13_IMPL_TYPE_GWACU10AA_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint16.h"
#include "impl_type_float.h"
#include "impl_type_uint8.h"

namespace ara {
namespace chassisgaca13 {
struct GwAcu10AA {
    ::UInt16 acuIfcSpeedLimit;
    ::UInt16 acuIfcIsdrestOfdis;
    ::Float acuIfcOfframpDis;
    ::UInt8 acuIfcSpeedLimtType;
    ::UInt8 acuIfcRoadType;
    ::UInt8 acuIfcZoneCode;
    ::UInt8 acuIfcNaviSt;
    ::UInt8 acuIfcNaviCorp;
    ::Float acuIfcNaviNewIconDis;
    ::UInt8 acuIfcNaviNewIcon;
    ::UInt8 acuIfcSpeedLimitUnit;
    ::UInt8 acuIfcOfframpSt;
    ::UInt8 acuNdasdmapReadySt;
    ::UInt16 acuIfcSlcaheadDis;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(acuIfcSpeedLimit);
        fun(acuIfcIsdrestOfdis);
        fun(acuIfcOfframpDis);
        fun(acuIfcSpeedLimtType);
        fun(acuIfcRoadType);
        fun(acuIfcZoneCode);
        fun(acuIfcNaviSt);
        fun(acuIfcNaviCorp);
        fun(acuIfcNaviNewIconDis);
        fun(acuIfcNaviNewIcon);
        fun(acuIfcSpeedLimitUnit);
        fun(acuIfcOfframpSt);
        fun(acuNdasdmapReadySt);
        fun(acuIfcSlcaheadDis);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(acuIfcSpeedLimit);
        fun(acuIfcIsdrestOfdis);
        fun(acuIfcOfframpDis);
        fun(acuIfcSpeedLimtType);
        fun(acuIfcRoadType);
        fun(acuIfcZoneCode);
        fun(acuIfcNaviSt);
        fun(acuIfcNaviCorp);
        fun(acuIfcNaviNewIconDis);
        fun(acuIfcNaviNewIcon);
        fun(acuIfcSpeedLimitUnit);
        fun(acuIfcOfframpSt);
        fun(acuNdasdmapReadySt);
        fun(acuIfcSlcaheadDis);
    }

    bool operator == (const ::ara::chassisgaca13::GwAcu10AA& t) const
    {
        return (acuIfcSpeedLimit == t.acuIfcSpeedLimit) && (acuIfcIsdrestOfdis == t.acuIfcIsdrestOfdis) && (fabs(acuIfcOfframpDis - t.acuIfcOfframpDis) < FLT_EPSILON) && (acuIfcSpeedLimtType == t.acuIfcSpeedLimtType) && (acuIfcRoadType == t.acuIfcRoadType) && (acuIfcZoneCode == t.acuIfcZoneCode) && (acuIfcNaviSt == t.acuIfcNaviSt) && (acuIfcNaviCorp == t.acuIfcNaviCorp) && (fabs(acuIfcNaviNewIconDis - t.acuIfcNaviNewIconDis) < FLT_EPSILON) && (acuIfcNaviNewIcon == t.acuIfcNaviNewIcon) && (acuIfcSpeedLimitUnit == t.acuIfcSpeedLimitUnit) && (acuIfcOfframpSt == t.acuIfcOfframpSt) && (acuNdasdmapReadySt == t.acuNdasdmapReadySt) && (acuIfcSlcaheadDis == t.acuIfcSlcaheadDis);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_GWACU10AA_H
