/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_PAS2_H
#define ARA_CHASSISGACA13_IMPL_TYPE_PAS2_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint16.h"

namespace ara {
namespace chassisgaca13 {
struct Pas2 {
    ::UInt16 pasFrdistance;
    ::UInt16 pasFldistance;
    ::UInt16 pasFrmidDistance;
    ::UInt16 pasFlmidDistance;
    ::UInt16 pasFsrsideDistance;
    ::UInt16 pasFslsideDistance;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(pasFrdistance);
        fun(pasFldistance);
        fun(pasFrmidDistance);
        fun(pasFlmidDistance);
        fun(pasFsrsideDistance);
        fun(pasFslsideDistance);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(pasFrdistance);
        fun(pasFldistance);
        fun(pasFrmidDistance);
        fun(pasFlmidDistance);
        fun(pasFsrsideDistance);
        fun(pasFslsideDistance);
    }

    bool operator == (const ::ara::chassisgaca13::Pas2& t) const
    {
        return (pasFrdistance == t.pasFrdistance) && (pasFldistance == t.pasFldistance) && (pasFrmidDistance == t.pasFrmidDistance) && (pasFlmidDistance == t.pasFlmidDistance) && (pasFsrsideDistance == t.pasFsrsideDistance) && (pasFslsideDistance == t.pasFslsideDistance);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_PAS2_H
