/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_EPS2_H
#define ARA_CHASSISGACA13_IMPL_TYPE_EPS2_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"
#include "impl_type_float.h"
#include "impl_type_uint16.h"

namespace ara {
namespace chassisgaca13 {
struct Eps2 {
    ::UInt8 epsLkactrlSt;
    ::UInt8 epsLkactrlAbortFeedback;
    ::Float epsLkactrlDlvdValue;
    ::UInt8 epsLkactrlDlvdValueVd;
    ::UInt8 epsHandsOffDetSt;
    ::UInt8 epsHandsOffDetStVd;
    ::UInt8 epsAssistPraSwitchToLka;
    ::UInt8 eps2MsgCounter;
    ::UInt16 eps2Checksum;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(epsLkactrlSt);
        fun(epsLkactrlAbortFeedback);
        fun(epsLkactrlDlvdValue);
        fun(epsLkactrlDlvdValueVd);
        fun(epsHandsOffDetSt);
        fun(epsHandsOffDetStVd);
        fun(epsAssistPraSwitchToLka);
        fun(eps2MsgCounter);
        fun(eps2Checksum);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(epsLkactrlSt);
        fun(epsLkactrlAbortFeedback);
        fun(epsLkactrlDlvdValue);
        fun(epsLkactrlDlvdValueVd);
        fun(epsHandsOffDetSt);
        fun(epsHandsOffDetStVd);
        fun(epsAssistPraSwitchToLka);
        fun(eps2MsgCounter);
        fun(eps2Checksum);
    }

    bool operator == (const ::ara::chassisgaca13::Eps2& t) const
    {
        return (epsLkactrlSt == t.epsLkactrlSt) && (epsLkactrlAbortFeedback == t.epsLkactrlAbortFeedback) && (fabs(epsLkactrlDlvdValue - t.epsLkactrlDlvdValue) < FLT_EPSILON) && (epsLkactrlDlvdValueVd == t.epsLkactrlDlvdValueVd) && (epsHandsOffDetSt == t.epsHandsOffDetSt) && (epsHandsOffDetStVd == t.epsHandsOffDetStVd) && (epsAssistPraSwitchToLka == t.epsAssistPraSwitchToLka) && (eps2MsgCounter == t.eps2MsgCounter) && (eps2Checksum == t.eps2Checksum);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_EPS2_H
