/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_BSDSNMACAN_H
#define ARA_CHASSISGACA13_IMPL_TYPE_BSDSNMACAN_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint16.h"
#include "impl_type_uint32.h"
#include "impl_type_uint64.h"

namespace ara {
namespace chassisgaca13 {
struct BsdsNmAcan {
    ::UInt16 bsdsNodeAddress;
    ::UInt32 bsdsNmdataField1;
    ::UInt16 bsdsSubNetWakeRq;
    ::UInt64 bsdsNmdataField2;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(bsdsNodeAddress);
        fun(bsdsNmdataField1);
        fun(bsdsSubNetWakeRq);
        fun(bsdsNmdataField2);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(bsdsNodeAddress);
        fun(bsdsNmdataField1);
        fun(bsdsSubNetWakeRq);
        fun(bsdsNmdataField2);
    }

    bool operator == (const ::ara::chassisgaca13::BsdsNmAcan& t) const
    {
        return (bsdsNodeAddress == t.bsdsNodeAddress) && (bsdsNmdataField1 == t.bsdsNmdataField1) && (bsdsSubNetWakeRq == t.bsdsSubNetWakeRq) && (bsdsNmdataField2 == t.bsdsNmdataField2);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_BSDSNMACAN_H
