/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_BCSEPB1A_H
#define ARA_CHASSISGACA13_IMPL_TYPE_BCSEPB1A_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"
#include "impl_type_uint16.h"

namespace ara {
namespace chassisgaca13 {
struct BcsEpb1A {
    ::UInt8 epbSwitchStVd;
    ::UInt8 epbSwitchSt;
    ::UInt8 epbSysSt;
    ::UInt8 epbFailSt;
    ::UInt8 bcsEpb1AMsgCounter;
    ::UInt16 bcsEpb1AChecksum;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(epbSwitchStVd);
        fun(epbSwitchSt);
        fun(epbSysSt);
        fun(epbFailSt);
        fun(bcsEpb1AMsgCounter);
        fun(bcsEpb1AChecksum);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(epbSwitchStVd);
        fun(epbSwitchSt);
        fun(epbSysSt);
        fun(epbFailSt);
        fun(bcsEpb1AMsgCounter);
        fun(bcsEpb1AChecksum);
    }

    bool operator == (const ::ara::chassisgaca13::BcsEpb1A& t) const
    {
        return (epbSwitchStVd == t.epbSwitchStVd) && (epbSwitchSt == t.epbSwitchSt) && (epbSysSt == t.epbSysSt) && (epbFailSt == t.epbFailSt) && (bcsEpb1AMsgCounter == t.bcsEpb1AMsgCounter) && (bcsEpb1AChecksum == t.bcsEpb1AChecksum);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_BCSEPB1A_H
