/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_MLMNM_H
#define ARA_CHASSISGACA13_IMPL_TYPE_MLMNM_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint16.h"
#include "impl_type_uint64.h"

namespace ara {
namespace chassisgaca13 {
struct MlmNm {
    ::UInt16 mlmNodeAddress;
    ::UInt64 mlmNmdataField;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(mlmNodeAddress);
        fun(mlmNmdataField);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(mlmNodeAddress);
        fun(mlmNmdataField);
    }

    bool operator == (const ::ara::chassisgaca13::MlmNm& t) const
    {
        return (mlmNodeAddress == t.mlmNodeAddress) && (mlmNmdataField == t.mlmNmdataField);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_MLMNM_H
