/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_BSDMNMACAN_H
#define ARA_CHASSISGACA13_IMPL_TYPE_BSDMNMACAN_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint16.h"
#include "impl_type_uint32.h"
#include "impl_type_uint64.h"

namespace ara {
namespace chassisgaca13 {
struct BsdmNmAcan {
    ::UInt16 bsdmNodeAddress;
    ::UInt32 bsdmNmdataField1;
    ::UInt16 bsdmSubNetWakeRq;
    ::UInt64 bsdmNmdataField2;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(bsdmNodeAddress);
        fun(bsdmNmdataField1);
        fun(bsdmSubNetWakeRq);
        fun(bsdmNmdataField2);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(bsdmNodeAddress);
        fun(bsdmNmdataField1);
        fun(bsdmSubNetWakeRq);
        fun(bsdmNmdataField2);
    }

    bool operator == (const ::ara::chassisgaca13::BsdmNmAcan& t) const
    {
        return (bsdmNodeAddress == t.bsdmNodeAddress) && (bsdmNmdataField1 == t.bsdmNmdataField1) && (bsdmSubNetWakeRq == t.bsdmSubNetWakeRq) && (bsdmNmdataField2 == t.bsdmNmdataField2);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_BSDMNMACAN_H
