/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_BCS7A_H
#define ARA_CHASSISGACA13_IMPL_TYPE_BCS7A_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"
#include "impl_type_uint16.h"

namespace ara {
namespace chassisgaca13 {
struct Bcs7A {
    ::UInt8 bcsHdcerrSt;
    ::UInt8 bcsHdcctrlSt;
    ::UInt8 bcs7AMsgCounter;
    ::UInt16 bcs7AChecksum;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(bcsHdcerrSt);
        fun(bcsHdcctrlSt);
        fun(bcs7AMsgCounter);
        fun(bcs7AChecksum);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(bcsHdcerrSt);
        fun(bcsHdcctrlSt);
        fun(bcs7AMsgCounter);
        fun(bcs7AChecksum);
    }

    bool operator == (const ::ara::chassisgaca13::Bcs7A& t) const
    {
        return (bcsHdcerrSt == t.bcsHdcerrSt) && (bcsHdcctrlSt == t.bcsHdcctrlSt) && (bcs7AMsgCounter == t.bcs7AMsgCounter) && (bcs7AChecksum == t.bcs7AChecksum);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_BCS7A_H
