/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_GWBCM2A_H
#define ARA_CHASSISGACA13_IMPL_TYPE_GWBCM2A_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"
#include "impl_type_uint16.h"

namespace ara {
namespace chassisgaca13 {
struct GwBcm2A {
    ::UInt8 bcmFrontWiperSt;
    ::UInt8 bcmRearFogLampSt;
    ::UInt8 bcmFrontFogLampSt;
    ::UInt8 bcmHighBeamSt;
    ::UInt8 bcmLowBeamSt;
    ::UInt8 bcmDriverDoorAjarSt;
    ::UInt8 bcmKeySt;
    ::UInt8 bcmFrontWasherSt;
    ::UInt8 bcmRrdoorAjarSt;
    ::UInt8 bcmRldoorAjarSt;
    ::UInt8 bcmPsngrDoorAjarSt;
    ::UInt8 bcmTurnLightSwitchSt;
    ::UInt8 bcmRightTurnLampFaultSt;
    ::UInt8 bcmRightTurnLampSt;
    ::UInt8 bcmLeftTurnLampFaultSt;
    ::UInt8 bcmLeftTurnLampSt;
    ::UInt8 bcmMainLampSwst;
    ::UInt8 bcmBeamSwitchSt;
    ::UInt8 bcmAutoHighBeamCtrlSt;
    ::UInt8 bcmAtwsSt;
    ::UInt8 bcmPsngrDoorLockSt;
    ::UInt8 bcmDriverDoorLockSt;
    ::UInt8 bcmBcan2MsgCounter;
    ::UInt16 bcmBcan2Checksum;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(bcmFrontWiperSt);
        fun(bcmRearFogLampSt);
        fun(bcmFrontFogLampSt);
        fun(bcmHighBeamSt);
        fun(bcmLowBeamSt);
        fun(bcmDriverDoorAjarSt);
        fun(bcmKeySt);
        fun(bcmFrontWasherSt);
        fun(bcmRrdoorAjarSt);
        fun(bcmRldoorAjarSt);
        fun(bcmPsngrDoorAjarSt);
        fun(bcmTurnLightSwitchSt);
        fun(bcmRightTurnLampFaultSt);
        fun(bcmRightTurnLampSt);
        fun(bcmLeftTurnLampFaultSt);
        fun(bcmLeftTurnLampSt);
        fun(bcmMainLampSwst);
        fun(bcmBeamSwitchSt);
        fun(bcmAutoHighBeamCtrlSt);
        fun(bcmAtwsSt);
        fun(bcmPsngrDoorLockSt);
        fun(bcmDriverDoorLockSt);
        fun(bcmBcan2MsgCounter);
        fun(bcmBcan2Checksum);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(bcmFrontWiperSt);
        fun(bcmRearFogLampSt);
        fun(bcmFrontFogLampSt);
        fun(bcmHighBeamSt);
        fun(bcmLowBeamSt);
        fun(bcmDriverDoorAjarSt);
        fun(bcmKeySt);
        fun(bcmFrontWasherSt);
        fun(bcmRrdoorAjarSt);
        fun(bcmRldoorAjarSt);
        fun(bcmPsngrDoorAjarSt);
        fun(bcmTurnLightSwitchSt);
        fun(bcmRightTurnLampFaultSt);
        fun(bcmRightTurnLampSt);
        fun(bcmLeftTurnLampFaultSt);
        fun(bcmLeftTurnLampSt);
        fun(bcmMainLampSwst);
        fun(bcmBeamSwitchSt);
        fun(bcmAutoHighBeamCtrlSt);
        fun(bcmAtwsSt);
        fun(bcmPsngrDoorLockSt);
        fun(bcmDriverDoorLockSt);
        fun(bcmBcan2MsgCounter);
        fun(bcmBcan2Checksum);
    }

    bool operator == (const ::ara::chassisgaca13::GwBcm2A& t) const
    {
        return (bcmFrontWiperSt == t.bcmFrontWiperSt) && (bcmRearFogLampSt == t.bcmRearFogLampSt) && (bcmFrontFogLampSt == t.bcmFrontFogLampSt) && (bcmHighBeamSt == t.bcmHighBeamSt) && (bcmLowBeamSt == t.bcmLowBeamSt) && (bcmDriverDoorAjarSt == t.bcmDriverDoorAjarSt) && (bcmKeySt == t.bcmKeySt) && (bcmFrontWasherSt == t.bcmFrontWasherSt) && (bcmRrdoorAjarSt == t.bcmRrdoorAjarSt) && (bcmRldoorAjarSt == t.bcmRldoorAjarSt) && (bcmPsngrDoorAjarSt == t.bcmPsngrDoorAjarSt) && (bcmTurnLightSwitchSt == t.bcmTurnLightSwitchSt) && (bcmRightTurnLampFaultSt == t.bcmRightTurnLampFaultSt) && (bcmRightTurnLampSt == t.bcmRightTurnLampSt) && (bcmLeftTurnLampFaultSt == t.bcmLeftTurnLampFaultSt) && (bcmLeftTurnLampSt == t.bcmLeftTurnLampSt) && (bcmMainLampSwst == t.bcmMainLampSwst) && (bcmBeamSwitchSt == t.bcmBeamSwitchSt) && (bcmAutoHighBeamCtrlSt == t.bcmAutoHighBeamCtrlSt) && (bcmAtwsSt == t.bcmAtwsSt) && (bcmPsngrDoorLockSt == t.bcmPsngrDoorLockSt) && (bcmDriverDoorLockSt == t.bcmDriverDoorLockSt) && (bcmBcan2MsgCounter == t.bcmBcan2MsgCounter) && (bcmBcan2Checksum == t.bcmBcan2Checksum);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_GWBCM2A_H
