/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASSISGACA13_IMPL_TYPE_GWBCM1A_H
#define ARA_CHASSISGACA13_IMPL_TYPE_GWBCM1A_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"

namespace ara {
namespace chassisgaca13 {
struct GwBcm1A {
    ::UInt8 tpmsTyreSt;
    ::UInt8 bcmHazardLampSt;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(tpmsTyreSt);
        fun(bcmHazardLampSt);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(tpmsTyreSt);
        fun(bcmHazardLampSt);
    }

    bool operator == (const ::ara::chassisgaca13::GwBcm1A& t) const
    {
        return (tpmsTyreSt == t.tpmsTyreSt) && (bcmHazardLampSt == t.bcmHazardLampSt);
    }
};
} // namespace chassisgaca13
} // namespace ara


#endif // ARA_CHASSISGACA13_IMPL_TYPE_GWBCM1A_H
