/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CAMERA_IMPL_TYPE_CAMDELAYDATA_H
#define ARA_CAMERA_IMPL_TYPE_CAMDELAYDATA_H
#include <cfloat>
#include <cmath>
#include "impl_type_string.h"
#include "impl_type_uint64.h"

namespace ara {
namespace camera {
struct CamDelayData {
    ::String frameId;
    ::UInt64 ispCostTime;
    ::UInt64 ispRecvTime;
    ::UInt64 intfCostTime;
    ::UInt64 intfRecvTime;

    static bool IsPlane()
    {
        return false;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(frameId);
        fun(ispCostTime);
        fun(ispRecvTime);
        fun(intfCostTime);
        fun(intfRecvTime);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(frameId);
        fun(ispCostTime);
        fun(ispRecvTime);
        fun(intfCostTime);
        fun(intfRecvTime);
    }

    bool operator == (const ::ara::camera::CamDelayData& t) const
    {
        return (frameId == t.frameId) && (ispCostTime == t.ispCostTime) && (ispRecvTime == t.ispRecvTime) && (intfCostTime == t.intfCostTime) && (intfRecvTime == t.intfRecvTime);
    }
};
} // namespace camera
} // namespace ara


#endif // ARA_CAMERA_IMPL_TYPE_CAMDELAYDATA_H
