/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CANTP_CANTPMSGSERVICEINTERFACE_COMMON_H
#define ARA_CANTP_CANTPMSGSERVICEINTERFACE_COMMON_H

#include "ara/com/types.h"
#include "ara/cantp/impl_type_cantpmsg.h"

namespace ara {
namespace cantp {
class CanTpMsgServiceInterface {
public:
    constexpr CanTpMsgServiceInterface() = default;
    constexpr static ara::com::ServiceIdentifierType ServiceIdentifier = ara::com::ServiceIdentifierType("/HuaweiMDC/PlatformServiceInterface/CanTpServiceInterface/CanTpMsgServiceInterface");
    constexpr static ara::com::ServiceVersionType ServiceVersion = ara::com::ServiceVersionType("1.1");
};
} // namespace cantp
} // namespace ara

#endif // ARA_CANTP_CANTPMSGSERVICEINTERFACE_COMMON_H
