/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#include "ara/diag/diagcomclient_skeleton.h"
#include "ara/diag/diagcomnotifier_skeleton.h"
#include "ara/diag/diagcomserver_skeleton.h"
#include "ara/sm/triggerinout_proxy.h"
#include "mdc/config/server/configserverserviceinterface_proxy.h"
