/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_DEVM_MCU_DEVMMCUCTRLSOMEIPSERVICEINTERFACE_PROXY_H
#define MDC_DEVM_DEVM_MCU_DEVMMCUCTRLSOMEIPSERVICEINTERFACE_PROXY_H

#include "ara/com/internal/proxy/proxy_adapter.h"
#include "ara/com/internal/proxy/event_adapter.h"
#include "ara/com/internal/proxy/field_adapter.h"
#include "ara/com/internal/proxy/method_adapter.h"
#include "mdc/devm/devm_mcu/devmmcuctrlsomeipserviceinterface_common.h"
#include <string>
#include <cfloat>
#include <cmath>

namespace mdc {
namespace devm {
namespace devm_mcu {
namespace proxy {
namespace events {
    using DevInfoEvent = ara::com::internal::proxy::event::EventAdapter<::mdc::devm::DevInfoResultType>;
    using McuFuncEvent = ara::com::internal::proxy::event::EventAdapter<::mdc::devm::StatusResultType>;
    using McuPowerEvent = ara::com::internal::proxy::event::EventAdapter<::mdc::devm::StatusResultType>;
    using SocSleepRequestEvent = ara::com::internal::proxy::event::EventAdapter<::mdc::mcu::ReqPowerType>;
    static constexpr ara::com::internal::EntityId DevInfoEventId = 1780; //DevInfoEvent_event_hash
    static constexpr ara::com::internal::EntityId McuFuncEventId = 42127; //McuFuncEvent_event_hash
    static constexpr ara::com::internal::EntityId McuPowerEventId = 10062; //McuPowerEvent_event_hash
    static constexpr ara::com::internal::EntityId SocSleepRequestEventId = 44820; //SocSleepRequestEvent_event_hash
}

namespace fields {
}

namespace methods {
static constexpr ara::com::internal::EntityId GetMcuDevInfoId = 11926; //GetMcuDevInfo_method_hash
static constexpr ara::com::internal::EntityId GetMcuOutRegId = 65447; //GetMcuOutReg_method_hash
static constexpr ara::com::internal::EntityId GetMcuRegId = 29374; //GetMcuReg_method_hash
static constexpr ara::com::internal::EntityId GetMcuStateId = 41287; //GetMcuState_method_hash
static constexpr ara::com::internal::EntityId GetMcuTaskListId = 39834; //GetMcuTaskList_method_hash
static constexpr ara::com::internal::EntityId GetMcuVersionId = 7103; //GetMcuVersion_method_hash
static constexpr ara::com::internal::EntityId GetStateId = 64093; //GetState_method_hash
static constexpr ara::com::internal::EntityId GetSysPowerOffInfoId = 26982; //GetSysPowerOffInfo_method_hash
static constexpr ara::com::internal::EntityId ResetMcuHardwareId = 42423; //ResetMcuHardware_method_hash
static constexpr ara::com::internal::EntityId ResetMcuSystemId = 2886; //ResetMcuSystem_method_hash
static constexpr ara::com::internal::EntityId SetChannelCtrlId = 1438; //SetChannelCtrl_method_hash
static constexpr ara::com::internal::EntityId SetInfoId = 45794; //SetInfo_method_hash
static constexpr ara::com::internal::EntityId SetMcuDevMgrId = 19067; //SetMcuDevMgr_method_hash
static constexpr ara::com::internal::EntityId SetMcuFuncId = 13908; //SetMcuFunc_method_hash
static constexpr ara::com::internal::EntityId SetMcuOutRegId = 55925; //SetMcuOutReg_method_hash
static constexpr ara::com::internal::EntityId SetMcuPowerId = 26157; //SetMcuPower_method_hash
static constexpr ara::com::internal::EntityId SetMcuRegId = 21656; //SetMcuReg_method_hash
static constexpr ara::com::internal::EntityId SetMcuWDogId = 47333; //SetMcuWDog_method_hash
static constexpr ara::com::internal::EntityId SetSysPowerOffInfoReadedId = 59997; //SetSysPowerOffInfoReaded_method_hash
static constexpr ara::com::internal::EntityId TerminateMcuTaskId = 10373; //TerminateMcuTask_method_hash
static constexpr ara::com::internal::EntityId TransSocTempToMcuId = 14866; //TransSocTempToMcu_method_hash


class GetMcuDevInfo {
public:
    using Output = void;

    GetMcuDevInfo(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<void> operator()(const ::UInt32& devId)
    {
        return method_(devId);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> method_;
};

class GetMcuOutReg {
public:
    struct Output {
        ::UInt32 regValRet;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(regValRet);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(regValRet);
        }

        bool operator == (const Output& t) const
        {
           return (regValRet == t.regValRet);
        }
    };

    GetMcuOutReg(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& regAddr)
    {
        return method_(regAddr);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> method_;
};

class GetMcuReg {
public:
    struct Output {
        ::UInt32 regValRet;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(regValRet);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(regValRet);
        }

        bool operator == (const Output& t) const
        {
           return (regValRet == t.regValRet);
        }
    };

    GetMcuReg(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& regAddr)
    {
        return method_(regAddr);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> method_;
};

class GetMcuState {
public:
    struct Output {
        ::UInt8 ctrlRet;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ctrlRet);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ctrlRet);
        }

        bool operator == (const Output& t) const
        {
           return (ctrlRet == t.ctrlRet);
        }
    };

    GetMcuState(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};

class GetMcuTaskList {
public:
    struct Output {
        ::UInt32 validLen;
        ::mdc::devm::TaskListResultType taskList;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(validLen);
            fun(taskList);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(validLen);
            fun(taskList);
        }

        bool operator == (const Output& t) const
        {
           return (validLen == t.validLen) && (taskList == t.taskList);
        }
    };

    GetMcuTaskList(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& reserved)
    {
        return method_(reserved);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> method_;
};

class GetMcuVersion {
public:
    struct Output {
        ::mdc::devm::VersionResultType chipType;
        ::mdc::devm::VersionResultType hwVersion;
        ::mdc::devm::VersionResultType swVersion;
        ::UInt8 upgradeable;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(chipType);
            fun(hwVersion);
            fun(swVersion);
            fun(upgradeable);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(chipType);
            fun(hwVersion);
            fun(swVersion);
            fun(upgradeable);
        }

        bool operator == (const Output& t) const
        {
           return (chipType == t.chipType) && (hwVersion == t.hwVersion) && (swVersion == t.swVersion) && (upgradeable == t.upgradeable);
        }
    };

    GetMcuVersion(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};

class GetState {
public:
    struct Output {
        ::UInt8 ctrlRet;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ctrlRet);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ctrlRet);
        }

        bool operator == (const Output& t) const
        {
           return (ctrlRet == t.ctrlRet);
        }
    };

    GetState(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& hostId)
    {
        return method_(hostId);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8> method_;
};

class GetSysPowerOffInfo {
public:
    struct Output {
        ::mdc::devm::UtcDateTime date;
        ::UInt8 reason;
        ::UInt8 result;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(date);
            fun(reason);
            fun(result);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(date);
            fun(reason);
            fun(result);
        }

        bool operator == (const Output& t) const
        {
           return (date == t.date) && (reason == t.reason) && (result == t.result);
        }
    };

    GetSysPowerOffInfo(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};

class ResetMcuHardware {
public:
    struct Output {
        ::UInt32 ctrlRet;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ctrlRet);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ctrlRet);
        }

        bool operator == (const Output& t) const
        {
           return (ctrlRet == t.ctrlRet);
        }
    };

    ResetMcuHardware(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& reserved)
    {
        return method_(reserved);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> method_;
};

class ResetMcuSystem {
public:
    struct Output {
        ::UInt32 ctrlRet;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ctrlRet);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ctrlRet);
        }

        bool operator == (const Output& t) const
        {
           return (ctrlRet == t.ctrlRet);
        }
    };

    ResetMcuSystem(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& reserved)
    {
        return method_(reserved);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> method_;
};

class SetChannelCtrl {
public:
    struct Output {
        ::UInt8 result;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }

        bool operator == (const Output& t) const
        {
           return (result == t.result);
        }
    };

    SetChannelCtrl(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& channel, const ::UInt8& state, const ::UInt8& type)
    {
        return method_(channel, state, type);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt8, ::UInt8> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt8, ::UInt8> method_;
};

class SetInfo {
public:
    struct Output {
        ::UInt8 result;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }

        bool operator == (const Output& t) const
        {
           return (result == t.result);
        }
    };

    SetInfo(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& type, const ::UInt32& dataSize, const ::mdc::devm::BufArray512& dataBuff)
    {
        return method_(type, dataSize, dataBuff);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt32, ::mdc::devm::BufArray512> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt32, ::mdc::devm::BufArray512> method_;
};

class SetMcuDevMgr {
public:
    struct Output {
        ::UInt32 ctrlRet;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ctrlRet);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ctrlRet);
        }

        bool operator == (const Output& t) const
        {
           return (ctrlRet == t.ctrlRet);
        }
    };

    SetMcuDevMgr(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& reserved)
    {
        return method_(reserved);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> method_;
};

class SetMcuFunc {
public:
    using Output = void;

    SetMcuFunc(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<void> operator()(const ::String& funcName, const ::UInt32& funcState)
    {
        return method_(funcName, funcState);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::String, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::String, ::UInt32> method_;
};

class SetMcuOutReg {
public:
    struct Output {
        ::UInt32 regSetResult;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(regSetResult);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(regSetResult);
        }

        bool operator == (const Output& t) const
        {
           return (regSetResult == t.regSetResult);
        }
    };

    SetMcuOutReg(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& regAddr, const ::UInt32& regVal)
    {
        return method_(regAddr, regVal);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt32> method_;
};

class SetMcuPower {
public:
    struct Output {
        ::UInt8 result;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }

        bool operator == (const Output& t) const
        {
           return (result == t.result);
        }
    };

    SetMcuPower(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& devId, const ::UInt32& powerState)
    {
        return method_(devId, powerState);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt32> method_;
};

class SetMcuReg {
public:
    struct Output {
        ::UInt32 regSetResult;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(regSetResult);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(regSetResult);
        }

        bool operator == (const Output& t) const
        {
           return (regSetResult == t.regSetResult);
        }
    };

    SetMcuReg(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& regAddr, const ::UInt32& regVal)
    {
        return method_(regAddr, regVal);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt32> method_;
};

class SetMcuWDog {
public:
    struct Output {
        ::UInt32 ctrlRet;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ctrlRet);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ctrlRet);
        }

        bool operator == (const Output& t) const
        {
           return (ctrlRet == t.ctrlRet);
        }
    };

    SetMcuWDog(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& wDogSystemMode, const ::UInt32& wDogType, const ::UInt32& wDogMode, const ::UInt32& wDogOWTime, const ::UInt32& wDogCWTime, const ::UInt32& wDogOffset)
    {
        return method_(wDogSystemMode, wDogType, wDogMode, wDogOWTime, wDogCWTime, wDogOffset);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt32, ::UInt32, ::UInt32, ::UInt32, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt32, ::UInt32, ::UInt32, ::UInt32, ::UInt32> method_;
};

class SetSysPowerOffInfoReaded {
public:
    struct Output {
        ::UInt8 result;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }

        bool operator == (const Output& t) const
        {
           return (result == t.result);
        }
    };

    SetSysPowerOffInfoReaded(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};

class TerminateMcuTask {
public:
    struct Output {
        ::UInt32 ctrlRet;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ctrlRet);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ctrlRet);
        }

        bool operator == (const Output& t) const
        {
           return (ctrlRet == t.ctrlRet);
        }
    };

    TerminateMcuTask(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& taskId)
    {
        return method_(taskId);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> method_;
};

class TransSocTempToMcu {
public:
    struct Output {
        ::UInt8 ret;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ret);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ret);
        }

        bool operator == (const Output& t) const
        {
           return (ret == t.ret);
        }
    };

    TransSocTempToMcu(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& hostId, const ::mdc::devm::Int32Array10& temp)
    {
        return method_(hostId, temp);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::mdc::devm::Int32Array10> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::mdc::devm::Int32Array10> method_;
};
} // namespace methods

class DevmMcuCtrlSomeipServiceInterfaceProxy {
private:
    std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxyAdapter;
public:
    using HandleType = vrtf::vcc::api::types::HandleType;
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxy): ptr(std::move(proxy)){}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> GetProxyAdapter()
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> ptr;
    };

    virtual ~DevmMcuCtrlSomeipServiceInterfaceProxy()
    {
        DevInfoEvent.UnsetReceiveHandler();
        DevInfoEvent.Unsubscribe();
        McuFuncEvent.UnsetReceiveHandler();
        McuFuncEvent.Unsubscribe();
        McuPowerEvent.UnsetReceiveHandler();
        McuPowerEvent.Unsubscribe();
        SocSleepRequestEvent.UnsetReceiveHandler();
        SocSleepRequestEvent.Unsubscribe();
    }

    explicit DevmMcuCtrlSomeipServiceInterfaceProxy(const vrtf::vcc::api::types::HandleType &handle)
        : proxyAdapter(std::make_unique<ara::com::internal::proxy::ProxyAdapter>(::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier, handle)),
          DevInfoEvent(proxyAdapter->GetProxy(), events::DevInfoEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier),
          McuFuncEvent(proxyAdapter->GetProxy(), events::McuFuncEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier),
          McuPowerEvent(proxyAdapter->GetProxy(), events::McuPowerEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier),
          SocSleepRequestEvent(proxyAdapter->GetProxy(), events::SocSleepRequestEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier),
          GetMcuDevInfo(proxyAdapter->GetProxy(), methods::GetMcuDevInfoId),
          GetMcuOutReg(proxyAdapter->GetProxy(), methods::GetMcuOutRegId),
          GetMcuReg(proxyAdapter->GetProxy(), methods::GetMcuRegId),
          GetMcuState(proxyAdapter->GetProxy(), methods::GetMcuStateId),
          GetMcuTaskList(proxyAdapter->GetProxy(), methods::GetMcuTaskListId),
          GetMcuVersion(proxyAdapter->GetProxy(), methods::GetMcuVersionId),
          GetState(proxyAdapter->GetProxy(), methods::GetStateId),
          GetSysPowerOffInfo(proxyAdapter->GetProxy(), methods::GetSysPowerOffInfoId),
          ResetMcuHardware(proxyAdapter->GetProxy(), methods::ResetMcuHardwareId),
          ResetMcuSystem(proxyAdapter->GetProxy(), methods::ResetMcuSystemId),
          SetChannelCtrl(proxyAdapter->GetProxy(), methods::SetChannelCtrlId),
          SetInfo(proxyAdapter->GetProxy(), methods::SetInfoId),
          SetMcuDevMgr(proxyAdapter->GetProxy(), methods::SetMcuDevMgrId),
          SetMcuFunc(proxyAdapter->GetProxy(), methods::SetMcuFuncId),
          SetMcuOutReg(proxyAdapter->GetProxy(), methods::SetMcuOutRegId),
          SetMcuPower(proxyAdapter->GetProxy(), methods::SetMcuPowerId),
          SetMcuReg(proxyAdapter->GetProxy(), methods::SetMcuRegId),
          SetMcuWDog(proxyAdapter->GetProxy(), methods::SetMcuWDogId),
          SetSysPowerOffInfoReaded(proxyAdapter->GetProxy(), methods::SetSysPowerOffInfoReadedId),
          TerminateMcuTask(proxyAdapter->GetProxy(), methods::TerminateMcuTaskId),
          TransSocTempToMcu(proxyAdapter->GetProxy(), methods::TransSocTempToMcuId){
            ara::core::Result<void> resultGetMcuDevInfo = proxyAdapter->InitializeMethod<methods::GetMcuDevInfo::Output>(methods::GetMcuDevInfoId);
            ThrowError(resultGetMcuDevInfo);
            ara::core::Result<void> resultGetMcuOutReg = proxyAdapter->InitializeMethod<methods::GetMcuOutReg::Output>(methods::GetMcuOutRegId);
            ThrowError(resultGetMcuOutReg);
            ara::core::Result<void> resultGetMcuReg = proxyAdapter->InitializeMethod<methods::GetMcuReg::Output>(methods::GetMcuRegId);
            ThrowError(resultGetMcuReg);
            ara::core::Result<void> resultGetMcuState = proxyAdapter->InitializeMethod<methods::GetMcuState::Output>(methods::GetMcuStateId);
            ThrowError(resultGetMcuState);
            ara::core::Result<void> resultGetMcuTaskList = proxyAdapter->InitializeMethod<methods::GetMcuTaskList::Output>(methods::GetMcuTaskListId);
            ThrowError(resultGetMcuTaskList);
            ara::core::Result<void> resultGetMcuVersion = proxyAdapter->InitializeMethod<methods::GetMcuVersion::Output>(methods::GetMcuVersionId);
            ThrowError(resultGetMcuVersion);
            ara::core::Result<void> resultGetState = proxyAdapter->InitializeMethod<methods::GetState::Output>(methods::GetStateId);
            ThrowError(resultGetState);
            ara::core::Result<void> resultGetSysPowerOffInfo = proxyAdapter->InitializeMethod<methods::GetSysPowerOffInfo::Output>(methods::GetSysPowerOffInfoId);
            ThrowError(resultGetSysPowerOffInfo);
            ara::core::Result<void> resultResetMcuHardware = proxyAdapter->InitializeMethod<methods::ResetMcuHardware::Output>(methods::ResetMcuHardwareId);
            ThrowError(resultResetMcuHardware);
            ara::core::Result<void> resultResetMcuSystem = proxyAdapter->InitializeMethod<methods::ResetMcuSystem::Output>(methods::ResetMcuSystemId);
            ThrowError(resultResetMcuSystem);
            ara::core::Result<void> resultSetChannelCtrl = proxyAdapter->InitializeMethod<methods::SetChannelCtrl::Output>(methods::SetChannelCtrlId);
            ThrowError(resultSetChannelCtrl);
            ara::core::Result<void> resultSetInfo = proxyAdapter->InitializeMethod<methods::SetInfo::Output>(methods::SetInfoId);
            ThrowError(resultSetInfo);
            ara::core::Result<void> resultSetMcuDevMgr = proxyAdapter->InitializeMethod<methods::SetMcuDevMgr::Output>(methods::SetMcuDevMgrId);
            ThrowError(resultSetMcuDevMgr);
            ara::core::Result<void> resultSetMcuFunc = proxyAdapter->InitializeMethod<methods::SetMcuFunc::Output>(methods::SetMcuFuncId);
            ThrowError(resultSetMcuFunc);
            ara::core::Result<void> resultSetMcuOutReg = proxyAdapter->InitializeMethod<methods::SetMcuOutReg::Output>(methods::SetMcuOutRegId);
            ThrowError(resultSetMcuOutReg);
            ara::core::Result<void> resultSetMcuPower = proxyAdapter->InitializeMethod<methods::SetMcuPower::Output>(methods::SetMcuPowerId);
            ThrowError(resultSetMcuPower);
            ara::core::Result<void> resultSetMcuReg = proxyAdapter->InitializeMethod<methods::SetMcuReg::Output>(methods::SetMcuRegId);
            ThrowError(resultSetMcuReg);
            ara::core::Result<void> resultSetMcuWDog = proxyAdapter->InitializeMethod<methods::SetMcuWDog::Output>(methods::SetMcuWDogId);
            ThrowError(resultSetMcuWDog);
            ara::core::Result<void> resultSetSysPowerOffInfoReaded = proxyAdapter->InitializeMethod<methods::SetSysPowerOffInfoReaded::Output>(methods::SetSysPowerOffInfoReadedId);
            ThrowError(resultSetSysPowerOffInfoReaded);
            ara::core::Result<void> resultTerminateMcuTask = proxyAdapter->InitializeMethod<methods::TerminateMcuTask::Output>(methods::TerminateMcuTaskId);
            ThrowError(resultTerminateMcuTask);
            ara::core::Result<void> resultTransSocTempToMcu = proxyAdapter->InitializeMethod<methods::TransSocTempToMcu::Output>(methods::TransSocTempToMcuId);
            ThrowError(resultTransSocTempToMcu);
        }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }

    DevmMcuCtrlSomeipServiceInterfaceProxy(const DevmMcuCtrlSomeipServiceInterfaceProxy&) = delete;
    DevmMcuCtrlSomeipServiceInterfaceProxy& operator=(const DevmMcuCtrlSomeipServiceInterfaceProxy&) = delete;

    DevmMcuCtrlSomeipServiceInterfaceProxy(DevmMcuCtrlSomeipServiceInterfaceProxy&& other) = default;
    DevmMcuCtrlSomeipServiceInterfaceProxy& operator=(DevmMcuCtrlSomeipServiceInterfaceProxy&& other) = default;
    DevmMcuCtrlSomeipServiceInterfaceProxy(ConstructionToken&& token) noexcept
        : proxyAdapter(token.GetProxyAdapter()),
          DevInfoEvent(proxyAdapter->GetProxy(), events::DevInfoEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier),
          McuFuncEvent(proxyAdapter->GetProxy(), events::McuFuncEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier),
          McuPowerEvent(proxyAdapter->GetProxy(), events::McuPowerEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier),
          SocSleepRequestEvent(proxyAdapter->GetProxy(), events::SocSleepRequestEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier),
          GetMcuDevInfo(proxyAdapter->GetProxy(), methods::GetMcuDevInfoId),
          GetMcuOutReg(proxyAdapter->GetProxy(), methods::GetMcuOutRegId),
          GetMcuReg(proxyAdapter->GetProxy(), methods::GetMcuRegId),
          GetMcuState(proxyAdapter->GetProxy(), methods::GetMcuStateId),
          GetMcuTaskList(proxyAdapter->GetProxy(), methods::GetMcuTaskListId),
          GetMcuVersion(proxyAdapter->GetProxy(), methods::GetMcuVersionId),
          GetState(proxyAdapter->GetProxy(), methods::GetStateId),
          GetSysPowerOffInfo(proxyAdapter->GetProxy(), methods::GetSysPowerOffInfoId),
          ResetMcuHardware(proxyAdapter->GetProxy(), methods::ResetMcuHardwareId),
          ResetMcuSystem(proxyAdapter->GetProxy(), methods::ResetMcuSystemId),
          SetChannelCtrl(proxyAdapter->GetProxy(), methods::SetChannelCtrlId),
          SetInfo(proxyAdapter->GetProxy(), methods::SetInfoId),
          SetMcuDevMgr(proxyAdapter->GetProxy(), methods::SetMcuDevMgrId),
          SetMcuFunc(proxyAdapter->GetProxy(), methods::SetMcuFuncId),
          SetMcuOutReg(proxyAdapter->GetProxy(), methods::SetMcuOutRegId),
          SetMcuPower(proxyAdapter->GetProxy(), methods::SetMcuPowerId),
          SetMcuReg(proxyAdapter->GetProxy(), methods::SetMcuRegId),
          SetMcuWDog(proxyAdapter->GetProxy(), methods::SetMcuWDogId),
          SetSysPowerOffInfoReaded(proxyAdapter->GetProxy(), methods::SetSysPowerOffInfoReadedId),
          TerminateMcuTask(proxyAdapter->GetProxy(), methods::TerminateMcuTaskId),
          TransSocTempToMcu(proxyAdapter->GetProxy(), methods::TransSocTempToMcuId){
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        const vrtf::vcc::api::types::HandleType &handle)
    {
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> preProxyAdapter =
            std::make_unique<ara::com::internal::proxy::ProxyAdapter>(
               ::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier, handle);
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            methods::GetMcuDevInfo GetMcuDevInfo(preProxyAdapter->GetProxy(), methods::GetMcuDevInfoId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetMcuDevInfo::Output>(methods::GetMcuDevInfoId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetMcuOutReg GetMcuOutReg(preProxyAdapter->GetProxy(), methods::GetMcuOutRegId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetMcuOutReg::Output>(methods::GetMcuOutRegId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetMcuReg GetMcuReg(preProxyAdapter->GetProxy(), methods::GetMcuRegId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetMcuReg::Output>(methods::GetMcuRegId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetMcuState GetMcuState(preProxyAdapter->GetProxy(), methods::GetMcuStateId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetMcuState::Output>(methods::GetMcuStateId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetMcuTaskList GetMcuTaskList(preProxyAdapter->GetProxy(), methods::GetMcuTaskListId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetMcuTaskList::Output>(methods::GetMcuTaskListId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetMcuVersion GetMcuVersion(preProxyAdapter->GetProxy(), methods::GetMcuVersionId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetMcuVersion::Output>(methods::GetMcuVersionId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetState GetState(preProxyAdapter->GetProxy(), methods::GetStateId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetState::Output>(methods::GetStateId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetSysPowerOffInfo GetSysPowerOffInfo(preProxyAdapter->GetProxy(), methods::GetSysPowerOffInfoId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetSysPowerOffInfo::Output>(methods::GetSysPowerOffInfoId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::ResetMcuHardware ResetMcuHardware(preProxyAdapter->GetProxy(), methods::ResetMcuHardwareId);
            initResult = preProxyAdapter->InitializeMethod<methods::ResetMcuHardware::Output>(methods::ResetMcuHardwareId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::ResetMcuSystem ResetMcuSystem(preProxyAdapter->GetProxy(), methods::ResetMcuSystemId);
            initResult = preProxyAdapter->InitializeMethod<methods::ResetMcuSystem::Output>(methods::ResetMcuSystemId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetChannelCtrl SetChannelCtrl(preProxyAdapter->GetProxy(), methods::SetChannelCtrlId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetChannelCtrl::Output>(methods::SetChannelCtrlId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetInfo SetInfo(preProxyAdapter->GetProxy(), methods::SetInfoId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetInfo::Output>(methods::SetInfoId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetMcuDevMgr SetMcuDevMgr(preProxyAdapter->GetProxy(), methods::SetMcuDevMgrId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetMcuDevMgr::Output>(methods::SetMcuDevMgrId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetMcuFunc SetMcuFunc(preProxyAdapter->GetProxy(), methods::SetMcuFuncId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetMcuFunc::Output>(methods::SetMcuFuncId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetMcuOutReg SetMcuOutReg(preProxyAdapter->GetProxy(), methods::SetMcuOutRegId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetMcuOutReg::Output>(methods::SetMcuOutRegId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetMcuPower SetMcuPower(preProxyAdapter->GetProxy(), methods::SetMcuPowerId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetMcuPower::Output>(methods::SetMcuPowerId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetMcuReg SetMcuReg(preProxyAdapter->GetProxy(), methods::SetMcuRegId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetMcuReg::Output>(methods::SetMcuRegId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetMcuWDog SetMcuWDog(preProxyAdapter->GetProxy(), methods::SetMcuWDogId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetMcuWDog::Output>(methods::SetMcuWDogId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetSysPowerOffInfoReaded SetSysPowerOffInfoReaded(preProxyAdapter->GetProxy(), methods::SetSysPowerOffInfoReadedId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetSysPowerOffInfoReaded::Output>(methods::SetSysPowerOffInfoReadedId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::TerminateMcuTask TerminateMcuTask(preProxyAdapter->GetProxy(), methods::TerminateMcuTaskId);
            initResult = preProxyAdapter->InitializeMethod<methods::TerminateMcuTask::Output>(methods::TerminateMcuTaskId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::TransSocTempToMcu TransSocTempToMcu(preProxyAdapter->GetProxy(), methods::TransSocTempToMcuId);
            initResult = preProxyAdapter->InitializeMethod<methods::TransSocTempToMcu::Output>(methods::TransSocTempToMcuId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preProxyAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preProxyAdapter));
            ara::core::Result<ConstructionToken> result(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            result.EmplaceError(errorcode);
            return result;
        }
    }


    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier, instance);
    }

    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier, specifier);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier, instance);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::devm::devm_mcu::DevmMcuCtrlSomeipServiceInterface::ServiceIdentifier, specifier);
    }

    static void StopFindService(const ara::com::FindServiceHandle& handle)
    {
        ara::com::internal::proxy::ProxyAdapter::StopFindService(handle);
    }

    HandleType GetHandle() const
    {
        return proxyAdapter->GetHandle();
    }
    events::DevInfoEvent DevInfoEvent;
    events::McuFuncEvent McuFuncEvent;
    events::McuPowerEvent McuPowerEvent;
    events::SocSleepRequestEvent SocSleepRequestEvent;
    methods::GetMcuDevInfo GetMcuDevInfo;
    methods::GetMcuOutReg GetMcuOutReg;
    methods::GetMcuReg GetMcuReg;
    methods::GetMcuState GetMcuState;
    methods::GetMcuTaskList GetMcuTaskList;
    methods::GetMcuVersion GetMcuVersion;
    methods::GetState GetState;
    methods::GetSysPowerOffInfo GetSysPowerOffInfo;
    methods::ResetMcuHardware ResetMcuHardware;
    methods::ResetMcuSystem ResetMcuSystem;
    methods::SetChannelCtrl SetChannelCtrl;
    methods::SetInfo SetInfo;
    methods::SetMcuDevMgr SetMcuDevMgr;
    methods::SetMcuFunc SetMcuFunc;
    methods::SetMcuOutReg SetMcuOutReg;
    methods::SetMcuPower SetMcuPower;
    methods::SetMcuReg SetMcuReg;
    methods::SetMcuWDog SetMcuWDog;
    methods::SetSysPowerOffInfoReaded SetSysPowerOffInfoReaded;
    methods::TerminateMcuTask TerminateMcuTask;
    methods::TransSocTempToMcu TransSocTempToMcu;
};
} // namespace proxy
} // namespace devm_mcu
} // namespace devm
} // namespace mdc

#endif // MDC_DEVM_DEVM_MCU_DEVMMCUCTRLSOMEIPSERVICEINTERFACE_PROXY_H
