/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_DEVM_MCU_DEVMMCUCONFIGTRANSERVICEINTERFACE_PROXY_H
#define MDC_DEVM_DEVM_MCU_DEVMMCUCONFIGTRANSERVICEINTERFACE_PROXY_H

#include "ara/com/internal/proxy/proxy_adapter.h"
#include "ara/com/internal/proxy/event_adapter.h"
#include "ara/com/internal/proxy/field_adapter.h"
#include "ara/com/internal/proxy/method_adapter.h"
#include "mdc/devm/devm_mcu/devmmcuconfigtranserviceinterface_common.h"
#include <string>
#include <cfloat>
#include <cmath>

namespace mdc {
namespace devm {
namespace devm_mcu {
namespace proxy {
namespace events {
    using DiagStateEvent = ara::com::internal::proxy::event::EventAdapter<::mdc::devm::DiagStateData>;
    using FaultReportEvent = ara::com::internal::proxy::event::EventAdapter<::mdc::devm::FaultData>;
    static constexpr ara::com::internal::EntityId DiagStateEventId = 51058; //DiagStateEvent_event_hash
    static constexpr ara::com::internal::EntityId FaultReportEventId = 18483; //FaultReportEvent_event_hash
}

namespace fields {
}

namespace methods {
static constexpr ara::com::internal::EntityId GetConfigFileId = 18681; //GetConfigFile_method_hash
static constexpr ara::com::internal::EntityId GetConfigModeId = 22647; //GetConfigMode_method_hash
static constexpr ara::com::internal::EntityId GetDynamicDataId = 24986; //GetDynamicData_method_hash
static constexpr ara::com::internal::EntityId GetMacAddrId = 30588; //GetMacAddr_method_hash
static constexpr ara::com::internal::EntityId SendConfigFileId = 55936; //SendConfigFile_method_hash
static constexpr ara::com::internal::EntityId SetConfigModeId = 58349; //SetConfigMode_method_hash


class GetConfigFile {
public:
    struct Output {
        ::UInt8 frameTotal;
        ::UInt32 frameSize;
        ::mdc::devm::BufArray512 frameBuff;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(frameTotal);
            fun(frameSize);
            fun(frameBuff);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(frameTotal);
            fun(frameSize);
            fun(frameBuff);
        }

        bool operator == (const Output& t) const
        {
           return (frameTotal == t.frameTotal) && (frameSize == t.frameSize) && (frameBuff == t.frameBuff);
        }
    };

    GetConfigFile(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& cfgType, const ::UInt8& frameIndex)
    {
        return method_(cfgType, frameIndex);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt8> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt8> method_;
};

class GetConfigMode {
public:
    struct Output {
        ::mdc::devm::ConfigModeType ConfigMode;
        ::mdc::devm::ResultCode ConfigResult;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ConfigMode);
            fun(ConfigResult);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ConfigMode);
            fun(ConfigResult);
        }

        bool operator == (const Output& t) const
        {
           return (ConfigMode == t.ConfigMode) && (ConfigResult == t.ConfigResult);
        }
    };

    GetConfigMode(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};

class GetDynamicData {
public:
    struct Output {
        ::UInt32 dataSize;
        ::mdc::devm::BufArray512 dataBuff;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(dataSize);
            fun(dataBuff);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(dataSize);
            fun(dataBuff);
        }

        bool operator == (const Output& t) const
        {
           return (dataSize == t.dataSize) && (dataBuff == t.dataBuff);
        }
    };

    GetDynamicData(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& type)
    {
        return method_(type);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8> method_;
};

class GetMacAddr {
public:
    struct Output {
        ::mdc::devm::MacAddress macAddress;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(macAddress);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(macAddress);
        }

        bool operator == (const Output& t) const
        {
           return (macAddress == t.macAddress);
        }
    };

    GetMacAddr(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};

class SendConfigFile {
public:
    struct Output {
        ::mdc::devm::ResultCode ConfigResult;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ConfigResult);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ConfigResult);
        }

        bool operator == (const Output& t) const
        {
           return (ConfigResult == t.ConfigResult);
        }
    };

    SendConfigFile(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& sendFrameNum, const ::UInt8& frameMaxNum, const ::mdc::devm::BufArray512& SendConfigBuf)
    {
        return method_(sendFrameNum, frameMaxNum, SendConfigBuf);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt8, ::mdc::devm::BufArray512> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt8, ::mdc::devm::BufArray512> method_;
};

class SetConfigMode {
public:
    struct Output {
        ::mdc::devm::ResultCode ConfigResult;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ConfigResult);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ConfigResult);
        }

        bool operator == (const Output& t) const
        {
           return (ConfigResult == t.ConfigResult);
        }
    };

    SetConfigMode(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& mode, const ::UInt8& key)
    {
        return method_(mode, key);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt8> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt8> method_;
};
} // namespace methods

class DevmMcuConfigTranServiceInterfaceProxy {
private:
    std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxyAdapter;
public:
    using HandleType = vrtf::vcc::api::types::HandleType;
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxy): ptr(std::move(proxy)){}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> GetProxyAdapter()
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> ptr;
    };

    virtual ~DevmMcuConfigTranServiceInterfaceProxy()
    {
        DiagStateEvent.UnsetReceiveHandler();
        DiagStateEvent.Unsubscribe();
        FaultReportEvent.UnsetReceiveHandler();
        FaultReportEvent.Unsubscribe();
    }

    explicit DevmMcuConfigTranServiceInterfaceProxy(const vrtf::vcc::api::types::HandleType &handle)
        : proxyAdapter(std::make_unique<ara::com::internal::proxy::ProxyAdapter>(::mdc::devm::devm_mcu::DevmMcuConfigTranServiceInterface::ServiceIdentifier, handle)),
          DiagStateEvent(proxyAdapter->GetProxy(), events::DiagStateEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuConfigTranServiceInterface::ServiceIdentifier),
          FaultReportEvent(proxyAdapter->GetProxy(), events::FaultReportEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuConfigTranServiceInterface::ServiceIdentifier),
          GetConfigFile(proxyAdapter->GetProxy(), methods::GetConfigFileId),
          GetConfigMode(proxyAdapter->GetProxy(), methods::GetConfigModeId),
          GetDynamicData(proxyAdapter->GetProxy(), methods::GetDynamicDataId),
          GetMacAddr(proxyAdapter->GetProxy(), methods::GetMacAddrId),
          SendConfigFile(proxyAdapter->GetProxy(), methods::SendConfigFileId),
          SetConfigMode(proxyAdapter->GetProxy(), methods::SetConfigModeId){
            ara::core::Result<void> resultGetConfigFile = proxyAdapter->InitializeMethod<methods::GetConfigFile::Output>(methods::GetConfigFileId);
            ThrowError(resultGetConfigFile);
            ara::core::Result<void> resultGetConfigMode = proxyAdapter->InitializeMethod<methods::GetConfigMode::Output>(methods::GetConfigModeId);
            ThrowError(resultGetConfigMode);
            ara::core::Result<void> resultGetDynamicData = proxyAdapter->InitializeMethod<methods::GetDynamicData::Output>(methods::GetDynamicDataId);
            ThrowError(resultGetDynamicData);
            ara::core::Result<void> resultGetMacAddr = proxyAdapter->InitializeMethod<methods::GetMacAddr::Output>(methods::GetMacAddrId);
            ThrowError(resultGetMacAddr);
            ara::core::Result<void> resultSendConfigFile = proxyAdapter->InitializeMethod<methods::SendConfigFile::Output>(methods::SendConfigFileId);
            ThrowError(resultSendConfigFile);
            ara::core::Result<void> resultSetConfigMode = proxyAdapter->InitializeMethod<methods::SetConfigMode::Output>(methods::SetConfigModeId);
            ThrowError(resultSetConfigMode);
        }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }

    DevmMcuConfigTranServiceInterfaceProxy(const DevmMcuConfigTranServiceInterfaceProxy&) = delete;
    DevmMcuConfigTranServiceInterfaceProxy& operator=(const DevmMcuConfigTranServiceInterfaceProxy&) = delete;

    DevmMcuConfigTranServiceInterfaceProxy(DevmMcuConfigTranServiceInterfaceProxy&& other) = default;
    DevmMcuConfigTranServiceInterfaceProxy& operator=(DevmMcuConfigTranServiceInterfaceProxy&& other) = default;
    DevmMcuConfigTranServiceInterfaceProxy(ConstructionToken&& token) noexcept
        : proxyAdapter(token.GetProxyAdapter()),
          DiagStateEvent(proxyAdapter->GetProxy(), events::DiagStateEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuConfigTranServiceInterface::ServiceIdentifier),
          FaultReportEvent(proxyAdapter->GetProxy(), events::FaultReportEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_mcu::DevmMcuConfigTranServiceInterface::ServiceIdentifier),
          GetConfigFile(proxyAdapter->GetProxy(), methods::GetConfigFileId),
          GetConfigMode(proxyAdapter->GetProxy(), methods::GetConfigModeId),
          GetDynamicData(proxyAdapter->GetProxy(), methods::GetDynamicDataId),
          GetMacAddr(proxyAdapter->GetProxy(), methods::GetMacAddrId),
          SendConfigFile(proxyAdapter->GetProxy(), methods::SendConfigFileId),
          SetConfigMode(proxyAdapter->GetProxy(), methods::SetConfigModeId){
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        const vrtf::vcc::api::types::HandleType &handle)
    {
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> preProxyAdapter =
            std::make_unique<ara::com::internal::proxy::ProxyAdapter>(
               ::mdc::devm::devm_mcu::DevmMcuConfigTranServiceInterface::ServiceIdentifier, handle);
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            methods::GetConfigFile GetConfigFile(preProxyAdapter->GetProxy(), methods::GetConfigFileId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetConfigFile::Output>(methods::GetConfigFileId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetConfigMode GetConfigMode(preProxyAdapter->GetProxy(), methods::GetConfigModeId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetConfigMode::Output>(methods::GetConfigModeId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetDynamicData GetDynamicData(preProxyAdapter->GetProxy(), methods::GetDynamicDataId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetDynamicData::Output>(methods::GetDynamicDataId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetMacAddr GetMacAddr(preProxyAdapter->GetProxy(), methods::GetMacAddrId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetMacAddr::Output>(methods::GetMacAddrId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SendConfigFile SendConfigFile(preProxyAdapter->GetProxy(), methods::SendConfigFileId);
            initResult = preProxyAdapter->InitializeMethod<methods::SendConfigFile::Output>(methods::SendConfigFileId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetConfigMode SetConfigMode(preProxyAdapter->GetProxy(), methods::SetConfigModeId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetConfigMode::Output>(methods::SetConfigModeId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preProxyAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preProxyAdapter));
            ara::core::Result<ConstructionToken> result(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            result.EmplaceError(errorcode);
            return result;
        }
    }


    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::devm::devm_mcu::DevmMcuConfigTranServiceInterface::ServiceIdentifier, instance);
    }

    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::devm::devm_mcu::DevmMcuConfigTranServiceInterface::ServiceIdentifier, specifier);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::devm::devm_mcu::DevmMcuConfigTranServiceInterface::ServiceIdentifier, instance);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::devm::devm_mcu::DevmMcuConfigTranServiceInterface::ServiceIdentifier, specifier);
    }

    static void StopFindService(const ara::com::FindServiceHandle& handle)
    {
        ara::com::internal::proxy::ProxyAdapter::StopFindService(handle);
    }

    HandleType GetHandle() const
    {
        return proxyAdapter->GetHandle();
    }
    events::DiagStateEvent DiagStateEvent;
    events::FaultReportEvent FaultReportEvent;
    methods::GetConfigFile GetConfigFile;
    methods::GetConfigMode GetConfigMode;
    methods::GetDynamicData GetDynamicData;
    methods::GetMacAddr GetMacAddr;
    methods::SendConfigFile SendConfigFile;
    methods::SetConfigMode SetConfigMode;
};
} // namespace proxy
} // namespace devm_mcu
} // namespace devm
} // namespace mdc

#endif // MDC_DEVM_DEVM_MCU_DEVMMCUCONFIGTRANSERVICEINTERFACE_PROXY_H
