/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_DEVM_MCU_DEVMMCUCTRLSOMEIPSERVICEINTERFACE_COMMON_H
#define MDC_DEVM_DEVM_MCU_DEVMMCUCTRLSOMEIPSERVICEINTERFACE_COMMON_H

#include "ara/com/types.h"
#include "mdc/devm/impl_type_devinforesulttype.h"
#include "mdc/devm/impl_type_statusresulttype.h"
#include "mdc/mcu/impl_type_reqpowertype.h"
#include "impl_type_uint32.h"
#include "impl_type_uint8.h"
#include "mdc/devm/impl_type_tasklistresulttype.h"
#include "mdc/devm/impl_type_versionresulttype.h"
#include "mdc/devm/impl_type_utcdatetime.h"
#include "mdc/devm/impl_type_bufarray512.h"
#include "impl_type_string.h"
#include "mdc/devm/impl_type_int32array10.h"

namespace mdc {
namespace devm {
namespace devm_mcu {
class DevmMcuCtrlSomeipServiceInterface {
public:
    constexpr DevmMcuCtrlSomeipServiceInterface() = default;
    constexpr static ara::com::ServiceIdentifierType ServiceIdentifier = ara::com::ServiceIdentifierType("/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlServiceInterface/DevmMcuCtrlSomeipServiceInterface");
    constexpr static ara::com::ServiceVersionType ServiceVersion = ara::com::ServiceVersionType("1.1");
};
} // namespace devm_mcu
} // namespace devm
} // namespace mdc

#endif // MDC_DEVM_DEVM_MCU_DEVMMCUCTRLSOMEIPSERVICEINTERFACE_COMMON_H
