/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#include "ara/chassis/chassisreportserviceinterface_proxy.h"
#include "ara/egotrajectory/egotrajectoryserviceinterface_proxy.h"
#include "ara/ins/insinfoserviceinterface_proxy.h"
#include "ara/samm/sammfeatureserviceinterface_skeleton.h"
#include "mdc/adsfi/objectarrayinterface_proxy.h"
#include "mdc/adsfi/trajetorypredictioninterface_proxy.h"
#include "mdc/cam/camera/cameradecodedmbufserviceinterface_proxy.h"
#include "mdc/cam/camera/cameradecodedserviceinterface_proxy.h"
#include "mdc/fm/fmqueryservice_proxy.h"
#include "mdc/fm/fmreporteventservice_proxy.h"
#include "mdc/location/locationserviceinterface_proxy.h"
#include "mdc/navigation/navigationresultserviceinterface_proxy.h"
