/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_CHASS_REPBAKUP_IMPL_TYPE_CHASSISREPBAKUPMSG_H
#define ARA_CHASS_REPBAKUP_IMPL_TYPE_CHASSISREPBAKUPMSG_H
#include <cfloat>
#include <cmath>
#include "impl_type_float.h"
#include "ara/chass/repbakup/impl_type_brakeinfo.h"
#include "ara/chass/repbakup/impl_type_chassisrepbakupheader.h"

namespace ara {
namespace chass {
namespace repbakup {
struct ChassisRepBakUpMsg {
    ::Float velocity;
    ::ara::chass::repbakup::BrakeInfo brake;
    ::ara::chass::repbakup::ChassisRepBakUpHeader header;

    static bool IsPlane()
    {
        return false;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(velocity);
        fun(brake);
        fun(header);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(velocity);
        fun(brake);
        fun(header);
    }

    bool operator == (const ::ara::chass::repbakup::ChassisRepBakUpMsg& t) const
    {
        return (fabs(velocity - t.velocity) < FLT_EPSILON) && (brake == t.brake) && (header == t.header);
    }
};
} // namespace repbakup
} // namespace chass
} // namespace ara


#endif // ARA_CHASS_REPBAKUP_IMPL_TYPE_CHASSISREPBAKUPMSG_H
