/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_EGOTRAJECTORY_IMPL_TYPE_WAYPOINT_H
#define ARA_EGOTRAJECTORY_IMPL_TYPE_WAYPOINT_H
#include <cfloat>
#include <cmath>
#include "impl_type_double.h"
#include "ara/egotrajectory/impl_type_header.h"
#include "impl_type_string.h"

namespace ara {
namespace egotrajectory {
struct WayPoint {
    ::Double x;
    ::Double y;
    ::Double z;
    ::Double theta;
    ::Double curvature;
    ::Double s;
    ::Double deltaCurvature;
    ::Double deltaX;
    ::Double deltaY;
    ::ara::egotrajectory::Header header;
    ::String laneId;

    static bool IsPlane()
    {
        return false;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(x);
        fun(y);
        fun(z);
        fun(theta);
        fun(curvature);
        fun(s);
        fun(deltaCurvature);
        fun(deltaX);
        fun(deltaY);
        fun(header);
        fun(laneId);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(x);
        fun(y);
        fun(z);
        fun(theta);
        fun(curvature);
        fun(s);
        fun(deltaCurvature);
        fun(deltaX);
        fun(deltaY);
        fun(header);
        fun(laneId);
    }

    bool operator == (const ::ara::egotrajectory::WayPoint& t) const
    {
        return (fabs(x - t.x) < FLT_EPSILON) && (fabs(y - t.y) < FLT_EPSILON) && (fabs(z - t.z) < FLT_EPSILON) && (fabs(theta - t.theta) < FLT_EPSILON) && (fabs(curvature - t.curvature) < FLT_EPSILON) && (fabs(s - t.s) < FLT_EPSILON) && (fabs(deltaCurvature - t.deltaCurvature) < FLT_EPSILON) && (fabs(deltaX - t.deltaX) < FLT_EPSILON) && (fabs(deltaY - t.deltaY) < FLT_EPSILON) && (header == t.header) && (laneId == t.laneId);
    }
};
} // namespace egotrajectory
} // namespace ara


#endif // ARA_EGOTRAJECTORY_IMPL_TYPE_WAYPOINT_H
