/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_IMPL_TYPE_LOGMSG_H
#define MDC_IMPL_TYPE_LOGMSG_H
#include "impl_type_string.h"

namespace mdc {
typedef String logMsg;
} // namespace mdc


#endif // MDC_IMPL_TYPE_LOGMSG_H
