// Generated by gencpp from file gen_h/wheelspeed.msg
// DO NOT EDIT!


#ifndef GEN_H_MESSAGE_WHEELSPEED_H
#define GEN_H_MESSAGE_WHEELSPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gen_h
{
template <class ContainerAllocator>
struct wheelspeed_
{
  typedef wheelspeed_<ContainerAllocator> Type;

  wheelspeed_()
    : ESCWhlRRSpd(0.0)
    , ESCWhlRLSpd(0.0)
    , ESCWhlFRSpd(0.0)
    , ESCWhlFLSpd(0.0)  {
    }
  wheelspeed_(const ContainerAllocator& _alloc)
    : ESCWhlRRSpd(0.0)
    , ESCWhlRLSpd(0.0)
    , ESCWhlFRSpd(0.0)
    , ESCWhlFLSpd(0.0)  {
  (void)_alloc;
    }



   typedef double _ESCWhlRRSpd_type;
  _ESCWhlRRSpd_type ESCWhlRRSpd;

   typedef double _ESCWhlRLSpd_type;
  _ESCWhlRLSpd_type ESCWhlRLSpd;

   typedef double _ESCWhlFRSpd_type;
  _ESCWhlFRSpd_type ESCWhlFRSpd;

   typedef double _ESCWhlFLSpd_type;
  _ESCWhlFLSpd_type ESCWhlFLSpd;





  typedef boost::shared_ptr< ::gen_h::wheelspeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gen_h::wheelspeed_<ContainerAllocator> const> ConstPtr;

}; // struct wheelspeed_

typedef ::gen_h::wheelspeed_<std::allocator<void> > wheelspeed;

typedef boost::shared_ptr< ::gen_h::wheelspeed > wheelspeedPtr;
typedef boost::shared_ptr< ::gen_h::wheelspeed const> wheelspeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gen_h::wheelspeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gen_h::wheelspeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gen_h::wheelspeed_<ContainerAllocator1> & lhs, const ::gen_h::wheelspeed_<ContainerAllocator2> & rhs)
{
  return lhs.ESCWhlRRSpd == rhs.ESCWhlRRSpd &&
    lhs.ESCWhlRLSpd == rhs.ESCWhlRLSpd &&
    lhs.ESCWhlFRSpd == rhs.ESCWhlFRSpd &&
    lhs.ESCWhlFLSpd == rhs.ESCWhlFLSpd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gen_h::wheelspeed_<ContainerAllocator1> & lhs, const ::gen_h::wheelspeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gen_h

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gen_h::wheelspeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gen_h::wheelspeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gen_h::wheelspeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gen_h::wheelspeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gen_h::wheelspeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gen_h::wheelspeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gen_h::wheelspeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc5f047f372dbda5b429016c987e81e3";
  }

  static const char* value(const ::gen_h::wheelspeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc5f047f372dbda5ULL;
  static const uint64_t static_value2 = 0xb429016c987e81e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::gen_h::wheelspeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gen_h/wheelspeed";
  }

  static const char* value(const ::gen_h::wheelspeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gen_h::wheelspeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ESCWhlRRSpd\n"
"float64 ESCWhlRLSpd\n"
"float64 ESCWhlFRSpd\n"
"float64 ESCWhlFLSpd\n"
;
  }

  static const char* value(const ::gen_h::wheelspeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gen_h::wheelspeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ESCWhlRRSpd);
      stream.next(m.ESCWhlRLSpd);
      stream.next(m.ESCWhlFRSpd);
      stream.next(m.ESCWhlFLSpd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheelspeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gen_h::wheelspeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gen_h::wheelspeed_<ContainerAllocator>& v)
  {
    s << indent << "ESCWhlRRSpd: ";
    Printer<double>::stream(s, indent + "  ", v.ESCWhlRRSpd);
    s << indent << "ESCWhlRLSpd: ";
    Printer<double>::stream(s, indent + "  ", v.ESCWhlRLSpd);
    s << indent << "ESCWhlFRSpd: ";
    Printer<double>::stream(s, indent + "  ", v.ESCWhlFRSpd);
    s << indent << "ESCWhlFLSpd: ";
    Printer<double>::stream(s, indent + "  ", v.ESCWhlFLSpd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEN_H_MESSAGE_WHEELSPEED_H
