/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef CAMERADETECTIONEXECUTABLE_NETWORK_BINDING_H
#define CAMERADETECTIONEXECUTABLE_NETWORK_BINDING_H

#include "ara/core/array.h"
#include "ara/core/instance_specifier.h"

namespace mdc {
namespace cam {
namespace camera {
namespace cameradecodedserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("CameraDetectionExecutable/CameraDetectionRootSwComponent/CameraDetectionImageDataRPort")
    };
} // namespace cameradecodedserviceinterface
} // namespace camera
} // namespace cam
} // namespace mdc

namespace mdc {
namespace adsfi {
namespace objectarrayinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("CameraDetectionExecutable/CameraDetectionRootSwComponent/CameraDetectionObjectArrayPPort")
    };
} // namespace objectarrayinterface
} // namespace adsfi
} // namespace mdc

#endif // CAMERADETECTIONEXECUTABLE_NETWORK_BINDING_H
