/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef CAMERALANEEXECUTABLE_NETWORK_BINDING_H
#define CAMERALANEEXECUTABLE_NETWORK_BINDING_H

#include "ara/core/array.h"
#include "ara/core/instance_specifier.h"

namespace mdc {
namespace cam {
namespace camera {
namespace cameradecodedmbufserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("CameraLaneExecutable/CameraLaneRootSwComponent/CameraLaneImageDataRPort")
    };
} // namespace cameradecodedmbufserviceinterface
} // namespace camera
} // namespace cam
} // namespace mdc

namespace mdc {
namespace adsfi {
namespace lanelinearrayinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("CameraLaneExecutable/CameraLaneRootSwComponent/CameraLaneLineArrayDatePPort")
    };
} // namespace lanelinearrayinterface
} // namespace adsfi
} // namespace mdc

#endif // CAMERALANEEXECUTABLE_NETWORK_BINDING_H
