/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef DEVMC_NETWORK_BINDING_H
#define DEVMC_NETWORK_BINDING_H

#include "ara/core/array.h"
#include "ara/core/instance_specifier.h"

namespace mdc {
namespace devm {
namespace devmc {
namespace devmcenterserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("devmc/devmc/DevmCenterToAppPPort")
    };
} // namespace devmcenterserviceinterface
} // namespace devmc
} // namespace devm
} // namespace mdc

namespace mdc {
namespace devm {
namespace devm_mcu_300f {
namespace devmmcu300fconfigtranserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("devmc/devmc/DevmCenterFromMcu300FConfigTransRPort")
    };
} // namespace devmmcu300fconfigtranserviceinterface
} // namespace devm_mcu_300f
} // namespace devm
} // namespace mdc

namespace mdc {
namespace devm {
namespace devm_mcu {
namespace devmmcucanctrlsomeipserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("devmc/devmc/DevmCenterFromMcuCanCtrlPort")
    };
} // namespace devmmcucanctrlsomeipserviceinterface
} // namespace devm_mcu
} // namespace devm
} // namespace mdc

namespace mdc {
namespace devm {
namespace devm_mcu {
namespace devmmcuctrlsomeipserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("devmc/devmc/DevmCenterFromMcuRPort")
    };
} // namespace devmmcuctrlsomeipserviceinterface
} // namespace devm_mcu
} // namespace devm
} // namespace mdc

namespace mdc {
namespace devm {
namespace devmn {
namespace devmnodeserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("devmc/devmc/DevmCenterFromNodeRPort")
    };
} // namespace devmnodeserviceinterface
} // namespace devmn
} // namespace devm
} // namespace mdc

namespace ara {
namespace diag {
namespace diagcomclient {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("devmc/devmc/")
    };
} // namespace diagcomclient
} // namespace diag
} // namespace ara

namespace mdc {
namespace fm {
namespace fmreporteventservice {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("devmc/devmc/DevmCenterFromFmRPort")
    };
} // namespace fmreporteventservice
} // namespace fm
} // namespace mdc

namespace mdc {
namespace license {
namespace licmserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("devmc/devmc/DevmCenterFromLicenseRPort")
    };
} // namespace licmserviceinterface
} // namespace license
} // namespace mdc

namespace mdc {
namespace mcu {
namespace mcucannetworkserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("devmc/devmc/DevmCenterFromMcuNetWorkRPort")
    };
} // namespace mcucannetworkserviceinterface
} // namespace mcu
} // namespace mdc

#endif // DEVMC_NETWORK_BINDING_H
