/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef DEVM_CLIENT_NETWORK_BINDING_H
#define DEVM_CLIENT_NETWORK_BINDING_H

#include "ara/core/array.h"
#include "ara/core/instance_specifier.h"

namespace mdc {
namespace devm {
namespace devmc {
namespace devmcenterserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("devm_client/devm_client/DevmAppFromCenterRPort")
    };
} // namespace devmcenterserviceinterface
} // namespace devmc
} // namespace devm
} // namespace mdc

#endif // DEVM_CLIENT_NETWORK_BINDING_H
