/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef DIAG_SERVER_LOGGING_BEHAVIOR_H
#define DIAG_SERVER_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // DIAG_SERVER_LOGGING_BEHAVIOR_H
