/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef FM_LIB_NETWORK_BINDING_H
#define FM_LIB_NETWORK_BINDING_H

#include "ara/core/array.h"
#include "ara/core/instance_specifier.h"

namespace mdc {
namespace fm {
namespace fmqueryservice {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("fm_lib/fm_lib/queryRPort")
    };
} // namespace fmqueryservice
} // namespace fm
} // namespace mdc

namespace mdc {
namespace fm {
namespace fmreporteventservice {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("fm_lib/fm_lib/reportEventRPort")
    };
} // namespace fmreporteventservice
} // namespace fm
} // namespace mdc

#endif // FM_LIB_NETWORK_BINDING_H
