/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef IMPL_TYPE_UINT16_H
#define IMPL_TYPE_UINT16_H
#include "impl_type_uint16_t.h"

typedef uint16_t UInt16;


#endif // IMPL_TYPE_UINT16_H
