/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef IMPL_TYPE_LANESERIESVECTOR_H
#define IMPL_TYPE_LANESERIESVECTOR_H
#include "ara/core/vector.h"
#include "ara/navigation/impl_type_laneseries.h"

using LaneSeriesVector = ara::core::Vector<ara::navigation::LaneSeries>;


#endif // IMPL_TYPE_LANESERIESVECTOR_H
