/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef IMPL_TYPE_UINT8ARRAY_H
#define IMPL_TYPE_UINT8ARRAY_H
#include "ara/core/vector.h"
#include "impl_type_uint8.h"

using Uint8Array = ara::core::Vector<UInt8>;


#endif // IMPL_TYPE_UINT8ARRAY_H
