/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef LIBCAN_FWD_CM_PORT_LOGGING_BEHAVIOR_H
#define LIBCAN_FWD_CM_PORT_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // LIBCAN_FWD_CM_PORT_LOGGING_BEHAVIOR_H
