/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef LIBCHASSIS_A_CM_NETWORK_BINDING_H
#define LIBCHASSIS_A_CM_NETWORK_BINDING_H

#include "ara/core/array.h"
#include "ara/core/instance_specifier.h"

namespace ara {
namespace cantp {
namespace cantpmsgserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 2> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("libchassis_a_cm/libchassis_a_cm/ChassisCMFromCanTpRPort"),
        ara::core::InstanceSpecifier("libchassis_a_cm/libchassis_a_cm/ChassisCMToCanTpPPort")
    };
} // namespace cantpmsgserviceinterface
} // namespace cantp
} // namespace ara

namespace ara {
namespace chassiscmd {
namespace chassiscommandserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("libchassis_a_cm/libchassis_a_cm/ChassisFromAppRPort")
    };
} // namespace chassiscommandserviceinterface
} // namespace chassiscmd
} // namespace ara

namespace ara {
namespace chassis {
namespace chassisreportserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("libchassis_a_cm/libchassis_a_cm/ChassisToAppPPort")
    };
} // namespace chassisreportserviceinterface
} // namespace chassis
} // namespace ara

namespace ara {
namespace dataflow {
namespace dataflowserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("libchassis_a_cm/libchassis_a_cm/ChassisDataFlowPPort")
    };
} // namespace dataflowserviceinterface
} // namespace dataflow
} // namespace ara

namespace ara {
namespace timedelay {
namespace timedelayserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("libchassis_a_cm/libchassis_a_cm/ChassisTimeDelayPPort")
    };
} // namespace timedelayserviceinterface
} // namespace timedelay
} // namespace ara

#endif // LIBCHASSIS_A_CM_NETWORK_BINDING_H
