/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef LIDARTRACKEREXECUTABLE_NETWORK_BINDING_H
#define LIDARTRACKEREXECUTABLE_NETWORK_BINDING_H

#include "ara/core/array.h"
#include "ara/core/instance_specifier.h"

namespace ara {
namespace lidar {
namespace lidarserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("LidarTrackerExecutable/LidarTrackerRootSwComponent/LidarTrackerLidarDataRPort")
    };
} // namespace lidarserviceinterface
} // namespace lidar
} // namespace ara

namespace mdc {
namespace location {
namespace locationserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("LidarTrackerExecutable/LidarTrackerRootSwComponent/LidarTrackerLocationDataRPort")
    };
} // namespace locationserviceinterface
} // namespace location
} // namespace mdc

namespace mdc {
namespace adsfi {
namespace objectarrayinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 2> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("LidarTrackerExecutable/LidarTrackerRootSwComponent/LidarTrackerObjectArrayPPort"),
        ara::core::InstanceSpecifier("LidarTrackerExecutable/LidarTrackerRootSwComponent/LidarTrackerObjectArrayRPort")
    };
} // namespace objectarrayinterface
} // namespace adsfi
} // namespace mdc

#endif // LIDARTRACKEREXECUTABLE_NETWORK_BINDING_H
