/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef MCU_TOOL_PLUGIN_LOGGING_BEHAVIOR_H
#define MCU_TOOL_PLUGIN_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // MCU_TOOL_PLUGIN_LOGGING_BEHAVIOR_H
