/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef PLANNINGEXECUTABLE_NETWORK_BINDING_H
#define PLANNINGEXECUTABLE_NETWORK_BINDING_H

#include "ara/core/array.h"
#include "ara/core/instance_specifier.h"

namespace ara {
namespace chassis {
namespace chassisreportserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("PlanningExecutable/PlanningRootSwComponent/PlanningChassisReportRPort")
    };
} // namespace chassisreportserviceinterface
} // namespace chassis
} // namespace ara

namespace ara {
namespace egotrajectory {
namespace egotrajectoryserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("PlanningExecutable/PlanningRootSwComponent/PlanningEgoTrajectoryPPort")
    };
} // namespace egotrajectoryserviceinterface
} // namespace egotrajectory
} // namespace ara

namespace mdc {
namespace adsfi {
namespace lanelinearrayinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("PlanningExecutable/PlanningRootSwComponent/PlanningLaneLineFusionRPort")
    };
} // namespace lanelinearrayinterface
} // namespace adsfi
} // namespace mdc

namespace mdc {
namespace location {
namespace locationserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("PlanningExecutable/PlanningRootSwComponent/PlanningVehicleStateRPort")
    };
} // namespace locationserviceinterface
} // namespace location
} // namespace mdc

namespace mdc {
namespace navigation {
namespace navigationresultserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("PlanningExecutable/PlanningRootSwComponent/PlanningNavigationRPort")
    };
} // namespace navigationresultserviceinterface
} // namespace navigation
} // namespace mdc

namespace mdc {
namespace adsfi {
namespace objectarrayinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("PlanningExecutable/PlanningRootSwComponent/PlanningObjectArrayFusionRPort")
    };
} // namespace objectarrayinterface
} // namespace adsfi
} // namespace mdc

namespace mdc {
namespace trafficlight {
namespace trafficlightinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("PlanningExecutable/PlanningRootSwComponent/PlanningTrafficLightRPort")
    };
} // namespace trafficlightinterface
} // namespace trafficlight
} // namespace mdc

namespace mdc {
namespace adsfi {
namespace trajetorypredictioninterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("PlanningExecutable/PlanningRootSwComponent/PlanningTrajectoryPredictionRPort")
    };
} // namespace trajetorypredictioninterface
} // namespace adsfi
} // namespace mdc

#endif // PLANNINGEXECUTABLE_NETWORK_BINDING_H
