/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef SWM_CENTER_LOGGING_BEHAVIOR_H
#define SWM_CENTER_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // SWM_CENTER_LOGGING_BEHAVIOR_H
