/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef TIME_SYNCHRONIZATION_NETWORK_BINDING_H
#define TIME_SYNCHRONIZATION_NETWORK_BINDING_H

#include "ara/core/array.h"
#include "ara/core/instance_specifier.h"

namespace mdc {
namespace devm {
namespace devmc {
namespace devmcenterserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("time_synchronization/time_synchronization/")
    };
} // namespace devmcenterserviceinterface
} // namespace devmc
} // namespace devm
} // namespace mdc

namespace ara {
namespace diag {
namespace diagcomclient {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("time_synchronization/time_synchronization/")
    };
} // namespace diagcomclient
} // namespace diag
} // namespace ara

namespace mdc {
namespace timesync {
namespace timesyncserviceinterface {
    const ara::core::Array<ara::core::InstanceSpecifier, 1> INSTANCE_SPECIFIERS = {
        ara::core::InstanceSpecifier("time_synchronization/time_synchronization/TimeSyncFromAppRPort")
    };
} // namespace timesyncserviceinterface
} // namespace timesync
} // namespace mdc

#endif // TIME_SYNCHRONIZATION_NETWORK_BINDING_H
