/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef UPDATE_MANAGER_LOGGING_BEHAVIOR_H
#define UPDATE_MANAGER_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // UPDATE_MANAGER_LOGGING_BEHAVIOR_H
