/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_FM_FMQUERYSERVICE_PROXY_H
#define MDC_FM_FMQUERYSERVICE_PROXY_H

#include "ara/com/internal/proxy/proxy_adapter.h"
#include "ara/com/internal/proxy/event_adapter.h"
#include "ara/com/internal/proxy/field_adapter.h"
#include "ara/com/internal/proxy/method_adapter.h"
#include "mdc/fm/fmqueryservice_common.h"
#include <string>
#include <cfloat>
#include <cmath>

namespace mdc {
namespace fm {
namespace proxy {
namespace events {
}

namespace fields {
}

namespace methods {
static constexpr ara::com::internal::EntityId QueryFaultDetailId = 36459; //QueryFaultDetail_method_hash
static constexpr ara::com::internal::EntityId QueryFaultOnFlagId = 43267; //QueryFaultOnFlag_method_hash


class QueryFaultDetail {
public:
    struct Output {
        ::mdc::fm::FmFaultDetailVector faultDetailVec;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(faultDetailVec);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(faultDetailVec);
        }

        bool operator == (const Output& t) const
        {
           return (faultDetailVec == t.faultDetailVec);
        }
    };

    QueryFaultDetail(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};

class QueryFaultOnFlag {
public:
    struct Output {
        ::mdc::fm::FmFaultDetailVector faultDetailVec;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(faultDetailVec);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(faultDetailVec);
        }

        bool operator == (const Output& t) const
        {
           return (faultDetailVec == t.faultDetailVec);
        }
    };

    QueryFaultOnFlag(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& flag)
    {
        return method_(flag);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32> method_;
};
} // namespace methods

class FmQueryServiceProxy {
private:
    std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxyAdapter;
public:
    using HandleType = vrtf::vcc::api::types::HandleType;
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxy): ptr(std::move(proxy)){}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> GetProxyAdapter()
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> ptr;
    };

    virtual ~FmQueryServiceProxy()
    {
    }

    explicit FmQueryServiceProxy(const vrtf::vcc::api::types::HandleType &handle)
        : proxyAdapter(std::make_unique<ara::com::internal::proxy::ProxyAdapter>(::mdc::fm::FmQueryService::ServiceIdentifier, handle)),
          QueryFaultDetail(proxyAdapter->GetProxy(), methods::QueryFaultDetailId),
          QueryFaultOnFlag(proxyAdapter->GetProxy(), methods::QueryFaultOnFlagId){
            ara::core::Result<void> resultQueryFaultDetail = proxyAdapter->InitializeMethod<methods::QueryFaultDetail::Output>(methods::QueryFaultDetailId);
            ThrowError(resultQueryFaultDetail);
            ara::core::Result<void> resultQueryFaultOnFlag = proxyAdapter->InitializeMethod<methods::QueryFaultOnFlag::Output>(methods::QueryFaultOnFlagId);
            ThrowError(resultQueryFaultOnFlag);
        }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }

    FmQueryServiceProxy(const FmQueryServiceProxy&) = delete;
    FmQueryServiceProxy& operator=(const FmQueryServiceProxy&) = delete;

    FmQueryServiceProxy(FmQueryServiceProxy&& other) = default;
    FmQueryServiceProxy& operator=(FmQueryServiceProxy&& other) = default;
    FmQueryServiceProxy(ConstructionToken&& token) noexcept
        : proxyAdapter(token.GetProxyAdapter()),
          QueryFaultDetail(proxyAdapter->GetProxy(), methods::QueryFaultDetailId),
          QueryFaultOnFlag(proxyAdapter->GetProxy(), methods::QueryFaultOnFlagId){
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        const vrtf::vcc::api::types::HandleType &handle)
    {
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> preProxyAdapter =
            std::make_unique<ara::com::internal::proxy::ProxyAdapter>(
               ::mdc::fm::FmQueryService::ServiceIdentifier, handle);
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            methods::QueryFaultDetail QueryFaultDetail(preProxyAdapter->GetProxy(), methods::QueryFaultDetailId);
            initResult = preProxyAdapter->InitializeMethod<methods::QueryFaultDetail::Output>(methods::QueryFaultDetailId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::QueryFaultOnFlag QueryFaultOnFlag(preProxyAdapter->GetProxy(), methods::QueryFaultOnFlagId);
            initResult = preProxyAdapter->InitializeMethod<methods::QueryFaultOnFlag::Output>(methods::QueryFaultOnFlagId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preProxyAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preProxyAdapter));
            ara::core::Result<ConstructionToken> result(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            result.EmplaceError(errorcode);
            return result;
        }
    }


    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::fm::FmQueryService::ServiceIdentifier, instance);
    }

    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::fm::FmQueryService::ServiceIdentifier, specifier);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::fm::FmQueryService::ServiceIdentifier, instance);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::fm::FmQueryService::ServiceIdentifier, specifier);
    }

    static void StopFindService(const ara::com::FindServiceHandle& handle)
    {
        ara::com::internal::proxy::ProxyAdapter::StopFindService(handle);
    }

    HandleType GetHandle() const
    {
        return proxyAdapter->GetHandle();
    }
    methods::QueryFaultDetail QueryFaultDetail;
    methods::QueryFaultOnFlag QueryFaultOnFlag;
};
} // namespace proxy
} // namespace fm
} // namespace mdc

#endif // MDC_FM_FMQUERYSERVICE_PROXY_H
