/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_IMPL_TYPE_PACKAGEINFOTYPE_H
#define MDC_DEVM_IMPL_TYPE_PACKAGEINFOTYPE_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"
#include "mdc/devm/impl_type_framesyncconfigparam.h"
#include "mdc/devm/impl_type_headlengthconfigpara.h"
#include "mdc/devm/impl_type_datalengthconfigpara.h"
#include "mdc/devm/impl_type_packagechecksumconfigpara.h"

namespace mdc {
namespace devm {
struct PackageInfoType {
    ::UInt8 headType;
    ::UInt8 dataType;
    ::mdc::devm::FrameSyncConfigParam frameSyncConfig;
    ::mdc::devm::HeadLengthConfigPara packageHeadIdConfig;
    ::mdc::devm::DataLengthConfigPara packageLengthConfig;
    ::mdc::devm::PackageChecksumConfigPara packageChecksumConfig;

    static bool IsPlane()
    {
        return false;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(headType);
        fun(dataType);
        fun(frameSyncConfig);
        fun(packageHeadIdConfig);
        fun(packageLengthConfig);
        fun(packageChecksumConfig);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(headType);
        fun(dataType);
        fun(frameSyncConfig);
        fun(packageHeadIdConfig);
        fun(packageLengthConfig);
        fun(packageChecksumConfig);
    }

    bool operator == (const ::mdc::devm::PackageInfoType& t) const
    {
        return (headType == t.headType) && (dataType == t.dataType) && (frameSyncConfig == t.frameSyncConfig) && (packageHeadIdConfig == t.packageHeadIdConfig) && (packageLengthConfig == t.packageLengthConfig) && (packageChecksumConfig == t.packageChecksumConfig);
    }
};
} // namespace devm
} // namespace mdc


#endif // MDC_DEVM_IMPL_TYPE_PACKAGEINFOTYPE_H
