/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_IMPL_TYPE_MAPPINGENUM_H
#define MDC_DEVM_IMPL_TYPE_MAPPINGENUM_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint32.h"

namespace mdc {
namespace devm {
struct MappingEnum {
    ::UInt32 sourceSignalEnumValue;
    ::UInt32 targetSignalEnumValue;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(sourceSignalEnumValue);
        fun(targetSignalEnumValue);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(sourceSignalEnumValue);
        fun(targetSignalEnumValue);
    }

    bool operator == (const ::mdc::devm::MappingEnum& t) const
    {
        return (sourceSignalEnumValue == t.sourceSignalEnumValue) && (targetSignalEnumValue == t.targetSignalEnumValue);
    }
};
} // namespace devm
} // namespace mdc


#endif // MDC_DEVM_IMPL_TYPE_MAPPINGENUM_H
