/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_IMPL_TYPE_INT32ARRAY10_H
#define MDC_DEVM_IMPL_TYPE_INT32ARRAY10_H
#include "ara/core/array.h"
#include "impl_type_int32.h"

namespace mdc {
namespace devm {
using Int32Array10 = ara::core::Array<Int32, 10>;
} // namespace devm
} // namespace mdc


#endif // MDC_DEVM_IMPL_TYPE_INT32ARRAY10_H
