/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_IMPL_TYPE_CANCONFIGPARAM_H
#define MDC_DEVM_IMPL_TYPE_CANCONFIGPARAM_H
#include <cfloat>
#include <cmath>
#include "mdc/devm/impl_type_canbusconfigparamlist.h"
#include "mdc/devm/impl_type_compensationlist.h"

namespace mdc {
namespace devm {
struct CanConfigParam {
    ::mdc::devm::CanBusConfigParamList canBusConfigParam;
    ::mdc::devm::CompensationList compensation;

    static bool IsPlane()
    {
        return false;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(canBusConfigParam);
        fun(compensation);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(canBusConfigParam);
        fun(compensation);
    }

    bool operator == (const ::mdc::devm::CanConfigParam& t) const
    {
        return (canBusConfigParam == t.canBusConfigParam) && (compensation == t.compensation);
    }
};
} // namespace devm
} // namespace mdc


#endif // MDC_DEVM_IMPL_TYPE_CANCONFIGPARAM_H
