/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_IMPL_TYPE_COMPENSATIONLIST_H
#define MDC_DEVM_IMPL_TYPE_COMPENSATIONLIST_H
#include "ara/core/vector.h"
#include "mdc/devm/impl_type_compensation.h"

namespace mdc {
namespace devm {
using CompensationList = ara::core::Vector<mdc::devm::Compensation>;
} // namespace devm
} // namespace mdc


#endif // MDC_DEVM_IMPL_TYPE_COMPENSATIONLIST_H
