/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_IMPL_TYPE_UARTCHANNELELEMTYPE_H
#define MDC_DEVM_IMPL_TYPE_UARTCHANNELELEMTYPE_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint32.h"
#include "mdc/devm/impl_type_packageinfotypelist.h"

namespace mdc {
namespace devm {
struct UartChannelElemType {
    ::UInt32 baudRate;
    ::mdc::devm::PackageInfoTypeList packageInfo;

    static bool IsPlane()
    {
        return false;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(baudRate);
        fun(packageInfo);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(baudRate);
        fun(packageInfo);
    }

    bool operator == (const ::mdc::devm::UartChannelElemType& t) const
    {
        return (baudRate == t.baudRate) && (packageInfo == t.packageInfo);
    }
};
} // namespace devm
} // namespace mdc


#endif // MDC_DEVM_IMPL_TYPE_UARTCHANNELELEMTYPE_H
