/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef IMPL_TYPE_GIDSTATUSSTRUCT_H
#define IMPL_TYPE_GIDSTATUSSTRUCT_H
#include "impl_type_bytearray.h"
namespace ara {
namespace diag {
struct GidStatusStruct {
    ByteArray gid;

    uint8_t furtherActionReq;

    uint8_t syncStatus;

    static bool IsPlane()
    {
        return false;
    }

    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(gid);
        fun(furtherActionReq);
        fun(syncStatus);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(gid);
        fun(furtherActionReq);
        fun(syncStatus);
    }

    bool operator==(const GidStatusStruct& t) const
    {
        return (t.gid == gid) && (furtherActionReq == t.furtherActionReq) && (syncStatus == t.syncStatus);
    }
};
} /* namespace diag */
} /* namespace ara */
#endif // IMPL_TYPE_GIDSTATUSSTRUCT_H
