/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_MCU_MCUCANNETWORKSERVICEINTERFACE_PROXY_H
#define MDC_MCU_MCUCANNETWORKSERVICEINTERFACE_PROXY_H

#include "ara/com/internal/proxy/proxy_adapter.h"
#include "ara/com/internal/proxy/event_adapter.h"
#include "ara/com/internal/proxy/field_adapter.h"
#include "ara/com/internal/proxy/method_adapter.h"
#include "mdc/mcu/mcucannetworkserviceinterface_common.h"
#include <string>
#include <cfloat>
#include <cmath>

namespace mdc {
namespace mcu {
namespace proxy {
namespace events {
    using WorkModeEvent = ara::com::internal::proxy::event::EventAdapter<::mdc::mcu::WorkMode>;
    static constexpr ara::com::internal::EntityId WorkModeEventId = 19493; //WorkModeEvent_event_hash
}

namespace fields {
}

namespace methods {
static constexpr ara::com::internal::EntityId CanNetMgrCtrlId = 34824; //CanNetMgrCtrl_method_hash
static constexpr ara::com::internal::EntityId GetWorkModeId = 52134; //GetWorkMode_method_hash
static constexpr ara::com::internal::EntityId NotifySystemActionId = 40499; //NotifySystemAction_method_hash
static constexpr ara::com::internal::EntityId RequestWorkModeId = 1678; //RequestWorkMode_method_hash
static constexpr ara::com::internal::EntityId SetMcuSystemStatusId = 20332; //SetMcuSystemStatus_method_hash
static constexpr ara::com::internal::EntityId SetWorkModeId = 50407; //SetWorkMode_method_hash


class CanNetMgrCtrl {
public:
    struct Output {
        ::UInt8 result;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }

        bool operator == (const Output& t) const
        {
           return (result == t.result);
        }
    };

    CanNetMgrCtrl(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& ctrlType)
    {
        return method_(ctrlType);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8> method_;
};

class GetWorkMode {
public:
    struct Output {
        ::UInt32 curMode;
        ::UInt8 res;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(curMode);
            fun(res);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(curMode);
            fun(res);
        }

        bool operator == (const Output& t) const
        {
           return (curMode == t.curMode) && (res == t.res);
        }
    };

    GetWorkMode(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};

class NotifySystemAction {
public:
    struct Output {
        ::UInt8 result;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }

        bool operator == (const Output& t) const
        {
           return (result == t.result);
        }
    };

    NotifySystemAction(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& type, const ::UInt32& dataSize, const ::mdc::devm::BufArray64& dataBuff)
    {
        return method_(type, dataSize, dataBuff);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt32, ::mdc::devm::BufArray64> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8, ::UInt32, ::mdc::devm::BufArray64> method_;
};

class RequestWorkMode {
public:
    struct Output {
        ::UInt8 res;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(res);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(res);
        }

        bool operator == (const Output& t) const
        {
           return (res == t.res);
        }
    };

    RequestWorkMode(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& mode, const ::UInt32& size, const ::mdc::mcu::BufArray64& buff)
    {
        return method_(mode, size, buff);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt32, ::mdc::mcu::BufArray64> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt32, ::mdc::mcu::BufArray64> method_;
};

class SetMcuSystemStatus {
public:
    struct Output {
        ::UInt8 result;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }

        bool operator == (const Output& t) const
        {
           return (result == t.result);
        }
    };

    SetMcuSystemStatus(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& type)
    {
        return method_(type);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8> method_;
};

class SetWorkMode {
public:
    struct Output {
        ::UInt8 result;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }

        bool operator == (const Output& t) const
        {
           return (result == t.result);
        }
    };

    SetWorkMode(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt8& mode)
    {
        return method_(mode);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt8> method_;
};
} // namespace methods

class McuCanNetWorkServiceInterfaceProxy {
private:
    std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxyAdapter;
public:
    using HandleType = vrtf::vcc::api::types::HandleType;
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxy): ptr(std::move(proxy)){}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> GetProxyAdapter()
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> ptr;
    };

    virtual ~McuCanNetWorkServiceInterfaceProxy()
    {
        WorkModeEvent.UnsetReceiveHandler();
        WorkModeEvent.Unsubscribe();
    }

    explicit McuCanNetWorkServiceInterfaceProxy(const vrtf::vcc::api::types::HandleType &handle)
        : proxyAdapter(std::make_unique<ara::com::internal::proxy::ProxyAdapter>(::mdc::mcu::McuCanNetWorkServiceInterface::ServiceIdentifier, handle)),
          WorkModeEvent(proxyAdapter->GetProxy(), events::WorkModeEventId, proxyAdapter->GetHandle(), ::mdc::mcu::McuCanNetWorkServiceInterface::ServiceIdentifier),
          CanNetMgrCtrl(proxyAdapter->GetProxy(), methods::CanNetMgrCtrlId),
          GetWorkMode(proxyAdapter->GetProxy(), methods::GetWorkModeId),
          NotifySystemAction(proxyAdapter->GetProxy(), methods::NotifySystemActionId),
          RequestWorkMode(proxyAdapter->GetProxy(), methods::RequestWorkModeId),
          SetMcuSystemStatus(proxyAdapter->GetProxy(), methods::SetMcuSystemStatusId),
          SetWorkMode(proxyAdapter->GetProxy(), methods::SetWorkModeId){
            ara::core::Result<void> resultCanNetMgrCtrl = proxyAdapter->InitializeMethod<methods::CanNetMgrCtrl::Output>(methods::CanNetMgrCtrlId);
            ThrowError(resultCanNetMgrCtrl);
            ara::core::Result<void> resultGetWorkMode = proxyAdapter->InitializeMethod<methods::GetWorkMode::Output>(methods::GetWorkModeId);
            ThrowError(resultGetWorkMode);
            ara::core::Result<void> resultNotifySystemAction = proxyAdapter->InitializeMethod<methods::NotifySystemAction::Output>(methods::NotifySystemActionId);
            ThrowError(resultNotifySystemAction);
            ara::core::Result<void> resultRequestWorkMode = proxyAdapter->InitializeMethod<methods::RequestWorkMode::Output>(methods::RequestWorkModeId);
            ThrowError(resultRequestWorkMode);
            ara::core::Result<void> resultSetMcuSystemStatus = proxyAdapter->InitializeMethod<methods::SetMcuSystemStatus::Output>(methods::SetMcuSystemStatusId);
            ThrowError(resultSetMcuSystemStatus);
            ara::core::Result<void> resultSetWorkMode = proxyAdapter->InitializeMethod<methods::SetWorkMode::Output>(methods::SetWorkModeId);
            ThrowError(resultSetWorkMode);
        }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }

    McuCanNetWorkServiceInterfaceProxy(const McuCanNetWorkServiceInterfaceProxy&) = delete;
    McuCanNetWorkServiceInterfaceProxy& operator=(const McuCanNetWorkServiceInterfaceProxy&) = delete;

    McuCanNetWorkServiceInterfaceProxy(McuCanNetWorkServiceInterfaceProxy&& other) = default;
    McuCanNetWorkServiceInterfaceProxy& operator=(McuCanNetWorkServiceInterfaceProxy&& other) = default;
    McuCanNetWorkServiceInterfaceProxy(ConstructionToken&& token) noexcept
        : proxyAdapter(token.GetProxyAdapter()),
          WorkModeEvent(proxyAdapter->GetProxy(), events::WorkModeEventId, proxyAdapter->GetHandle(), ::mdc::mcu::McuCanNetWorkServiceInterface::ServiceIdentifier),
          CanNetMgrCtrl(proxyAdapter->GetProxy(), methods::CanNetMgrCtrlId),
          GetWorkMode(proxyAdapter->GetProxy(), methods::GetWorkModeId),
          NotifySystemAction(proxyAdapter->GetProxy(), methods::NotifySystemActionId),
          RequestWorkMode(proxyAdapter->GetProxy(), methods::RequestWorkModeId),
          SetMcuSystemStatus(proxyAdapter->GetProxy(), methods::SetMcuSystemStatusId),
          SetWorkMode(proxyAdapter->GetProxy(), methods::SetWorkModeId){
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        const vrtf::vcc::api::types::HandleType &handle)
    {
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> preProxyAdapter =
            std::make_unique<ara::com::internal::proxy::ProxyAdapter>(
               ::mdc::mcu::McuCanNetWorkServiceInterface::ServiceIdentifier, handle);
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            methods::CanNetMgrCtrl CanNetMgrCtrl(preProxyAdapter->GetProxy(), methods::CanNetMgrCtrlId);
            initResult = preProxyAdapter->InitializeMethod<methods::CanNetMgrCtrl::Output>(methods::CanNetMgrCtrlId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetWorkMode GetWorkMode(preProxyAdapter->GetProxy(), methods::GetWorkModeId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetWorkMode::Output>(methods::GetWorkModeId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::NotifySystemAction NotifySystemAction(preProxyAdapter->GetProxy(), methods::NotifySystemActionId);
            initResult = preProxyAdapter->InitializeMethod<methods::NotifySystemAction::Output>(methods::NotifySystemActionId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::RequestWorkMode RequestWorkMode(preProxyAdapter->GetProxy(), methods::RequestWorkModeId);
            initResult = preProxyAdapter->InitializeMethod<methods::RequestWorkMode::Output>(methods::RequestWorkModeId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetMcuSystemStatus SetMcuSystemStatus(preProxyAdapter->GetProxy(), methods::SetMcuSystemStatusId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetMcuSystemStatus::Output>(methods::SetMcuSystemStatusId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::SetWorkMode SetWorkMode(preProxyAdapter->GetProxy(), methods::SetWorkModeId);
            initResult = preProxyAdapter->InitializeMethod<methods::SetWorkMode::Output>(methods::SetWorkModeId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preProxyAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preProxyAdapter));
            ara::core::Result<ConstructionToken> result(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            result.EmplaceError(errorcode);
            return result;
        }
    }


    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::mcu::McuCanNetWorkServiceInterface::ServiceIdentifier, instance);
    }

    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::mcu::McuCanNetWorkServiceInterface::ServiceIdentifier, specifier);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::mcu::McuCanNetWorkServiceInterface::ServiceIdentifier, instance);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::mcu::McuCanNetWorkServiceInterface::ServiceIdentifier, specifier);
    }

    static void StopFindService(const ara::com::FindServiceHandle& handle)
    {
        ara::com::internal::proxy::ProxyAdapter::StopFindService(handle);
    }

    HandleType GetHandle() const
    {
        return proxyAdapter->GetHandle();
    }
    events::WorkModeEvent WorkModeEvent;
    methods::CanNetMgrCtrl CanNetMgrCtrl;
    methods::GetWorkMode GetWorkMode;
    methods::NotifySystemAction NotifySystemAction;
    methods::RequestWorkMode RequestWorkMode;
    methods::SetMcuSystemStatus SetMcuSystemStatus;
    methods::SetWorkMode SetWorkMode;
};
} // namespace proxy
} // namespace mcu
} // namespace mdc

#endif // MDC_MCU_MCUCANNETWORKSERVICEINTERFACE_PROXY_H
