/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_TSYNC_IMPL_TYPE_NODENAME_H
#define ARA_TSYNC_IMPL_TYPE_NODENAME_H

#include "impl_type_uint8.h"
namespace ara {
namespace tsync {
enum class NodeName : UInt8
{
    DP_PRIMARY = 0,
    SD_PRIMARY = 1,
    MCU_PRIMARY = 2,
    DP_SECONDARY = 3,
    SD_SECONDARY = 4,
    MCU_SECONDARY = 5
};
} // namespace tsync
} // namespace ara


#endif // ARA_TSYNC_IMPL_TYPE_NODENAME_H
