/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_TSYNC_IMPL_TYPE_NODEUNSYNCTIMES_H
#define ARA_TSYNC_IMPL_TYPE_NODEUNSYNCTIMES_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint32_t.h"
#include "ara/tsync/impl_type_subinfostate.h"

namespace ara {
namespace tsync {
struct NodeUnsyncTimes {
    ::uint32_t unsyncTimes;
    ::ara::tsync::SubInfoState subInfoState;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(unsyncTimes);
        fun(subInfoState);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(unsyncTimes);
        fun(subInfoState);
    }

    bool operator == (const ::ara::tsync::NodeUnsyncTimes& t) const
    {
        return (unsyncTimes == t.unsyncTimes) && (subInfoState == t.subInfoState);
    }
};
} // namespace tsync
} // namespace ara


#endif // ARA_TSYNC_IMPL_TYPE_NODEUNSYNCTIMES_H
