/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_TSYNC_IMPL_TYPE_NODETIMESYNCSTATE_H
#define ARA_TSYNC_IMPL_TYPE_NODETIMESYNCSTATE_H
#include <cfloat>
#include <cmath>
#include "ara/tsync/impl_type_timesyncstate.h"
#include "ara/tsync/impl_type_subinfostate.h"

namespace ara {
namespace tsync {
struct NodeTimeSyncState {
    ::ara::tsync::TimeSyncState timeSyncState;
    ::ara::tsync::SubInfoState subInfoState;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(timeSyncState);
        fun(subInfoState);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(timeSyncState);
        fun(subInfoState);
    }

    bool operator == (const ::ara::tsync::NodeTimeSyncState& t) const
    {
        return (timeSyncState == t.timeSyncState) && (subInfoState == t.subInfoState);
    }
};
} // namespace tsync
} // namespace ara


#endif // ARA_TSYNC_IMPL_TYPE_NODETIMESYNCSTATE_H
