/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_DIAG_DIAGCOMCLIENT_SKELETON_H
#define ARA_DIAG_DIAGCOMCLIENT_SKELETON_H

#include "ara/com/internal/skeleton/skeleton_adapter.h"
#include "ara/com/internal/skeleton/event_adapter.h"
#include "ara/com/internal/skeleton/field_adapter.h"
#include "ara/com/internal/skeleton/method_adapter.h"
#include "ara/diag/diagcomclient_common.h"
#include <cstdint>
#include <cfloat>
#include <cmath>

namespace ara {
namespace diag {
namespace skeleton {
namespace events
{
    using RequestTrigger = ara::com::internal::skeleton::event::EventAdapter<::ara::diag::RequestTriggerType>;
    static constexpr ara::com::internal::EntityId RequestTriggerId = 52019; //RequestTrigger_event_hash
}

namespace methods
{
    using GetRequestHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using SendResponseHandle = ara::com::internal::skeleton::method::MethodAdapter;
    static constexpr ara::com::internal::EntityId GetRequestId = 62768; //GetRequest_method_hash
    static constexpr ara::com::internal::EntityId SendResponseId = 17402; //SendResponse_method_hash
}

namespace fields
{
}

class DiagComClientSkeleton {
private:
    std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeletonAdapter;
    void ConstructSkeleton(ara::com::MethodCallProcessingMode mode)
    {
        if (mode == ara::com::MethodCallProcessingMode::kEvent) {
            if (!(skeletonAdapter->SetMethodThreadNumber(skeletonAdapter->GetMethodThreadNumber(2), 1024))) {
#ifndef NOT_SUPPORT_EXCEPTIONS
                ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                throw ara::com::ComException(std::move(errorcode));
#else
                std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
            }
        }
        ara::core::Result<void> resultRequestTrigger = skeletonAdapter->InitializeEvent(RequestTrigger);
        ThrowError(resultRequestTrigger);
        ara::core::Result<void> resultGetRequest = skeletonAdapter->InitializeMethod<ara::core::Future<GetRequestOutput>>(methods::GetRequestId);
        ThrowError(resultGetRequest);
        ara::core::Result<void> resultSendResponse = skeletonAdapter->InitializeMethod<ara::core::Future<SendResponseOutput>>(methods::SendResponseId);
        ThrowError(resultSendResponse);
    }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }
public:
    
    struct GetRequestOutput {
        ::Boolean isResponsePositive;
        ::ara::diag::ByteArray responseData;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(isResponsePositive);
            fun(responseData);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(isResponsePositive);
            fun(responseData);
        }
    
        bool operator == (const GetRequestOutput& t) const
        {
            return (isResponsePositive == t.isResponsePositive) && (responseData == t.responseData);
        }
    };
    
    
    using SendResponseOutput = void;
    
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeleton)
            : ptr(std::move(skeleton)) {}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> GetSkeletonAdapter() 
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> ptr;
    };
    explicit DiagComClientSkeleton(ara::com::InstanceIdentifier instanceId,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        : skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::ara::diag::DiagComClient::ServiceIdentifier, instanceId, mode)),
          RequestTrigger(skeletonAdapter->GetSkeleton(), events::RequestTriggerId),
          GetRequestHandle(skeletonAdapter->GetSkeleton(), methods::GetRequestId),
          SendResponseHandle(skeletonAdapter->GetSkeleton(), methods::SendResponseId){
        ConstructSkeleton(mode);
    }

    explicit DiagComClientSkeleton(ara::core::InstanceSpecifier instanceSpec,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::ara::diag::DiagComClient::ServiceIdentifier, instanceSpec, mode)),
          RequestTrigger(skeletonAdapter->GetSkeleton(), events::RequestTriggerId),
          GetRequestHandle(skeletonAdapter->GetSkeleton(), methods::GetRequestId),
          SendResponseHandle(skeletonAdapter->GetSkeleton(), methods::SendResponseId){
        ConstructSkeleton(mode);
    }

    explicit DiagComClientSkeleton(ara::com::InstanceIdentifierContainer instanceContainer,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::ara::diag::DiagComClient::ServiceIdentifier, instanceContainer, mode)),
          RequestTrigger(skeletonAdapter->GetSkeleton(), events::RequestTriggerId),
          GetRequestHandle(skeletonAdapter->GetSkeleton(), methods::GetRequestId),
          SendResponseHandle(skeletonAdapter->GetSkeleton(), methods::SendResponseId){
        ConstructSkeleton(mode);
    }

    DiagComClientSkeleton(const DiagComClientSkeleton&) = delete;
    DiagComClientSkeleton& operator=(const DiagComClientSkeleton&) = delete;

    DiagComClientSkeleton(DiagComClientSkeleton&& other) = default;
    DiagComClientSkeleton& operator=(DiagComClientSkeleton&& other) = default;
    DiagComClientSkeleton(ConstructionToken&& token) noexcept 
        : skeletonAdapter(token.GetSkeletonAdapter()),
          RequestTrigger(skeletonAdapter->GetSkeleton(), events::RequestTriggerId),
          GetRequestHandle(skeletonAdapter->GetSkeleton(), methods::GetRequestId),
          SendResponseHandle(skeletonAdapter->GetSkeleton(), methods::SendResponseId){
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifier instanceId,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::ara::diag::DiagComClient::ServiceIdentifier, instanceId, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::core::InstanceSpecifier instanceSpec,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::ara::diag::DiagComClient::ServiceIdentifier, instanceSpec, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifierContainer instanceIdContainer,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::ara::diag::DiagComClient::ServiceIdentifier, instanceIdContainer, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> PreConstructResult(
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter>& preSkeletonAdapter, ara::com::MethodCallProcessingMode mode)
    {
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            if (mode == ara::com::MethodCallProcessingMode::kEvent) {
                if(!preSkeletonAdapter->SetMethodThreadNumber(preSkeletonAdapter->GetMethodThreadNumber(2), 1024)) {
                    result = false;
                    ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                    initResult.EmplaceError(errorcode);
                    break;
                }
            }
            events::RequestTrigger RequestTrigger(preSkeletonAdapter->GetSkeleton(), events::RequestTriggerId);
            initResult = preSkeletonAdapter->InitializeEvent(RequestTrigger);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetRequestOutput>>(methods::GetRequestId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<SendResponseOutput>>(methods::SendResponseId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preSkeletonAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preSkeletonAdapter));
            ara::core::Result<ConstructionToken> preResult(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            preResult.EmplaceError(errorcode);
            return preResult;
        }
    }

    virtual ~DiagComClientSkeleton()
    {
        StopOfferService();
    }

    void OfferService()
    {
        skeletonAdapter->RegisterMethod(&DiagComClientSkeleton::GetRequest, *this, methods::GetRequestId);
        skeletonAdapter->RegisterMethod(&DiagComClientSkeleton::SendResponse, *this, methods::SendResponseId);
        skeletonAdapter->OfferService();
    }
    void StopOfferService()
    {
        skeletonAdapter->StopOfferService();
    }
    ara::core::Future<bool> ProcessNextMethodCall()
    {
        return skeletonAdapter->ProcessNextMethodCall();
    }
    bool SetMethodThreadNumber(const std::uint16_t& number, const std::uint16_t& queueSize)
    {
        return skeletonAdapter->SetMethodThreadNumber(number, queueSize);
    }
    virtual ara::core::Future<GetRequestOutput> GetRequest(const ::String& spec, const ::UInt64& serialNumber) = 0;
    virtual ara::core::Future<SendResponseOutput> SendResponse(const ::String& spec, const ::UInt64& serialNumber, const ::Boolean& isPositive, const ::ara::diag::ByteVector& responseData) = 0;

    events::RequestTrigger RequestTrigger;
    methods::GetRequestHandle GetRequestHandle;
    methods::SendResponseHandle SendResponseHandle;
};
} // namespace skeleton
} // namespace diag
} // namespace ara

#endif // ARA_DIAG_DIAGCOMCLIENT_SKELETON_H
