/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_ACTCOMPENSATION_IMPL_TYPE_VEHICLEMOTION_H
#define ARA_ACTCOMPENSATION_IMPL_TYPE_VEHICLEMOTION_H
#include <cfloat>
#include <cmath>
#include "ara/actcompensation/impl_type_float32withvalid.h"

namespace ara {
namespace actcompensation {
struct VehicleMotion {
    ::ara::actcompensation::Float32WithValid vx;
    ::ara::actcompensation::Float32WithValid vy;
    ::ara::actcompensation::Float32WithValid vz;
    ::ara::actcompensation::Float32WithValid ax;
    ::ara::actcompensation::Float32WithValid ay;
    ::ara::actcompensation::Float32WithValid az;
    ::ara::actcompensation::Float32WithValid yaw;
    ::ara::actcompensation::Float32WithValid pitch;
    ::ara::actcompensation::Float32WithValid roll;
    ::ara::actcompensation::Float32WithValid yawRate;
    ::ara::actcompensation::Float32WithValid pitchRate;
    ::ara::actcompensation::Float32WithValid rollRate;
    ::ara::actcompensation::Float32WithValid yawAcceleration;
    ::ara::actcompensation::Float32WithValid pitchAcceleration;
    ::ara::actcompensation::Float32WithValid rollAcceleration;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(vx);
        fun(vy);
        fun(vz);
        fun(ax);
        fun(ay);
        fun(az);
        fun(yaw);
        fun(pitch);
        fun(roll);
        fun(yawRate);
        fun(pitchRate);
        fun(rollRate);
        fun(yawAcceleration);
        fun(pitchAcceleration);
        fun(rollAcceleration);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(vx);
        fun(vy);
        fun(vz);
        fun(ax);
        fun(ay);
        fun(az);
        fun(yaw);
        fun(pitch);
        fun(roll);
        fun(yawRate);
        fun(pitchRate);
        fun(rollRate);
        fun(yawAcceleration);
        fun(pitchAcceleration);
        fun(rollAcceleration);
    }

    bool operator == (const ::ara::actcompensation::VehicleMotion& t) const
    {
        return (vx == t.vx) && (vy == t.vy) && (vz == t.vz) && (ax == t.ax) && (ay == t.ay) && (az == t.az) && (yaw == t.yaw) && (pitch == t.pitch) && (roll == t.roll) && (yawRate == t.yawRate) && (pitchRate == t.pitchRate) && (rollRate == t.rollRate) && (yawAcceleration == t.yawAcceleration) && (pitchAcceleration == t.pitchAcceleration) && (rollAcceleration == t.rollAcceleration);
    }
};
} // namespace actcompensation
} // namespace ara


#endif // ARA_ACTCOMPENSATION_IMPL_TYPE_VEHICLEMOTION_H
