/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_MDCCAN_IMPL_TYPE_SYSTEMTIME_H
#define MDC_MDCCAN_IMPL_TYPE_SYSTEMTIME_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint32.h"

namespace mdc {
namespace mdccan {
struct Systemtime {
    ::UInt32 second;
    ::UInt32 nsecond;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(second);
        fun(nsecond);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(second);
        fun(nsecond);
    }

    bool operator == (const ::mdc::mdccan::Systemtime& t) const
    {
        return (second == t.second) && (nsecond == t.nsecond);
    }
};
} // namespace mdccan
} // namespace mdc


#endif // MDC_MDCCAN_IMPL_TYPE_SYSTEMTIME_H
