/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_MDCCAN_IMPL_TYPE_CANDATA_H
#define MDC_MDCCAN_IMPL_TYPE_CANDATA_H
#include "ara/core/vector.h"
#include "impl_type_uint8.h"

namespace mdc {
namespace mdccan {
using CanData = ara::core::Vector<UInt8>;
} // namespace mdccan
} // namespace mdc


#endif // MDC_MDCCAN_IMPL_TYPE_CANDATA_H
