/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SSM_IMPL_TYPE_GEARINFO_H
#define MDC_SSM_IMPL_TYPE_GEARINFO_H
#include <cfloat>
#include <cmath>
#include "mdc/ssm/impl_type_gear.h"
#include "impl_type_uint8.h"
#include "mdc/ssm/impl_type_uint8withvalid.h"
#include "impl_type_int32.h"

namespace mdc {
namespace ssm {
struct GearInfo {
    ::mdc::ssm::Gear gear;
    ::mdc::ssm::Gear gearLever;
    ::UInt8 gearShiftStatus;
    ::mdc::ssm::Uint8WithValid driverOverride;
    ::Int32 faultCode;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(gear);
        fun(gearLever);
        fun(gearShiftStatus);
        fun(driverOverride);
        fun(faultCode);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(gear);
        fun(gearLever);
        fun(gearShiftStatus);
        fun(driverOverride);
        fun(faultCode);
    }

    bool operator == (const ::mdc::ssm::GearInfo& t) const
    {
        return (gear == t.gear) && (gearLever == t.gearLever) && (gearShiftStatus == t.gearShiftStatus) && (driverOverride == t.driverOverride) && (faultCode == t.faultCode);
    }
};
} // namespace ssm
} // namespace mdc


#endif // MDC_SSM_IMPL_TYPE_GEARINFO_H
