/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SSM_IMPL_TYPE_UINT8WITHVALID_H
#define MDC_SSM_IMPL_TYPE_UINT8WITHVALID_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"

namespace mdc {
namespace ssm {
struct Uint8WithValid {
    ::UInt8 value;
    ::UInt8 confidence;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(value);
        fun(confidence);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(value);
        fun(confidence);
    }

    bool operator == (const ::mdc::ssm::Uint8WithValid& t) const
    {
        return (value == t.value) && (confidence == t.confidence);
    }
};
} // namespace ssm
} // namespace mdc


#endif // MDC_SSM_IMPL_TYPE_UINT8WITHVALID_H
