/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SSM_IMPL_TYPE_LIGHTSWITCH_H
#define MDC_SSM_IMPL_TYPE_LIGHTSWITCH_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"

namespace mdc {
namespace ssm {
struct LightSwitch {
    ::UInt8 turnLightSwitch;
    ::UInt8 hazardLightSwicth;
    ::UInt8 positionLightSwitch;
    ::UInt8 daytimeRunningLightSwitch;
    ::UInt8 highLowBeamSwitch;
    ::UInt8 fogFrontSwitch;
    ::UInt8 fogRearSwitch;
    ::UInt8 hornSwitch;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(turnLightSwitch);
        fun(hazardLightSwicth);
        fun(positionLightSwitch);
        fun(daytimeRunningLightSwitch);
        fun(highLowBeamSwitch);
        fun(fogFrontSwitch);
        fun(fogRearSwitch);
        fun(hornSwitch);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(turnLightSwitch);
        fun(hazardLightSwicth);
        fun(positionLightSwitch);
        fun(daytimeRunningLightSwitch);
        fun(highLowBeamSwitch);
        fun(fogFrontSwitch);
        fun(fogRearSwitch);
        fun(hornSwitch);
    }

    bool operator == (const ::mdc::ssm::LightSwitch& t) const
    {
        return (turnLightSwitch == t.turnLightSwitch) && (hazardLightSwicth == t.hazardLightSwicth) && (positionLightSwitch == t.positionLightSwitch) && (daytimeRunningLightSwitch == t.daytimeRunningLightSwitch) && (highLowBeamSwitch == t.highLowBeamSwitch) && (fogFrontSwitch == t.fogFrontSwitch) && (fogRearSwitch == t.fogRearSwitch) && (hornSwitch == t.hornSwitch);
    }
};
} // namespace ssm
} // namespace mdc


#endif // MDC_SSM_IMPL_TYPE_LIGHTSWITCH_H
