/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SSM_IMPL_TYPE_ACTUATORSTATUS_H
#define MDC_SSM_IMPL_TYPE_ACTUATORSTATUS_H
#include <cfloat>
#include <cmath>
#include "mdc/ssm/impl_type_actuatorworkstatus.h"

namespace mdc {
namespace ssm {
struct ActuatorStatus {
    ::mdc::ssm::ActuatorWorkStatus angleSteer;
    ::mdc::ssm::ActuatorWorkStatus torqueSteer;
    ::mdc::ssm::ActuatorWorkStatus emergencyAngleSteer;
    ::mdc::ssm::ActuatorWorkStatus emergencyTorqueSteer;
    ::mdc::ssm::ActuatorWorkStatus steerVibrate;
    ::mdc::ssm::ActuatorWorkStatus accelerate;
    ::mdc::ssm::ActuatorWorkStatus decelerate;
    ::mdc::ssm::ActuatorWorkStatus emergencyDecelerate;
    ::mdc::ssm::ActuatorWorkStatus drive;
    ::mdc::ssm::ActuatorWorkStatus brake;
    ::mdc::ssm::ActuatorWorkStatus vlc;
    ::mdc::ssm::ActuatorWorkStatus emergencyStop;
    ::mdc::ssm::ActuatorWorkStatus stop;
    ::mdc::ssm::ActuatorWorkStatus park;
    ::mdc::ssm::ActuatorWorkStatus gear;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(angleSteer);
        fun(torqueSteer);
        fun(emergencyAngleSteer);
        fun(emergencyTorqueSteer);
        fun(steerVibrate);
        fun(accelerate);
        fun(decelerate);
        fun(emergencyDecelerate);
        fun(drive);
        fun(brake);
        fun(vlc);
        fun(emergencyStop);
        fun(stop);
        fun(park);
        fun(gear);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(angleSteer);
        fun(torqueSteer);
        fun(emergencyAngleSteer);
        fun(emergencyTorqueSteer);
        fun(steerVibrate);
        fun(accelerate);
        fun(decelerate);
        fun(emergencyDecelerate);
        fun(drive);
        fun(brake);
        fun(vlc);
        fun(emergencyStop);
        fun(stop);
        fun(park);
        fun(gear);
    }

    bool operator == (const ::mdc::ssm::ActuatorStatus& t) const
    {
        return (angleSteer == t.angleSteer) && (torqueSteer == t.torqueSteer) && (emergencyAngleSteer == t.emergencyAngleSteer) && (emergencyTorqueSteer == t.emergencyTorqueSteer) && (steerVibrate == t.steerVibrate) && (accelerate == t.accelerate) && (decelerate == t.decelerate) && (emergencyDecelerate == t.emergencyDecelerate) && (drive == t.drive) && (brake == t.brake) && (vlc == t.vlc) && (emergencyStop == t.emergencyStop) && (stop == t.stop) && (park == t.park) && (gear == t.gear);
    }
};
} // namespace ssm
} // namespace mdc


#endif // MDC_SSM_IMPL_TYPE_ACTUATORSTATUS_H
