/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SSM_IMPL_TYPE_DOORSTATUS_H
#define MDC_SSM_IMPL_TYPE_DOORSTATUS_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"

namespace mdc {
namespace ssm {
struct DoorStatus {
    ::UInt8 doorFlStatus;
    ::UInt8 doorFrStatus;
    ::UInt8 doorRlStatus;
    ::UInt8 doorRrStatus;
    ::UInt8 doorHoodStatus;
    ::UInt8 doorTrunkStatus;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(doorFlStatus);
        fun(doorFrStatus);
        fun(doorRlStatus);
        fun(doorRrStatus);
        fun(doorHoodStatus);
        fun(doorTrunkStatus);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(doorFlStatus);
        fun(doorFrStatus);
        fun(doorRlStatus);
        fun(doorRrStatus);
        fun(doorHoodStatus);
        fun(doorTrunkStatus);
    }

    bool operator == (const ::mdc::ssm::DoorStatus& t) const
    {
        return (doorFlStatus == t.doorFlStatus) && (doorFrStatus == t.doorFrStatus) && (doorRlStatus == t.doorRlStatus) && (doorRrStatus == t.doorRrStatus) && (doorHoodStatus == t.doorHoodStatus) && (doorTrunkStatus == t.doorTrunkStatus);
    }
};
} // namespace ssm
} // namespace mdc


#endif // MDC_SSM_IMPL_TYPE_DOORSTATUS_H
