/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SSM_IMPL_TYPE_ACTUATORWORKSTATUS_H
#define MDC_SSM_IMPL_TYPE_ACTUATORWORKSTATUS_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"

namespace mdc {
namespace ssm {
struct ActuatorWorkStatus {
    ::UInt8 capability;
    ::UInt8 response;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(capability);
        fun(response);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(capability);
        fun(response);
    }

    bool operator == (const ::mdc::ssm::ActuatorWorkStatus& t) const
    {
        return (capability == t.capability) && (response == t.response);
    }
};
} // namespace ssm
} // namespace mdc


#endif // MDC_SSM_IMPL_TYPE_ACTUATORWORKSTATUS_H
