/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SSM_IMPL_TYPE_PADSWITCH_H
#define MDC_SSM_IMPL_TYPE_PADSWITCH_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"

namespace mdc {
namespace ssm {
struct PadSwitch {
    ::UInt8 up;
    ::UInt8 down;
    ::UInt8 left;
    ::UInt8 right;
    ::UInt8 ok;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(up);
        fun(down);
        fun(left);
        fun(right);
        fun(ok);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(up);
        fun(down);
        fun(left);
        fun(right);
        fun(ok);
    }

    bool operator == (const ::mdc::ssm::PadSwitch& t) const
    {
        return (up == t.up) && (down == t.down) && (left == t.left) && (right == t.right) && (ok == t.ok);
    }
};
} // namespace ssm
} // namespace mdc


#endif // MDC_SSM_IMPL_TYPE_PADSWITCH_H
