/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SSM_IMPL_TYPE_TYRESTATUS_H
#define MDC_SSM_IMPL_TYPE_TYRESTATUS_H
#include <cfloat>
#include <cmath>
#include "impl_type_float.h"
#include "mdc/ssm/impl_type_uint8withvalid.h"

namespace mdc {
namespace ssm {
struct TyreStatus {
    ::Float tyrePressureValue;
    ::mdc::ssm::Uint8WithValid tyrePressureLeakageStatus;
    ::mdc::ssm::Uint8WithValid tyrePressureTirePStatus;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(tyrePressureValue);
        fun(tyrePressureLeakageStatus);
        fun(tyrePressureTirePStatus);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(tyrePressureValue);
        fun(tyrePressureLeakageStatus);
        fun(tyrePressureTirePStatus);
    }

    bool operator == (const ::mdc::ssm::TyreStatus& t) const
    {
        return (fabs(tyrePressureValue - t.tyrePressureValue) < FLT_EPSILON) && (tyrePressureLeakageStatus == t.tyrePressureLeakageStatus) && (tyrePressureTirePStatus == t.tyrePressureTirePStatus);
    }
};
} // namespace ssm
} // namespace mdc


#endif // MDC_SSM_IMPL_TYPE_TYRESTATUS_H
