/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SSM_IMPL_TYPE_WINDOWSTATUS_H
#define MDC_SSM_IMPL_TYPE_WINDOWSTATUS_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint8.h"

namespace mdc {
namespace ssm {
struct WindowStatus {
    ::UInt8 windowFlStatus;
    ::UInt8 windowFrStatus;
    ::UInt8 windowRlStatus;
    ::UInt8 windowRrStatus;
    ::UInt8 windowTopStatus;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(windowFlStatus);
        fun(windowFrStatus);
        fun(windowRlStatus);
        fun(windowRrStatus);
        fun(windowTopStatus);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(windowFlStatus);
        fun(windowFrStatus);
        fun(windowRlStatus);
        fun(windowRrStatus);
        fun(windowTopStatus);
    }

    bool operator == (const ::mdc::ssm::WindowStatus& t) const
    {
        return (windowFlStatus == t.windowFlStatus) && (windowFrStatus == t.windowFrStatus) && (windowRlStatus == t.windowRlStatus) && (windowRrStatus == t.windowRrStatus) && (windowTopStatus == t.windowTopStatus);
    }
};
} // namespace ssm
} // namespace mdc


#endif // MDC_SSM_IMPL_TYPE_WINDOWSTATUS_H
