/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SSM_VEHICLEINFOBODYSERVICEINTERFACE_SKELETON_H
#define MDC_SSM_VEHICLEINFOBODYSERVICEINTERFACE_SKELETON_H

#include "ara/com/internal/skeleton/skeleton_adapter.h"
#include "ara/com/internal/skeleton/event_adapter.h"
#include "ara/com/internal/skeleton/field_adapter.h"
#include "ara/com/internal/skeleton/method_adapter.h"
#include "mdc/ssm/vehicleinfobodyserviceinterface_common.h"
#include <cstdint>
#include <cfloat>
#include <cmath>

namespace mdc {
namespace ssm {
namespace skeleton {
namespace events
{
    using bodyInfoEvt = ara::com::internal::skeleton::event::EventAdapter<::mdc::ssm::VehicleBodyInfo>;
    static constexpr ara::com::internal::EntityId bodyInfoEvtId = 36451; //bodyInfoEvt_event_hash
}

namespace methods
{
}

namespace fields
{
    using commonStatus = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::CommonStatus>;
    using doorStatus = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::DoorStatus>;
    using doorSwitch = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::DoorSwitch>;
    using lightStatus = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::LightStatus>;
    using lightSwitch = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::LightSwitch>;
    using mirrorSwitch = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::MirrorSwitch>;
    using modeSwitch = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::ModeSwitch>;
    using padSwitch = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::PadSwitch>;
    using pepsSwitch = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::PepsSwitch>;
    using safetyStatus = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::SafetyStatus>;
    using tyreFlStatus = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::TyreStatus>;
    using tyreFrStatus = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::TyreStatus>;
    using tyreRlStatus = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::TyreStatus>;
    using tyreRrStatus = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::TyreStatus>;
    using windowStatus = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::WindowStatus>;
    using wiperFrontStatus = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::Wiper>;
    using wiperFrontSwitch = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::Wiper>;
    using wiperRearStatus = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::Wiper>;
    using wiperRearSwitch = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::Wiper>;
    using bodyInfo = ara::com::internal::skeleton::field::FieldAdapter<::mdc::ssm::VehicleBodyInfo>;
    static constexpr ara::com::internal::EntityId commonStatusId = 47768; //commonStatus_field_hash
    static constexpr ara::com::internal::EntityId commonStatusGetterId = 12448; //commonStatus_getter_hash
    static constexpr ara::com::internal::EntityId doorStatusId = 65406; //doorStatus_field_hash
    static constexpr ara::com::internal::EntityId doorStatusGetterId = 38324; //doorStatus_getter_hash
    static constexpr ara::com::internal::EntityId doorSwitchId = 2472; //doorSwitch_field_hash
    static constexpr ara::com::internal::EntityId doorSwitchGetterId = 1736; //doorSwitch_getter_hash
    static constexpr ara::com::internal::EntityId lightStatusId = 14583; //lightStatus_field_hash
    static constexpr ara::com::internal::EntityId lightStatusGetterId = 48951; //lightStatus_getter_hash
    static constexpr ara::com::internal::EntityId lightSwitchId = 46858; //lightSwitch_field_hash
    static constexpr ara::com::internal::EntityId lightSwitchGetterId = 37564; //lightSwitch_getter_hash
    static constexpr ara::com::internal::EntityId mirrorSwitchId = 36329; //mirrorSwitch_field_hash
    static constexpr ara::com::internal::EntityId mirrorSwitchGetterId = 6604; //mirrorSwitch_getter_hash
    static constexpr ara::com::internal::EntityId modeSwitchId = 29186; //modeSwitch_field_hash
    static constexpr ara::com::internal::EntityId modeSwitchGetterId = 23389; //modeSwitch_getter_hash
    static constexpr ara::com::internal::EntityId padSwitchId = 3386; //padSwitch_field_hash
    static constexpr ara::com::internal::EntityId padSwitchGetterId = 55605; //padSwitch_getter_hash
    static constexpr ara::com::internal::EntityId pepsSwitchId = 41531; //pepsSwitch_field_hash
    static constexpr ara::com::internal::EntityId pepsSwitchGetterId = 56006; //pepsSwitch_getter_hash
    static constexpr ara::com::internal::EntityId safetyStatusId = 38163; //safetyStatus_field_hash
    static constexpr ara::com::internal::EntityId safetyStatusGetterId = 51590; //safetyStatus_getter_hash
    static constexpr ara::com::internal::EntityId tyreFlStatusId = 17000; //tyreFlStatus_field_hash
    static constexpr ara::com::internal::EntityId tyreFlStatusGetterId = 50791; //tyreFlStatus_getter_hash
    static constexpr ara::com::internal::EntityId tyreFrStatusId = 34653; //tyreFrStatus_field_hash
    static constexpr ara::com::internal::EntityId tyreFrStatusGetterId = 42706; //tyreFrStatus_getter_hash
    static constexpr ara::com::internal::EntityId tyreRlStatusId = 18609; //tyreRlStatus_field_hash
    static constexpr ara::com::internal::EntityId tyreRlStatusGetterId = 10239; //tyreRlStatus_getter_hash
    static constexpr ara::com::internal::EntityId tyreRrStatusId = 60431; //tyreRrStatus_field_hash
    static constexpr ara::com::internal::EntityId tyreRrStatusGetterId = 45913; //tyreRrStatus_getter_hash
    static constexpr ara::com::internal::EntityId windowStatusId = 42621; //windowStatus_field_hash
    static constexpr ara::com::internal::EntityId windowStatusGetterId = 4857; //windowStatus_getter_hash
    static constexpr ara::com::internal::EntityId wiperFrontStatusId = 39743; //wiperFrontStatus_field_hash
    static constexpr ara::com::internal::EntityId wiperFrontStatusGetterId = 27840; //wiperFrontStatus_getter_hash
    static constexpr ara::com::internal::EntityId wiperFrontSwitchId = 9696; //wiperFrontSwitch_field_hash
    static constexpr ara::com::internal::EntityId wiperFrontSwitchGetterId = 53535; //wiperFrontSwitch_getter_hash
    static constexpr ara::com::internal::EntityId wiperRearStatusId = 11709; //wiperRearStatus_field_hash
    static constexpr ara::com::internal::EntityId wiperRearStatusGetterId = 17923; //wiperRearStatus_getter_hash
    static constexpr ara::com::internal::EntityId wiperRearSwitchId = 53260; //wiperRearSwitch_field_hash
    static constexpr ara::com::internal::EntityId wiperRearSwitchGetterId = 4046; //wiperRearSwitch_getter_hash
    static constexpr ara::com::internal::EntityId bodyInfoId = 2186; //bodyInfo_field_hash
    static constexpr ara::com::internal::EntityId bodyInfoGetterId = 11171; //bodyInfo_getter_hash
}

class VehicleInfoBodyServiceInterfaceSkeleton {
private:
    std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeletonAdapter;
    void ConstructSkeleton(ara::com::MethodCallProcessingMode mode)
    {
        if (mode == ara::com::MethodCallProcessingMode::kEvent) {
            if (!(skeletonAdapter->SetMethodThreadNumber(skeletonAdapter->GetMethodThreadNumber(20), 1024))) {
#ifndef NOT_SUPPORT_EXCEPTIONS
                ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                throw ara::com::ComException(std::move(errorcode));
#else
                std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
            }
        }
        ara::core::Result<void> resultbodyInfoEvt = skeletonAdapter->InitializeEvent(bodyInfoEvt);
        ThrowError(resultbodyInfoEvt);
        commonStatus.SetGetterEntityId(fields::commonStatusGetterId);
        ara::core::Result<void> resultcommonStatus = skeletonAdapter->InitializeField<::mdc::ssm::CommonStatus>(commonStatus);
        ThrowError(resultcommonStatus);
        doorStatus.SetGetterEntityId(fields::doorStatusGetterId);
        ara::core::Result<void> resultdoorStatus = skeletonAdapter->InitializeField<::mdc::ssm::DoorStatus>(doorStatus);
        ThrowError(resultdoorStatus);
        doorSwitch.SetGetterEntityId(fields::doorSwitchGetterId);
        ara::core::Result<void> resultdoorSwitch = skeletonAdapter->InitializeField<::mdc::ssm::DoorSwitch>(doorSwitch);
        ThrowError(resultdoorSwitch);
        lightStatus.SetGetterEntityId(fields::lightStatusGetterId);
        ara::core::Result<void> resultlightStatus = skeletonAdapter->InitializeField<::mdc::ssm::LightStatus>(lightStatus);
        ThrowError(resultlightStatus);
        lightSwitch.SetGetterEntityId(fields::lightSwitchGetterId);
        ara::core::Result<void> resultlightSwitch = skeletonAdapter->InitializeField<::mdc::ssm::LightSwitch>(lightSwitch);
        ThrowError(resultlightSwitch);
        mirrorSwitch.SetGetterEntityId(fields::mirrorSwitchGetterId);
        ara::core::Result<void> resultmirrorSwitch = skeletonAdapter->InitializeField<::mdc::ssm::MirrorSwitch>(mirrorSwitch);
        ThrowError(resultmirrorSwitch);
        modeSwitch.SetGetterEntityId(fields::modeSwitchGetterId);
        ara::core::Result<void> resultmodeSwitch = skeletonAdapter->InitializeField<::mdc::ssm::ModeSwitch>(modeSwitch);
        ThrowError(resultmodeSwitch);
        padSwitch.SetGetterEntityId(fields::padSwitchGetterId);
        ara::core::Result<void> resultpadSwitch = skeletonAdapter->InitializeField<::mdc::ssm::PadSwitch>(padSwitch);
        ThrowError(resultpadSwitch);
        pepsSwitch.SetGetterEntityId(fields::pepsSwitchGetterId);
        ara::core::Result<void> resultpepsSwitch = skeletonAdapter->InitializeField<::mdc::ssm::PepsSwitch>(pepsSwitch);
        ThrowError(resultpepsSwitch);
        safetyStatus.SetGetterEntityId(fields::safetyStatusGetterId);
        ara::core::Result<void> resultsafetyStatus = skeletonAdapter->InitializeField<::mdc::ssm::SafetyStatus>(safetyStatus);
        ThrowError(resultsafetyStatus);
        tyreFlStatus.SetGetterEntityId(fields::tyreFlStatusGetterId);
        ara::core::Result<void> resulttyreFlStatus = skeletonAdapter->InitializeField<::mdc::ssm::TyreStatus>(tyreFlStatus);
        ThrowError(resulttyreFlStatus);
        tyreFrStatus.SetGetterEntityId(fields::tyreFrStatusGetterId);
        ara::core::Result<void> resulttyreFrStatus = skeletonAdapter->InitializeField<::mdc::ssm::TyreStatus>(tyreFrStatus);
        ThrowError(resulttyreFrStatus);
        tyreRlStatus.SetGetterEntityId(fields::tyreRlStatusGetterId);
        ara::core::Result<void> resulttyreRlStatus = skeletonAdapter->InitializeField<::mdc::ssm::TyreStatus>(tyreRlStatus);
        ThrowError(resulttyreRlStatus);
        tyreRrStatus.SetGetterEntityId(fields::tyreRrStatusGetterId);
        ara::core::Result<void> resulttyreRrStatus = skeletonAdapter->InitializeField<::mdc::ssm::TyreStatus>(tyreRrStatus);
        ThrowError(resulttyreRrStatus);
        windowStatus.SetGetterEntityId(fields::windowStatusGetterId);
        ara::core::Result<void> resultwindowStatus = skeletonAdapter->InitializeField<::mdc::ssm::WindowStatus>(windowStatus);
        ThrowError(resultwindowStatus);
        wiperFrontStatus.SetGetterEntityId(fields::wiperFrontStatusGetterId);
        ara::core::Result<void> resultwiperFrontStatus = skeletonAdapter->InitializeField<::mdc::ssm::Wiper>(wiperFrontStatus);
        ThrowError(resultwiperFrontStatus);
        wiperFrontSwitch.SetGetterEntityId(fields::wiperFrontSwitchGetterId);
        ara::core::Result<void> resultwiperFrontSwitch = skeletonAdapter->InitializeField<::mdc::ssm::Wiper>(wiperFrontSwitch);
        ThrowError(resultwiperFrontSwitch);
        wiperRearStatus.SetGetterEntityId(fields::wiperRearStatusGetterId);
        ara::core::Result<void> resultwiperRearStatus = skeletonAdapter->InitializeField<::mdc::ssm::Wiper>(wiperRearStatus);
        ThrowError(resultwiperRearStatus);
        wiperRearSwitch.SetGetterEntityId(fields::wiperRearSwitchGetterId);
        ara::core::Result<void> resultwiperRearSwitch = skeletonAdapter->InitializeField<::mdc::ssm::Wiper>(wiperRearSwitch);
        ThrowError(resultwiperRearSwitch);
        bodyInfo.SetGetterEntityId(fields::bodyInfoGetterId);
        ara::core::Result<void> resultbodyInfo = skeletonAdapter->InitializeField<::mdc::ssm::VehicleBodyInfo>(bodyInfo);
        ThrowError(resultbodyInfo);
    }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }
public:
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeleton)
            : ptr(std::move(skeleton)) {}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> GetSkeletonAdapter() 
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> ptr;
        fields::commonStatus commonStatus;
        fields::doorStatus doorStatus;
        fields::doorSwitch doorSwitch;
        fields::lightStatus lightStatus;
        fields::lightSwitch lightSwitch;
        fields::mirrorSwitch mirrorSwitch;
        fields::modeSwitch modeSwitch;
        fields::padSwitch padSwitch;
        fields::pepsSwitch pepsSwitch;
        fields::safetyStatus safetyStatus;
        fields::tyreFlStatus tyreFlStatus;
        fields::tyreFrStatus tyreFrStatus;
        fields::tyreRlStatus tyreRlStatus;
        fields::tyreRrStatus tyreRrStatus;
        fields::windowStatus windowStatus;
        fields::wiperFrontStatus wiperFrontStatus;
        fields::wiperFrontSwitch wiperFrontSwitch;
        fields::wiperRearStatus wiperRearStatus;
        fields::wiperRearSwitch wiperRearSwitch;
        fields::bodyInfo bodyInfo;
    };
    explicit VehicleInfoBodyServiceInterfaceSkeleton(ara::com::InstanceIdentifier instanceId,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        : skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::ssm::VehicleInfoBodyServiceInterface::ServiceIdentifier, instanceId, mode)),
          bodyInfoEvt(skeletonAdapter->GetSkeleton(), events::bodyInfoEvtId),
          commonStatus(skeletonAdapter->GetSkeleton(), fields::commonStatusId),
          doorStatus(skeletonAdapter->GetSkeleton(), fields::doorStatusId),
          doorSwitch(skeletonAdapter->GetSkeleton(), fields::doorSwitchId),
          lightStatus(skeletonAdapter->GetSkeleton(), fields::lightStatusId),
          lightSwitch(skeletonAdapter->GetSkeleton(), fields::lightSwitchId),
          mirrorSwitch(skeletonAdapter->GetSkeleton(), fields::mirrorSwitchId),
          modeSwitch(skeletonAdapter->GetSkeleton(), fields::modeSwitchId),
          padSwitch(skeletonAdapter->GetSkeleton(), fields::padSwitchId),
          pepsSwitch(skeletonAdapter->GetSkeleton(), fields::pepsSwitchId),
          safetyStatus(skeletonAdapter->GetSkeleton(), fields::safetyStatusId),
          tyreFlStatus(skeletonAdapter->GetSkeleton(), fields::tyreFlStatusId),
          tyreFrStatus(skeletonAdapter->GetSkeleton(), fields::tyreFrStatusId),
          tyreRlStatus(skeletonAdapter->GetSkeleton(), fields::tyreRlStatusId),
          tyreRrStatus(skeletonAdapter->GetSkeleton(), fields::tyreRrStatusId),
          windowStatus(skeletonAdapter->GetSkeleton(), fields::windowStatusId),
          wiperFrontStatus(skeletonAdapter->GetSkeleton(), fields::wiperFrontStatusId),
          wiperFrontSwitch(skeletonAdapter->GetSkeleton(), fields::wiperFrontSwitchId),
          wiperRearStatus(skeletonAdapter->GetSkeleton(), fields::wiperRearStatusId),
          wiperRearSwitch(skeletonAdapter->GetSkeleton(), fields::wiperRearSwitchId),
          bodyInfo(skeletonAdapter->GetSkeleton(), fields::bodyInfoId) {
        ConstructSkeleton(mode);
    }

    explicit VehicleInfoBodyServiceInterfaceSkeleton(ara::core::InstanceSpecifier instanceSpec,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::ssm::VehicleInfoBodyServiceInterface::ServiceIdentifier, instanceSpec, mode)),
          bodyInfoEvt(skeletonAdapter->GetSkeleton(), events::bodyInfoEvtId),
          commonStatus(skeletonAdapter->GetSkeleton(), fields::commonStatusId),
          doorStatus(skeletonAdapter->GetSkeleton(), fields::doorStatusId),
          doorSwitch(skeletonAdapter->GetSkeleton(), fields::doorSwitchId),
          lightStatus(skeletonAdapter->GetSkeleton(), fields::lightStatusId),
          lightSwitch(skeletonAdapter->GetSkeleton(), fields::lightSwitchId),
          mirrorSwitch(skeletonAdapter->GetSkeleton(), fields::mirrorSwitchId),
          modeSwitch(skeletonAdapter->GetSkeleton(), fields::modeSwitchId),
          padSwitch(skeletonAdapter->GetSkeleton(), fields::padSwitchId),
          pepsSwitch(skeletonAdapter->GetSkeleton(), fields::pepsSwitchId),
          safetyStatus(skeletonAdapter->GetSkeleton(), fields::safetyStatusId),
          tyreFlStatus(skeletonAdapter->GetSkeleton(), fields::tyreFlStatusId),
          tyreFrStatus(skeletonAdapter->GetSkeleton(), fields::tyreFrStatusId),
          tyreRlStatus(skeletonAdapter->GetSkeleton(), fields::tyreRlStatusId),
          tyreRrStatus(skeletonAdapter->GetSkeleton(), fields::tyreRrStatusId),
          windowStatus(skeletonAdapter->GetSkeleton(), fields::windowStatusId),
          wiperFrontStatus(skeletonAdapter->GetSkeleton(), fields::wiperFrontStatusId),
          wiperFrontSwitch(skeletonAdapter->GetSkeleton(), fields::wiperFrontSwitchId),
          wiperRearStatus(skeletonAdapter->GetSkeleton(), fields::wiperRearStatusId),
          wiperRearSwitch(skeletonAdapter->GetSkeleton(), fields::wiperRearSwitchId),
          bodyInfo(skeletonAdapter->GetSkeleton(), fields::bodyInfoId) {
        ConstructSkeleton(mode);
    }

    explicit VehicleInfoBodyServiceInterfaceSkeleton(ara::com::InstanceIdentifierContainer instanceContainer,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::ssm::VehicleInfoBodyServiceInterface::ServiceIdentifier, instanceContainer, mode)),
          bodyInfoEvt(skeletonAdapter->GetSkeleton(), events::bodyInfoEvtId),
          commonStatus(skeletonAdapter->GetSkeleton(), fields::commonStatusId),
          doorStatus(skeletonAdapter->GetSkeleton(), fields::doorStatusId),
          doorSwitch(skeletonAdapter->GetSkeleton(), fields::doorSwitchId),
          lightStatus(skeletonAdapter->GetSkeleton(), fields::lightStatusId),
          lightSwitch(skeletonAdapter->GetSkeleton(), fields::lightSwitchId),
          mirrorSwitch(skeletonAdapter->GetSkeleton(), fields::mirrorSwitchId),
          modeSwitch(skeletonAdapter->GetSkeleton(), fields::modeSwitchId),
          padSwitch(skeletonAdapter->GetSkeleton(), fields::padSwitchId),
          pepsSwitch(skeletonAdapter->GetSkeleton(), fields::pepsSwitchId),
          safetyStatus(skeletonAdapter->GetSkeleton(), fields::safetyStatusId),
          tyreFlStatus(skeletonAdapter->GetSkeleton(), fields::tyreFlStatusId),
          tyreFrStatus(skeletonAdapter->GetSkeleton(), fields::tyreFrStatusId),
          tyreRlStatus(skeletonAdapter->GetSkeleton(), fields::tyreRlStatusId),
          tyreRrStatus(skeletonAdapter->GetSkeleton(), fields::tyreRrStatusId),
          windowStatus(skeletonAdapter->GetSkeleton(), fields::windowStatusId),
          wiperFrontStatus(skeletonAdapter->GetSkeleton(), fields::wiperFrontStatusId),
          wiperFrontSwitch(skeletonAdapter->GetSkeleton(), fields::wiperFrontSwitchId),
          wiperRearStatus(skeletonAdapter->GetSkeleton(), fields::wiperRearStatusId),
          wiperRearSwitch(skeletonAdapter->GetSkeleton(), fields::wiperRearSwitchId),
          bodyInfo(skeletonAdapter->GetSkeleton(), fields::bodyInfoId) {
        ConstructSkeleton(mode);
    }

    VehicleInfoBodyServiceInterfaceSkeleton(const VehicleInfoBodyServiceInterfaceSkeleton&) = delete;
    VehicleInfoBodyServiceInterfaceSkeleton& operator=(const VehicleInfoBodyServiceInterfaceSkeleton&) = delete;

    VehicleInfoBodyServiceInterfaceSkeleton(VehicleInfoBodyServiceInterfaceSkeleton&& other) = default;
    VehicleInfoBodyServiceInterfaceSkeleton& operator=(VehicleInfoBodyServiceInterfaceSkeleton&& other) = default;
    VehicleInfoBodyServiceInterfaceSkeleton(ConstructionToken&& token) noexcept 
        : skeletonAdapter(token.GetSkeletonAdapter()),
          bodyInfoEvt(skeletonAdapter->GetSkeleton(), events::bodyInfoEvtId),
          commonStatus(skeletonAdapter->GetSkeleton(), fields::commonStatusId),
          doorStatus(skeletonAdapter->GetSkeleton(), fields::doorStatusId),
          doorSwitch(skeletonAdapter->GetSkeleton(), fields::doorSwitchId),
          lightStatus(skeletonAdapter->GetSkeleton(), fields::lightStatusId),
          lightSwitch(skeletonAdapter->GetSkeleton(), fields::lightSwitchId),
          mirrorSwitch(skeletonAdapter->GetSkeleton(), fields::mirrorSwitchId),
          modeSwitch(skeletonAdapter->GetSkeleton(), fields::modeSwitchId),
          padSwitch(skeletonAdapter->GetSkeleton(), fields::padSwitchId),
          pepsSwitch(skeletonAdapter->GetSkeleton(), fields::pepsSwitchId),
          safetyStatus(skeletonAdapter->GetSkeleton(), fields::safetyStatusId),
          tyreFlStatus(skeletonAdapter->GetSkeleton(), fields::tyreFlStatusId),
          tyreFrStatus(skeletonAdapter->GetSkeleton(), fields::tyreFrStatusId),
          tyreRlStatus(skeletonAdapter->GetSkeleton(), fields::tyreRlStatusId),
          tyreRrStatus(skeletonAdapter->GetSkeleton(), fields::tyreRrStatusId),
          windowStatus(skeletonAdapter->GetSkeleton(), fields::windowStatusId),
          wiperFrontStatus(skeletonAdapter->GetSkeleton(), fields::wiperFrontStatusId),
          wiperFrontSwitch(skeletonAdapter->GetSkeleton(), fields::wiperFrontSwitchId),
          wiperRearStatus(skeletonAdapter->GetSkeleton(), fields::wiperRearStatusId),
          wiperRearSwitch(skeletonAdapter->GetSkeleton(), fields::wiperRearSwitchId),
          bodyInfo(skeletonAdapter->GetSkeleton(), fields::bodyInfoId) {
        commonStatus.SetGetterEntityId(fields::commonStatusGetterId);
        doorStatus.SetGetterEntityId(fields::doorStatusGetterId);
        doorSwitch.SetGetterEntityId(fields::doorSwitchGetterId);
        lightStatus.SetGetterEntityId(fields::lightStatusGetterId);
        lightSwitch.SetGetterEntityId(fields::lightSwitchGetterId);
        mirrorSwitch.SetGetterEntityId(fields::mirrorSwitchGetterId);
        modeSwitch.SetGetterEntityId(fields::modeSwitchGetterId);
        padSwitch.SetGetterEntityId(fields::padSwitchGetterId);
        pepsSwitch.SetGetterEntityId(fields::pepsSwitchGetterId);
        safetyStatus.SetGetterEntityId(fields::safetyStatusGetterId);
        tyreFlStatus.SetGetterEntityId(fields::tyreFlStatusGetterId);
        tyreFrStatus.SetGetterEntityId(fields::tyreFrStatusGetterId);
        tyreRlStatus.SetGetterEntityId(fields::tyreRlStatusGetterId);
        tyreRrStatus.SetGetterEntityId(fields::tyreRrStatusGetterId);
        windowStatus.SetGetterEntityId(fields::windowStatusGetterId);
        wiperFrontStatus.SetGetterEntityId(fields::wiperFrontStatusGetterId);
        wiperFrontSwitch.SetGetterEntityId(fields::wiperFrontSwitchGetterId);
        wiperRearStatus.SetGetterEntityId(fields::wiperRearStatusGetterId);
        wiperRearSwitch.SetGetterEntityId(fields::wiperRearSwitchGetterId);
        bodyInfo.SetGetterEntityId(fields::bodyInfoGetterId);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifier instanceId,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::ssm::VehicleInfoBodyServiceInterface::ServiceIdentifier, instanceId, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::core::InstanceSpecifier instanceSpec,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::ssm::VehicleInfoBodyServiceInterface::ServiceIdentifier, instanceSpec, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifierContainer instanceIdContainer,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::ssm::VehicleInfoBodyServiceInterface::ServiceIdentifier, instanceIdContainer, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> PreConstructResult(
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter>& preSkeletonAdapter, ara::com::MethodCallProcessingMode mode)
    {
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            if (mode == ara::com::MethodCallProcessingMode::kEvent) {
                if(!preSkeletonAdapter->SetMethodThreadNumber(preSkeletonAdapter->GetMethodThreadNumber(20), 1024)) {
                    result = false;
                    ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                    initResult.EmplaceError(errorcode);
                    break;
                }
            }
            events::bodyInfoEvt bodyInfoEvt(preSkeletonAdapter->GetSkeleton(), events::bodyInfoEvtId);
            initResult = preSkeletonAdapter->InitializeEvent(bodyInfoEvt);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::commonStatus commonStatus(preSkeletonAdapter->GetSkeleton(), fields::commonStatusId);
            commonStatus.SetGetterEntityId(fields::commonStatusGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::CommonStatus>(commonStatus);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::doorStatus doorStatus(preSkeletonAdapter->GetSkeleton(), fields::doorStatusId);
            doorStatus.SetGetterEntityId(fields::doorStatusGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::DoorStatus>(doorStatus);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::doorSwitch doorSwitch(preSkeletonAdapter->GetSkeleton(), fields::doorSwitchId);
            doorSwitch.SetGetterEntityId(fields::doorSwitchGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::DoorSwitch>(doorSwitch);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::lightStatus lightStatus(preSkeletonAdapter->GetSkeleton(), fields::lightStatusId);
            lightStatus.SetGetterEntityId(fields::lightStatusGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::LightStatus>(lightStatus);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::lightSwitch lightSwitch(preSkeletonAdapter->GetSkeleton(), fields::lightSwitchId);
            lightSwitch.SetGetterEntityId(fields::lightSwitchGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::LightSwitch>(lightSwitch);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::mirrorSwitch mirrorSwitch(preSkeletonAdapter->GetSkeleton(), fields::mirrorSwitchId);
            mirrorSwitch.SetGetterEntityId(fields::mirrorSwitchGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::MirrorSwitch>(mirrorSwitch);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::modeSwitch modeSwitch(preSkeletonAdapter->GetSkeleton(), fields::modeSwitchId);
            modeSwitch.SetGetterEntityId(fields::modeSwitchGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::ModeSwitch>(modeSwitch);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::padSwitch padSwitch(preSkeletonAdapter->GetSkeleton(), fields::padSwitchId);
            padSwitch.SetGetterEntityId(fields::padSwitchGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::PadSwitch>(padSwitch);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::pepsSwitch pepsSwitch(preSkeletonAdapter->GetSkeleton(), fields::pepsSwitchId);
            pepsSwitch.SetGetterEntityId(fields::pepsSwitchGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::PepsSwitch>(pepsSwitch);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::safetyStatus safetyStatus(preSkeletonAdapter->GetSkeleton(), fields::safetyStatusId);
            safetyStatus.SetGetterEntityId(fields::safetyStatusGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::SafetyStatus>(safetyStatus);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::tyreFlStatus tyreFlStatus(preSkeletonAdapter->GetSkeleton(), fields::tyreFlStatusId);
            tyreFlStatus.SetGetterEntityId(fields::tyreFlStatusGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::TyreStatus>(tyreFlStatus);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::tyreFrStatus tyreFrStatus(preSkeletonAdapter->GetSkeleton(), fields::tyreFrStatusId);
            tyreFrStatus.SetGetterEntityId(fields::tyreFrStatusGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::TyreStatus>(tyreFrStatus);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::tyreRlStatus tyreRlStatus(preSkeletonAdapter->GetSkeleton(), fields::tyreRlStatusId);
            tyreRlStatus.SetGetterEntityId(fields::tyreRlStatusGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::TyreStatus>(tyreRlStatus);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::tyreRrStatus tyreRrStatus(preSkeletonAdapter->GetSkeleton(), fields::tyreRrStatusId);
            tyreRrStatus.SetGetterEntityId(fields::tyreRrStatusGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::TyreStatus>(tyreRrStatus);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::windowStatus windowStatus(preSkeletonAdapter->GetSkeleton(), fields::windowStatusId);
            windowStatus.SetGetterEntityId(fields::windowStatusGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::WindowStatus>(windowStatus);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::wiperFrontStatus wiperFrontStatus(preSkeletonAdapter->GetSkeleton(), fields::wiperFrontStatusId);
            wiperFrontStatus.SetGetterEntityId(fields::wiperFrontStatusGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::Wiper>(wiperFrontStatus);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::wiperFrontSwitch wiperFrontSwitch(preSkeletonAdapter->GetSkeleton(), fields::wiperFrontSwitchId);
            wiperFrontSwitch.SetGetterEntityId(fields::wiperFrontSwitchGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::Wiper>(wiperFrontSwitch);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::wiperRearStatus wiperRearStatus(preSkeletonAdapter->GetSkeleton(), fields::wiperRearStatusId);
            wiperRearStatus.SetGetterEntityId(fields::wiperRearStatusGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::Wiper>(wiperRearStatus);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::wiperRearSwitch wiperRearSwitch(preSkeletonAdapter->GetSkeleton(), fields::wiperRearSwitchId);
            wiperRearSwitch.SetGetterEntityId(fields::wiperRearSwitchGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::Wiper>(wiperRearSwitch);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::bodyInfo bodyInfo(preSkeletonAdapter->GetSkeleton(), fields::bodyInfoId);
            bodyInfo.SetGetterEntityId(fields::bodyInfoGetterId);
            initResult = preSkeletonAdapter->InitializeField<::mdc::ssm::VehicleBodyInfo>(bodyInfo);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preSkeletonAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preSkeletonAdapter));
            ara::core::Result<ConstructionToken> preResult(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            preResult.EmplaceError(errorcode);
            return preResult;
        }
    }

    virtual ~VehicleInfoBodyServiceInterfaceSkeleton()
    {
        StopOfferService();
    }

    void OfferService()
    {
        commonStatus.VerifyValidity();
        doorStatus.VerifyValidity();
        doorSwitch.VerifyValidity();
        lightStatus.VerifyValidity();
        lightSwitch.VerifyValidity();
        mirrorSwitch.VerifyValidity();
        modeSwitch.VerifyValidity();
        padSwitch.VerifyValidity();
        pepsSwitch.VerifyValidity();
        safetyStatus.VerifyValidity();
        tyreFlStatus.VerifyValidity();
        tyreFrStatus.VerifyValidity();
        tyreRlStatus.VerifyValidity();
        tyreRrStatus.VerifyValidity();
        windowStatus.VerifyValidity();
        wiperFrontStatus.VerifyValidity();
        wiperFrontSwitch.VerifyValidity();
        wiperRearStatus.VerifyValidity();
        wiperRearSwitch.VerifyValidity();
        bodyInfo.VerifyValidity();
        skeletonAdapter->OfferService();
    }
    void StopOfferService()
    {
        skeletonAdapter->StopOfferService();
        commonStatus.ResetInitState();
        doorStatus.ResetInitState();
        doorSwitch.ResetInitState();
        lightStatus.ResetInitState();
        lightSwitch.ResetInitState();
        mirrorSwitch.ResetInitState();
        modeSwitch.ResetInitState();
        padSwitch.ResetInitState();
        pepsSwitch.ResetInitState();
        safetyStatus.ResetInitState();
        tyreFlStatus.ResetInitState();
        tyreFrStatus.ResetInitState();
        tyreRlStatus.ResetInitState();
        tyreRrStatus.ResetInitState();
        windowStatus.ResetInitState();
        wiperFrontStatus.ResetInitState();
        wiperFrontSwitch.ResetInitState();
        wiperRearStatus.ResetInitState();
        wiperRearSwitch.ResetInitState();
        bodyInfo.ResetInitState();
    }
    ara::core::Future<bool> ProcessNextMethodCall()
    {
        return skeletonAdapter->ProcessNextMethodCall();
    }
    bool SetMethodThreadNumber(const std::uint16_t& number, const std::uint16_t& queueSize)
    {
        return skeletonAdapter->SetMethodThreadNumber(number, queueSize);
    }

    events::bodyInfoEvt bodyInfoEvt;
    fields::commonStatus commonStatus;
    fields::doorStatus doorStatus;
    fields::doorSwitch doorSwitch;
    fields::lightStatus lightStatus;
    fields::lightSwitch lightSwitch;
    fields::mirrorSwitch mirrorSwitch;
    fields::modeSwitch modeSwitch;
    fields::padSwitch padSwitch;
    fields::pepsSwitch pepsSwitch;
    fields::safetyStatus safetyStatus;
    fields::tyreFlStatus tyreFlStatus;
    fields::tyreFrStatus tyreFrStatus;
    fields::tyreRlStatus tyreRlStatus;
    fields::tyreRrStatus tyreRrStatus;
    fields::windowStatus windowStatus;
    fields::wiperFrontStatus wiperFrontStatus;
    fields::wiperFrontSwitch wiperFrontSwitch;
    fields::wiperRearStatus wiperRearStatus;
    fields::wiperRearSwitch wiperRearSwitch;
    fields::bodyInfo bodyInfo;
};
} // namespace skeleton
} // namespace ssm
} // namespace mdc

#endif // MDC_SSM_VEHICLEINFOBODYSERVICEINTERFACE_SKELETON_H
