/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_DEVM_FC_DEVMFCSERVICEINTERFACE_COMMON_H
#define MDC_DEVM_DEVM_FC_DEVMFCSERVICEINTERFACE_COMMON_H

#include "ara/com/types.h"
#include "mdc/devm/impl_type_faultdmdata.h"
#include "mdc/devm/impl_type_faultphmdata.h"
#include "impl_type_uint32.h"
#include "impl_type_uint16.h"
#include "impl_type_uint8.h"
#include "mdc/devm/impl_type_uint8list.h"
#include "impl_type_int32.h"

namespace mdc {
namespace devm {
namespace devm_fc {
class DevmFcServiceInterface {
public:
    constexpr DevmFcServiceInterface() = default;
    constexpr static ara::com::ServiceIdentifierType ServiceIdentifier = ara::com::ServiceIdentifierType("/HuaweiMDC/MdcPlatformServices/DevmFcServiceInterface/DevmFcServiceInterface");
    constexpr static ara::com::ServiceVersionType ServiceVersion = ara::com::ServiceVersionType("1.1");
};
} // namespace devm_fc
} // namespace devm
} // namespace mdc

#endif // MDC_DEVM_DEVM_FC_DEVMFCSERVICEINTERFACE_COMMON_H
