/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_DEVM_FC_DEVMFCSERVICEINTERFACE_PROXY_H
#define MDC_DEVM_DEVM_FC_DEVMFCSERVICEINTERFACE_PROXY_H

#include "ara/com/internal/proxy/proxy_adapter.h"
#include "ara/com/internal/proxy/event_adapter.h"
#include "ara/com/internal/proxy/field_adapter.h"
#include "ara/com/internal/proxy/method_adapter.h"
#include "mdc/devm/devm_fc/devmfcserviceinterface_common.h"
#include <string>
#include <cfloat>
#include <cmath>

namespace mdc {
namespace devm {
namespace devm_fc {
namespace proxy {
namespace events {
    using FaultReportDmEvent = ara::com::internal::proxy::event::EventAdapter<::mdc::devm::FaultDmData>;
    using FaultReportPhmEvent = ara::com::internal::proxy::event::EventAdapter<::mdc::devm::FaultPhmData>;
    static constexpr ara::com::internal::EntityId FaultReportDmEventId = 26251; //FaultReportDmEvent_event_hash
    static constexpr ara::com::internal::EntityId FaultReportPhmEventId = 25313; //FaultReportPhmEvent_event_hash
}

namespace fields {
}

namespace methods {
static constexpr ara::com::internal::EntityId DidOperateId = 57911; //DidOperate_method_hash
static constexpr ara::com::internal::EntityId GetStateId = 64093; //GetState_method_hash
static constexpr ara::com::internal::EntityId ImportDataDefineId = 39249; //ImportDataDefine_method_hash


class DidOperate {
public:
    struct Output {
        ::mdc::devm::Uint8List rxData;
        ::Int32 result;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(rxData);
            fun(result);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(rxData);
            fun(result);
        }

        bool operator == (const Output& t) const
        {
           return (rxData == t.rxData) && (result == t.result);
        }
    };

    DidOperate(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()(const ::UInt32& devId, const ::UInt16& did, const ::UInt8& didAction, const ::mdc::devm::Uint8List& txData)
    {
        return method_(devId, did, didAction, txData);
    }

    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt16, ::UInt8, ::mdc::devm::Uint8List> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output, ::UInt32, ::UInt16, ::UInt8, ::mdc::devm::Uint8List> method_;
};

class GetState {
public:
    struct Output {
        ::UInt8 state;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(state);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(state);
        }

        bool operator == (const Output& t) const
        {
           return (state == t.state);
        }
    };

    GetState(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};

class ImportDataDefine {
public:
    struct Output {
        ::mdc::devm::Uint8List uint8List;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(uint8List);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(uint8List);
        }

        bool operator == (const Output& t) const
        {
           return (uint8List == t.uint8List);
        }
    };

    ImportDataDefine(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};
} // namespace methods

class DevmFcServiceInterfaceProxy {
private:
    std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxyAdapter;
public:
    using HandleType = vrtf::vcc::api::types::HandleType;
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxy): ptr(std::move(proxy)){}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> GetProxyAdapter()
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> ptr;
    };

    virtual ~DevmFcServiceInterfaceProxy()
    {
        FaultReportDmEvent.UnsetReceiveHandler();
        FaultReportDmEvent.Unsubscribe();
        FaultReportPhmEvent.UnsetReceiveHandler();
        FaultReportPhmEvent.Unsubscribe();
    }

    explicit DevmFcServiceInterfaceProxy(const vrtf::vcc::api::types::HandleType &handle)
        : proxyAdapter(std::make_unique<ara::com::internal::proxy::ProxyAdapter>(::mdc::devm::devm_fc::DevmFcServiceInterface::ServiceIdentifier, handle)),
          FaultReportDmEvent(proxyAdapter->GetProxy(), events::FaultReportDmEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_fc::DevmFcServiceInterface::ServiceIdentifier),
          FaultReportPhmEvent(proxyAdapter->GetProxy(), events::FaultReportPhmEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_fc::DevmFcServiceInterface::ServiceIdentifier),
          DidOperate(proxyAdapter->GetProxy(), methods::DidOperateId),
          GetState(proxyAdapter->GetProxy(), methods::GetStateId),
          ImportDataDefine(proxyAdapter->GetProxy(), methods::ImportDataDefineId){
            ara::core::Result<void> resultDidOperate = proxyAdapter->InitializeMethod<methods::DidOperate::Output>(methods::DidOperateId);
            ThrowError(resultDidOperate);
            ara::core::Result<void> resultGetState = proxyAdapter->InitializeMethod<methods::GetState::Output>(methods::GetStateId);
            ThrowError(resultGetState);
            ara::core::Result<void> resultImportDataDefine = proxyAdapter->InitializeMethod<methods::ImportDataDefine::Output>(methods::ImportDataDefineId);
            ThrowError(resultImportDataDefine);
        }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }

    DevmFcServiceInterfaceProxy(const DevmFcServiceInterfaceProxy&) = delete;
    DevmFcServiceInterfaceProxy& operator=(const DevmFcServiceInterfaceProxy&) = delete;

    DevmFcServiceInterfaceProxy(DevmFcServiceInterfaceProxy&& other) = default;
    DevmFcServiceInterfaceProxy& operator=(DevmFcServiceInterfaceProxy&& other) = default;
    DevmFcServiceInterfaceProxy(ConstructionToken&& token) noexcept
        : proxyAdapter(token.GetProxyAdapter()),
          FaultReportDmEvent(proxyAdapter->GetProxy(), events::FaultReportDmEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_fc::DevmFcServiceInterface::ServiceIdentifier),
          FaultReportPhmEvent(proxyAdapter->GetProxy(), events::FaultReportPhmEventId, proxyAdapter->GetHandle(), ::mdc::devm::devm_fc::DevmFcServiceInterface::ServiceIdentifier),
          DidOperate(proxyAdapter->GetProxy(), methods::DidOperateId),
          GetState(proxyAdapter->GetProxy(), methods::GetStateId),
          ImportDataDefine(proxyAdapter->GetProxy(), methods::ImportDataDefineId){
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        const vrtf::vcc::api::types::HandleType &handle)
    {
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> preProxyAdapter =
            std::make_unique<ara::com::internal::proxy::ProxyAdapter>(
               ::mdc::devm::devm_fc::DevmFcServiceInterface::ServiceIdentifier, handle);
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            methods::DidOperate DidOperate(preProxyAdapter->GetProxy(), methods::DidOperateId);
            initResult = preProxyAdapter->InitializeMethod<methods::DidOperate::Output>(methods::DidOperateId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetState GetState(preProxyAdapter->GetProxy(), methods::GetStateId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetState::Output>(methods::GetStateId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::ImportDataDefine ImportDataDefine(preProxyAdapter->GetProxy(), methods::ImportDataDefineId);
            initResult = preProxyAdapter->InitializeMethod<methods::ImportDataDefine::Output>(methods::ImportDataDefineId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preProxyAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preProxyAdapter));
            ara::core::Result<ConstructionToken> result(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            result.EmplaceError(errorcode);
            return result;
        }
    }


    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::devm::devm_fc::DevmFcServiceInterface::ServiceIdentifier, instance);
    }

    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::devm::devm_fc::DevmFcServiceInterface::ServiceIdentifier, specifier);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::devm::devm_fc::DevmFcServiceInterface::ServiceIdentifier, instance);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::devm::devm_fc::DevmFcServiceInterface::ServiceIdentifier, specifier);
    }

    static void StopFindService(const ara::com::FindServiceHandle& handle)
    {
        ara::com::internal::proxy::ProxyAdapter::StopFindService(handle);
    }

    HandleType GetHandle() const
    {
        return proxyAdapter->GetHandle();
    }
    events::FaultReportDmEvent FaultReportDmEvent;
    events::FaultReportPhmEvent FaultReportPhmEvent;
    methods::DidOperate DidOperate;
    methods::GetState GetState;
    methods::ImportDataDefine ImportDataDefine;
};
} // namespace proxy
} // namespace devm_fc
} // namespace devm
} // namespace mdc

#endif // MDC_DEVM_DEVM_FC_DEVMFCSERVICEINTERFACE_PROXY_H
