/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_DEVM_DEVM_ISP_DEVMISPSERVICEINTERFACE_PROXY_H
#define MDC_DEVM_DEVM_ISP_DEVMISPSERVICEINTERFACE_PROXY_H

#include "ara/com/internal/proxy/proxy_adapter.h"
#include "ara/com/internal/proxy/event_adapter.h"
#include "ara/com/internal/proxy/field_adapter.h"
#include "ara/com/internal/proxy/method_adapter.h"
#include "mdc/devm/devm_isp/devmispserviceinterface_common.h"
#include <string>
#include <cfloat>
#include <cmath>

namespace mdc {
namespace devm {
namespace devm_isp {
namespace proxy {
namespace events {
}

namespace fields {
}

namespace methods {
static constexpr ara::com::internal::EntityId GetISPVersionId = 51012; //GetISPVersion_method_hash
static constexpr ara::com::internal::EntityId GetStateId = 64093; //GetState_method_hash


class GetISPVersion {
public:
    struct Output {
        ::mdc::devm::VersionISP VersionISP;

        static bool IsPlane()
        {
            return false;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(VersionISP);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(VersionISP);
        }

        bool operator == (const Output& t) const
        {
           return (VersionISP == t.VersionISP);
        }
    };

    GetISPVersion(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};

class GetState {
public:
    struct Output {
        ::mdc::devm::WorkStatusType state;

        static bool IsPlane()
        {
            return true;
        }

        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(state);
        }

        template<typename F>
        void enumerate(F& fun) const
        {
            fun(state);
        }

        bool operator == (const Output& t) const
        {
           return (state == t.state);
        }
    };

    GetState(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId): method_(proxy, entityId){}
    void Initialize(std::shared_ptr<vrtf::vcc::Proxy>& proxy, ara::com::internal::EntityId entityId)
    {
        method_.Initialize(proxy, entityId);
    }
    ara::core::Future<Output> operator()()
    {
        return method_();
    }

    ara::com::internal::proxy::method::MethodAdapter<Output> GetMethod()
    {
        return method_;
    }

private:
    ara::com::internal::proxy::method::MethodAdapter<Output> method_;
};
} // namespace methods

class DevmIspServiceInterfaceProxy {
private:
    std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxyAdapter;
public:
    using HandleType = vrtf::vcc::api::types::HandleType;
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> proxy): ptr(std::move(proxy)){}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> GetProxyAdapter()
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> ptr;
    };

    virtual ~DevmIspServiceInterfaceProxy()
    {
    }

    explicit DevmIspServiceInterfaceProxy(const vrtf::vcc::api::types::HandleType &handle)
        : proxyAdapter(std::make_unique<ara::com::internal::proxy::ProxyAdapter>(::mdc::devm::devm_isp::DevmIspServiceInterface::ServiceIdentifier, handle)),
          GetISPVersion(proxyAdapter->GetProxy(), methods::GetISPVersionId),
          GetState(proxyAdapter->GetProxy(), methods::GetStateId){
            ara::core::Result<void> resultGetISPVersion = proxyAdapter->InitializeMethod<methods::GetISPVersion::Output>(methods::GetISPVersionId);
            ThrowError(resultGetISPVersion);
            ara::core::Result<void> resultGetState = proxyAdapter->InitializeMethod<methods::GetState::Output>(methods::GetStateId);
            ThrowError(resultGetState);
        }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }

    DevmIspServiceInterfaceProxy(const DevmIspServiceInterfaceProxy&) = delete;
    DevmIspServiceInterfaceProxy& operator=(const DevmIspServiceInterfaceProxy&) = delete;

    DevmIspServiceInterfaceProxy(DevmIspServiceInterfaceProxy&& other) = default;
    DevmIspServiceInterfaceProxy& operator=(DevmIspServiceInterfaceProxy&& other) = default;
    DevmIspServiceInterfaceProxy(ConstructionToken&& token) noexcept
        : proxyAdapter(token.GetProxyAdapter()),
          GetISPVersion(proxyAdapter->GetProxy(), methods::GetISPVersionId),
          GetState(proxyAdapter->GetProxy(), methods::GetStateId){
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        const vrtf::vcc::api::types::HandleType &handle)
    {
        std::unique_ptr<ara::com::internal::proxy::ProxyAdapter> preProxyAdapter =
            std::make_unique<ara::com::internal::proxy::ProxyAdapter>(
               ::mdc::devm::devm_isp::DevmIspServiceInterface::ServiceIdentifier, handle);
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            methods::GetISPVersion GetISPVersion(preProxyAdapter->GetProxy(), methods::GetISPVersionId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetISPVersion::Output>(methods::GetISPVersionId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            methods::GetState GetState(preProxyAdapter->GetProxy(), methods::GetStateId);
            initResult = preProxyAdapter->InitializeMethod<methods::GetState::Output>(methods::GetStateId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preProxyAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preProxyAdapter));
            ara::core::Result<ConstructionToken> result(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            result.EmplaceError(errorcode);
            return result;
        }
    }


    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::devm::devm_isp::DevmIspServiceInterface::ServiceIdentifier, instance);
    }

    static ara::com::FindServiceHandle StartFindService(
        ara::com::FindServiceHandler<ara::com::internal::proxy::ProxyAdapter::HandleType> handler,
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::StartFindService(handler, ::mdc::devm::devm_isp::DevmIspServiceInterface::ServiceIdentifier, specifier);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::com::InstanceIdentifier instance)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::devm::devm_isp::DevmIspServiceInterface::ServiceIdentifier, instance);
    }

    static ara::com::ServiceHandleContainer<ara::com::internal::proxy::ProxyAdapter::HandleType> FindService(
        ara::core::InstanceSpecifier specifier)
    {
        return ara::com::internal::proxy::ProxyAdapter::FindService(::mdc::devm::devm_isp::DevmIspServiceInterface::ServiceIdentifier, specifier);
    }

    static void StopFindService(const ara::com::FindServiceHandle& handle)
    {
        ara::com::internal::proxy::ProxyAdapter::StopFindService(handle);
    }

    HandleType GetHandle() const
    {
        return proxyAdapter->GetHandle();
    }
    methods::GetISPVersion GetISPVersion;
    methods::GetState GetState;
};
} // namespace proxy
} // namespace devm_isp
} // namespace devm
} // namespace mdc

#endif // MDC_DEVM_DEVM_ISP_DEVMISPSERVICEINTERFACE_PROXY_H
