/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_MDCCANFDRX_CANFDRXSERVICEINTERFACE_COMMON_H
#define MDC_MDCCANFDRX_CANFDRXSERVICEINTERFACE_COMMON_H

#include "ara/com/types.h"
#include "mdc/mdccan/impl_type_canfdbusdataparaml.h"

namespace mdc {
namespace mdccanfdrx {
class CanFdRxServiceInterface {
public:
    constexpr CanFdRxServiceInterface() = default;
    constexpr static ara::com::ServiceIdentifierType ServiceIdentifier = ara::com::ServiceIdentifierType("/HuaweiMDC/MdcPlatformServices/CanFdRxServiceInterface/CanFdRxServiceInterface");
    constexpr static ara::com::ServiceVersionType ServiceVersion = ara::com::ServiceVersionType("1.1");
};
} // namespace mdccanfdrx
} // namespace mdc

#endif // MDC_MDCCANFDRX_CANFDRXSERVICEINTERFACE_COMMON_H
