/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#include "mdc/ex_wdg/exwdglowpowernotifyservice_skeleton.h"
#include "mdc/ex_wdg/qa_proxy.h"
#include "mdc/fm/faultpublishservice_skeleton.h"
#include "mdc/fm/fmfaultreceiveservice_proxy.h"
#include "mdc/fm/fmqueryservice_skeleton.h"
#include "mdc/fm/fmreporteventservice_skeleton.h"
#include "mdc/psm/psmtriggerswitchservice_proxy.h"
