/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_RTRACK_IMPL_TYPE_RADARTRACKARRAY_H
#define ARA_RTRACK_IMPL_TYPE_RADARTRACKARRAY_H
#include <cfloat>
#include <cmath>
#include "ara/radar/impl_type_header.h"
#include "impl_type_uint8.h"
#include "ara/radar/impl_type_radarstate.h"
#include "impl_type_tracklist.h"

namespace ara {
namespace rtrack {
struct RadarTrackArray {
    ::ara::radar::Header header;
    ::UInt8 sensorId;
    ::ara::radar::RadarState radarState;
    ::TrackList trackList;

    static bool IsPlane()
    {
        return false;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(header);
        fun(sensorId);
        fun(radarState);
        fun(trackList);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(header);
        fun(sensorId);
        fun(radarState);
        fun(trackList);
    }

    bool operator == (const ::ara::rtrack::RadarTrackArray& t) const
    {
        return (header == t.header) && (sensorId == t.sensorId) && (radarState == t.radarState) && (trackList == t.trackList);
    }
};
} // namespace rtrack
} // namespace ara


#endif // ARA_RTRACK_IMPL_TYPE_RADARTRACKARRAY_H
