/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_NAVIGATION_IMPL_TYPE_NAVIROADPOINT_H
#define ARA_NAVIGATION_IMPL_TYPE_NAVIROADPOINT_H
#include <cfloat>
#include <cmath>
#include "impl_type_int32.h"
#include "impl_type_double.h"
#include "impl_type_point.h"

namespace ara {
namespace navigation {
struct NaviRoadPoint {
    ::Int32 id;
    ::Double s;
    ::Point pose;

    static bool IsPlane()
    {
        return true;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(id);
        fun(s);
        fun(pose);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(id);
        fun(s);
        fun(pose);
    }

    bool operator == (const ::ara::navigation::NaviRoadPoint& t) const
    {
        return (id == t.id) && (fabs(s - t.s) < FLT_EPSILON) && (pose == t.pose);
    }
};
} // namespace navigation
} // namespace ara


#endif // ARA_NAVIGATION_IMPL_TYPE_NAVIROADPOINT_H
