/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_TSYNC_PPSINFO_TSYNCMEASURESERVICEINTERFACE_COMMON_H
#define ARA_TSYNC_PPSINFO_TSYNCMEASURESERVICEINTERFACE_COMMON_H

#include "ara/com/types.h"
#include "ara/tsync/impl_type_measuredata.h"

namespace ara {
namespace tsync {
namespace ppsinfo {
class TsyncMeasureServiceInterface {
public:
    constexpr TsyncMeasureServiceInterface() = default;
    constexpr static ara::com::ServiceIdentifierType ServiceIdentifier = ara::com::ServiceIdentifierType("/HuaweiMDC/PlatformServiceInterface/TsyncMeasureServiceInterface/TsyncMeasureServiceInterface");
    constexpr static ara::com::ServiceVersionType ServiceVersion = ara::com::ServiceVersionType("1.1");
};
} // namespace ppsinfo
} // namespace tsync
} // namespace ara

#endif // ARA_TSYNC_PPSINFO_TSYNCMEASURESERVICEINTERFACE_COMMON_H
