/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#include "mdc/devm/devm_mcu_300f/devmmcu300fconfigtranserviceinterface_proxy.h"
#include "mdc/nrm/nrmc/nrmcenterserviceinterface_skeleton.h"
#include "mdc/nrm/nrmn/nrmnserviceinterface_proxy.h"
