/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_NRM_NRMC_NRMCENTERSERVICEINTERFACE_COMMON_H
#define MDC_NRM_NRMC_NRMCENTERSERVICEINTERFACE_COMMON_H

#include "ara/com/types.h"
#include "impl_type_string.h"
#include "mdc/nrm/impl_type_cancfg.h"
#include "mdc/nrm/impl_type_domainconfiglist.h"
#include "mdc/nrm/impl_type_portconfiglist.h"
#include "impl_type_int32.h"

namespace mdc {
namespace nrm {
namespace nrmc {
class NrmCenterServiceInterface {
public:
    constexpr NrmCenterServiceInterface() = default;
    constexpr static ara::com::ServiceIdentifierType ServiceIdentifier = ara::com::ServiceIdentifierType("/HuaweiMDC/MdcPlatformServices/NrmcServiceInterface/NrmCenterServiceInterface");
    constexpr static ara::com::ServiceVersionType ServiceVersion = ara::com::ServiceVersionType("1.1");
};
} // namespace nrmc
} // namespace nrm
} // namespace mdc

#endif // MDC_NRM_NRMC_NRMCENTERSERVICEINTERFACE_COMMON_H
