/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_NRM_NRMC_NRMCENTERSERVICEINTERFACE_SKELETON_H
#define MDC_NRM_NRMC_NRMCENTERSERVICEINTERFACE_SKELETON_H

#include "ara/com/internal/skeleton/skeleton_adapter.h"
#include "ara/com/internal/skeleton/event_adapter.h"
#include "ara/com/internal/skeleton/field_adapter.h"
#include "ara/com/internal/skeleton/method_adapter.h"
#include "mdc/nrm/nrmc/nrmcenterserviceinterface_common.h"
#include <cstdint>
#include <cfloat>
#include <cmath>

namespace mdc {
namespace nrm {
namespace nrmc {
namespace skeleton {
namespace events
{
}

namespace methods
{
    using GetCanAllStatHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetCanConfigHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetCanDevNameHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetDomainNetTopConfigHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetEthAllStatHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetNetStatHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetPanelNetTopConfigHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetSensorEthDevNameHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetUartDevNameHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using ReportInitLswStatusHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using SetupLswHandle = ara::com::internal::skeleton::method::MethodAdapter;
    static constexpr ara::com::internal::EntityId GetCanAllStatId = 47653; //GetCanAllStat_method_hash
    static constexpr ara::com::internal::EntityId GetCanConfigId = 49603; //GetCanConfig_method_hash
    static constexpr ara::com::internal::EntityId GetCanDevNameId = 6325; //GetCanDevName_method_hash
    static constexpr ara::com::internal::EntityId GetDomainNetTopConfigId = 58208; //GetDomainNetTopConfig_method_hash
    static constexpr ara::com::internal::EntityId GetEthAllStatId = 2404; //GetEthAllStat_method_hash
    static constexpr ara::com::internal::EntityId GetNetStatId = 19476; //GetNetStat_method_hash
    static constexpr ara::com::internal::EntityId GetPanelNetTopConfigId = 34163; //GetPanelNetTopConfig_method_hash
    static constexpr ara::com::internal::EntityId GetSensorEthDevNameId = 45498; //GetSensorEthDevName_method_hash
    static constexpr ara::com::internal::EntityId GetUartDevNameId = 38675; //GetUartDevName_method_hash
    static constexpr ara::com::internal::EntityId ReportInitLswStatusId = 22352; //ReportInitLswStatus_method_hash
    static constexpr ara::com::internal::EntityId SetupLswId = 55707; //SetupLsw_method_hash
}

namespace fields
{
}

class NrmCenterServiceInterfaceSkeleton {
private:
    std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeletonAdapter;
    void ConstructSkeleton(ara::com::MethodCallProcessingMode mode)
    {
        if (mode == ara::com::MethodCallProcessingMode::kEvent) {
            if (!(skeletonAdapter->SetMethodThreadNumber(skeletonAdapter->GetMethodThreadNumber(11), 1024))) {
#ifndef NOT_SUPPORT_EXCEPTIONS
                ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                throw ara::com::ComException(std::move(errorcode));
#else
                std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
            }
        }
        ara::core::Result<void> resultGetCanAllStat = skeletonAdapter->InitializeMethod<ara::core::Future<GetCanAllStatOutput>>(methods::GetCanAllStatId);
        ThrowError(resultGetCanAllStat);
        ara::core::Result<void> resultGetCanConfig = skeletonAdapter->InitializeMethod<ara::core::Future<GetCanConfigOutput>>(methods::GetCanConfigId);
        ThrowError(resultGetCanConfig);
        ara::core::Result<void> resultGetCanDevName = skeletonAdapter->InitializeMethod<ara::core::Future<GetCanDevNameOutput>>(methods::GetCanDevNameId);
        ThrowError(resultGetCanDevName);
        ara::core::Result<void> resultGetDomainNetTopConfig = skeletonAdapter->InitializeMethod<ara::core::Future<GetDomainNetTopConfigOutput>>(methods::GetDomainNetTopConfigId);
        ThrowError(resultGetDomainNetTopConfig);
        ara::core::Result<void> resultGetEthAllStat = skeletonAdapter->InitializeMethod<ara::core::Future<GetEthAllStatOutput>>(methods::GetEthAllStatId);
        ThrowError(resultGetEthAllStat);
        ara::core::Result<void> resultGetNetStat = skeletonAdapter->InitializeMethod<ara::core::Future<GetNetStatOutput>>(methods::GetNetStatId);
        ThrowError(resultGetNetStat);
        ara::core::Result<void> resultGetPanelNetTopConfig = skeletonAdapter->InitializeMethod<ara::core::Future<GetPanelNetTopConfigOutput>>(methods::GetPanelNetTopConfigId);
        ThrowError(resultGetPanelNetTopConfig);
        ara::core::Result<void> resultGetSensorEthDevName = skeletonAdapter->InitializeMethod<ara::core::Future<GetSensorEthDevNameOutput>>(methods::GetSensorEthDevNameId);
        ThrowError(resultGetSensorEthDevName);
        ara::core::Result<void> resultGetUartDevName = skeletonAdapter->InitializeMethod<ara::core::Future<GetUartDevNameOutput>>(methods::GetUartDevNameId);
        ThrowError(resultGetUartDevName);
        ara::core::Result<void> resultReportInitLswStatus = skeletonAdapter->InitializeMethod<ara::core::Future<ReportInitLswStatusOutput>>(methods::ReportInitLswStatusId);
        ThrowError(resultReportInitLswStatus);
        ara::core::Result<void> resultSetupLsw = skeletonAdapter->InitializeMethod<ara::core::Future<SetupLswOutput>>(methods::SetupLswId);
        ThrowError(resultSetupLsw);
    }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }
public:
    
    struct GetCanAllStatOutput {
        ::String result;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }
    
        bool operator == (const GetCanAllStatOutput& t) const
        {
            return (result == t.result);
        }
    };
    
    
    struct GetCanConfigOutput {
        ::mdc::nrm::CanCfg mode;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(mode);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(mode);
        }
    
        bool operator == (const GetCanConfigOutput& t) const
        {
            return (mode == t.mode);
        }
    };
    
    
    struct GetCanDevNameOutput {
        ::String devName;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(devName);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(devName);
        }
    
        bool operator == (const GetCanDevNameOutput& t) const
        {
            return (devName == t.devName);
        }
    };
    
    
    struct GetDomainNetTopConfigOutput {
        ::mdc::nrm::DomainConfigList domainNetTopCfg;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(domainNetTopCfg);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(domainNetTopCfg);
        }
    
        bool operator == (const GetDomainNetTopConfigOutput& t) const
        {
            return (domainNetTopCfg == t.domainNetTopCfg);
        }
    };
    
    
    struct GetEthAllStatOutput {
        ::String result;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }
    
        bool operator == (const GetEthAllStatOutput& t) const
        {
            return (result == t.result);
        }
    };
    
    
    struct GetNetStatOutput {
        ::String result;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }
    
        bool operator == (const GetNetStatOutput& t) const
        {
            return (result == t.result);
        }
    };
    
    
    struct GetPanelNetTopConfigOutput {
        ::mdc::nrm::PortConfigList netTopConfig;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(netTopConfig);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(netTopConfig);
        }
    
        bool operator == (const GetPanelNetTopConfigOutput& t) const
        {
            return (netTopConfig == t.netTopConfig);
        }
    };
    
    
    struct GetSensorEthDevNameOutput {
        ::String devName;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(devName);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(devName);
        }
    
        bool operator == (const GetSensorEthDevNameOutput& t) const
        {
            return (devName == t.devName);
        }
    };
    
    
    struct GetUartDevNameOutput {
        ::String devName;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(devName);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(devName);
        }
    
        bool operator == (const GetUartDevNameOutput& t) const
        {
            return (devName == t.devName);
        }
    };
    
    
    struct ReportInitLswStatusOutput {
        ::Int32 result;
    
        static bool IsPlane()
        {
            return true;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }
    
        bool operator == (const ReportInitLswStatusOutput& t) const
        {
            return (result == t.result);
        }
    };
    
    
    struct SetupLswOutput {
        ::Int32 result;
    
        static bool IsPlane()
        {
            return true;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }
    
        bool operator == (const SetupLswOutput& t) const
        {
            return (result == t.result);
        }
    };
    
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeleton)
            : ptr(std::move(skeleton)) {}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> GetSkeletonAdapter() 
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> ptr;
    };
    explicit NrmCenterServiceInterfaceSkeleton(ara::com::InstanceIdentifier instanceId,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        : skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::nrm::nrmc::NrmCenterServiceInterface::ServiceIdentifier, instanceId, mode)),
          GetCanAllStatHandle(skeletonAdapter->GetSkeleton(), methods::GetCanAllStatId),
          GetCanConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetCanConfigId),
          GetCanDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetCanDevNameId),
          GetDomainNetTopConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetDomainNetTopConfigId),
          GetEthAllStatHandle(skeletonAdapter->GetSkeleton(), methods::GetEthAllStatId),
          GetNetStatHandle(skeletonAdapter->GetSkeleton(), methods::GetNetStatId),
          GetPanelNetTopConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetPanelNetTopConfigId),
          GetSensorEthDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetSensorEthDevNameId),
          GetUartDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetUartDevNameId),
          ReportInitLswStatusHandle(skeletonAdapter->GetSkeleton(), methods::ReportInitLswStatusId),
          SetupLswHandle(skeletonAdapter->GetSkeleton(), methods::SetupLswId){
        ConstructSkeleton(mode);
    }

    explicit NrmCenterServiceInterfaceSkeleton(ara::core::InstanceSpecifier instanceSpec,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::nrm::nrmc::NrmCenterServiceInterface::ServiceIdentifier, instanceSpec, mode)),
          GetCanAllStatHandle(skeletonAdapter->GetSkeleton(), methods::GetCanAllStatId),
          GetCanConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetCanConfigId),
          GetCanDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetCanDevNameId),
          GetDomainNetTopConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetDomainNetTopConfigId),
          GetEthAllStatHandle(skeletonAdapter->GetSkeleton(), methods::GetEthAllStatId),
          GetNetStatHandle(skeletonAdapter->GetSkeleton(), methods::GetNetStatId),
          GetPanelNetTopConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetPanelNetTopConfigId),
          GetSensorEthDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetSensorEthDevNameId),
          GetUartDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetUartDevNameId),
          ReportInitLswStatusHandle(skeletonAdapter->GetSkeleton(), methods::ReportInitLswStatusId),
          SetupLswHandle(skeletonAdapter->GetSkeleton(), methods::SetupLswId){
        ConstructSkeleton(mode);
    }

    explicit NrmCenterServiceInterfaceSkeleton(ara::com::InstanceIdentifierContainer instanceContainer,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::nrm::nrmc::NrmCenterServiceInterface::ServiceIdentifier, instanceContainer, mode)),
          GetCanAllStatHandle(skeletonAdapter->GetSkeleton(), methods::GetCanAllStatId),
          GetCanConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetCanConfigId),
          GetCanDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetCanDevNameId),
          GetDomainNetTopConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetDomainNetTopConfigId),
          GetEthAllStatHandle(skeletonAdapter->GetSkeleton(), methods::GetEthAllStatId),
          GetNetStatHandle(skeletonAdapter->GetSkeleton(), methods::GetNetStatId),
          GetPanelNetTopConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetPanelNetTopConfigId),
          GetSensorEthDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetSensorEthDevNameId),
          GetUartDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetUartDevNameId),
          ReportInitLswStatusHandle(skeletonAdapter->GetSkeleton(), methods::ReportInitLswStatusId),
          SetupLswHandle(skeletonAdapter->GetSkeleton(), methods::SetupLswId){
        ConstructSkeleton(mode);
    }

    NrmCenterServiceInterfaceSkeleton(const NrmCenterServiceInterfaceSkeleton&) = delete;
    NrmCenterServiceInterfaceSkeleton& operator=(const NrmCenterServiceInterfaceSkeleton&) = delete;

    NrmCenterServiceInterfaceSkeleton(NrmCenterServiceInterfaceSkeleton&& other) = default;
    NrmCenterServiceInterfaceSkeleton& operator=(NrmCenterServiceInterfaceSkeleton&& other) = default;
    NrmCenterServiceInterfaceSkeleton(ConstructionToken&& token) noexcept 
        : skeletonAdapter(token.GetSkeletonAdapter()),
          GetCanAllStatHandle(skeletonAdapter->GetSkeleton(), methods::GetCanAllStatId),
          GetCanConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetCanConfigId),
          GetCanDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetCanDevNameId),
          GetDomainNetTopConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetDomainNetTopConfigId),
          GetEthAllStatHandle(skeletonAdapter->GetSkeleton(), methods::GetEthAllStatId),
          GetNetStatHandle(skeletonAdapter->GetSkeleton(), methods::GetNetStatId),
          GetPanelNetTopConfigHandle(skeletonAdapter->GetSkeleton(), methods::GetPanelNetTopConfigId),
          GetSensorEthDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetSensorEthDevNameId),
          GetUartDevNameHandle(skeletonAdapter->GetSkeleton(), methods::GetUartDevNameId),
          ReportInitLswStatusHandle(skeletonAdapter->GetSkeleton(), methods::ReportInitLswStatusId),
          SetupLswHandle(skeletonAdapter->GetSkeleton(), methods::SetupLswId){
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifier instanceId,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::nrm::nrmc::NrmCenterServiceInterface::ServiceIdentifier, instanceId, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::core::InstanceSpecifier instanceSpec,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::nrm::nrmc::NrmCenterServiceInterface::ServiceIdentifier, instanceSpec, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifierContainer instanceIdContainer,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::nrm::nrmc::NrmCenterServiceInterface::ServiceIdentifier, instanceIdContainer, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> PreConstructResult(
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter>& preSkeletonAdapter, ara::com::MethodCallProcessingMode mode)
    {
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            if (mode == ara::com::MethodCallProcessingMode::kEvent) {
                if(!preSkeletonAdapter->SetMethodThreadNumber(preSkeletonAdapter->GetMethodThreadNumber(11), 1024)) {
                    result = false;
                    ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                    initResult.EmplaceError(errorcode);
                    break;
                }
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetCanAllStatOutput>>(methods::GetCanAllStatId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetCanConfigOutput>>(methods::GetCanConfigId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetCanDevNameOutput>>(methods::GetCanDevNameId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetDomainNetTopConfigOutput>>(methods::GetDomainNetTopConfigId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetEthAllStatOutput>>(methods::GetEthAllStatId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetNetStatOutput>>(methods::GetNetStatId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetPanelNetTopConfigOutput>>(methods::GetPanelNetTopConfigId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetSensorEthDevNameOutput>>(methods::GetSensorEthDevNameId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetUartDevNameOutput>>(methods::GetUartDevNameId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<ReportInitLswStatusOutput>>(methods::ReportInitLswStatusId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<SetupLswOutput>>(methods::SetupLswId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preSkeletonAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preSkeletonAdapter));
            ara::core::Result<ConstructionToken> preResult(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            preResult.EmplaceError(errorcode);
            return preResult;
        }
    }

    virtual ~NrmCenterServiceInterfaceSkeleton()
    {
        StopOfferService();
    }

    void OfferService()
    {
        skeletonAdapter->RegisterMethod(&NrmCenterServiceInterfaceSkeleton::GetCanAllStat, *this, methods::GetCanAllStatId);
        skeletonAdapter->RegisterMethod(&NrmCenterServiceInterfaceSkeleton::GetCanConfig, *this, methods::GetCanConfigId);
        skeletonAdapter->RegisterMethod(&NrmCenterServiceInterfaceSkeleton::GetCanDevName, *this, methods::GetCanDevNameId);
        skeletonAdapter->RegisterMethod(&NrmCenterServiceInterfaceSkeleton::GetDomainNetTopConfig, *this, methods::GetDomainNetTopConfigId);
        skeletonAdapter->RegisterMethod(&NrmCenterServiceInterfaceSkeleton::GetEthAllStat, *this, methods::GetEthAllStatId);
        skeletonAdapter->RegisterMethod(&NrmCenterServiceInterfaceSkeleton::GetNetStat, *this, methods::GetNetStatId);
        skeletonAdapter->RegisterMethod(&NrmCenterServiceInterfaceSkeleton::GetPanelNetTopConfig, *this, methods::GetPanelNetTopConfigId);
        skeletonAdapter->RegisterMethod(&NrmCenterServiceInterfaceSkeleton::GetSensorEthDevName, *this, methods::GetSensorEthDevNameId);
        skeletonAdapter->RegisterMethod(&NrmCenterServiceInterfaceSkeleton::GetUartDevName, *this, methods::GetUartDevNameId);
        skeletonAdapter->RegisterMethod(&NrmCenterServiceInterfaceSkeleton::ReportInitLswStatus, *this, methods::ReportInitLswStatusId);
        skeletonAdapter->RegisterMethod(&NrmCenterServiceInterfaceSkeleton::SetupLsw, *this, methods::SetupLswId);
        skeletonAdapter->OfferService();
    }
    void StopOfferService()
    {
        skeletonAdapter->StopOfferService();
    }
    ara::core::Future<bool> ProcessNextMethodCall()
    {
        return skeletonAdapter->ProcessNextMethodCall();
    }
    bool SetMethodThreadNumber(const std::uint16_t& number, const std::uint16_t& queueSize)
    {
        return skeletonAdapter->SetMethodThreadNumber(number, queueSize);
    }
    virtual ara::core::Future<GetCanAllStatOutput> GetCanAllStat() = 0;
    virtual ara::core::Future<GetCanConfigOutput> GetCanConfig(const ::String& portName) = 0;
    virtual ara::core::Future<GetCanDevNameOutput> GetCanDevName(const ::String& portName) = 0;
    virtual ara::core::Future<GetDomainNetTopConfigOutput> GetDomainNetTopConfig() = 0;
    virtual ara::core::Future<GetEthAllStatOutput> GetEthAllStat() = 0;
    virtual ara::core::Future<GetNetStatOutput> GetNetStat() = 0;
    virtual ara::core::Future<GetPanelNetTopConfigOutput> GetPanelNetTopConfig() = 0;
    virtual ara::core::Future<GetSensorEthDevNameOutput> GetSensorEthDevName(const ::String& portName) = 0;
    virtual ara::core::Future<GetUartDevNameOutput> GetUartDevName(const ::String& portName) = 0;
    virtual ara::core::Future<ReportInitLswStatusOutput> ReportInitLswStatus() = 0;
    virtual ara::core::Future<SetupLswOutput> SetupLsw() = 0;

    methods::GetCanAllStatHandle GetCanAllStatHandle;
    methods::GetCanConfigHandle GetCanConfigHandle;
    methods::GetCanDevNameHandle GetCanDevNameHandle;
    methods::GetDomainNetTopConfigHandle GetDomainNetTopConfigHandle;
    methods::GetEthAllStatHandle GetEthAllStatHandle;
    methods::GetNetStatHandle GetNetStatHandle;
    methods::GetPanelNetTopConfigHandle GetPanelNetTopConfigHandle;
    methods::GetSensorEthDevNameHandle GetSensorEthDevNameHandle;
    methods::GetUartDevNameHandle GetUartDevNameHandle;
    methods::ReportInitLswStatusHandle ReportInitLswStatusHandle;
    methods::SetupLswHandle SetupLswHandle;
};
} // namespace skeleton
} // namespace nrmc
} // namespace nrm
} // namespace mdc

#endif // MDC_NRM_NRMC_NRMCENTERSERVICEINTERFACE_SKELETON_H
