/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_NRM_IMPL_TYPE_PORTCONFIGOBJ_H
#define MDC_NRM_IMPL_TYPE_PORTCONFIGOBJ_H
#include <cfloat>
#include <cmath>
#include "impl_type_string.h"
#include "impl_type_uint16.h"
#include "impl_type_stringlist.h"

namespace mdc {
namespace nrm {
struct PortConfigObj {
    ::String portName;
    ::UInt16 portScope;
    ::StringList vlanIntfs;
    ::UInt16 portType;

    static bool IsPlane()
    {
        return false;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(portName);
        fun(portScope);
        fun(vlanIntfs);
        fun(portType);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(portName);
        fun(portScope);
        fun(vlanIntfs);
        fun(portType);
    }

    bool operator == (const ::mdc::nrm::PortConfigObj& t) const
    {
        return (portName == t.portName) && (portScope == t.portScope) && (vlanIntfs == t.vlanIntfs) && (portType == t.portType);
    }
};
} // namespace nrm
} // namespace mdc


#endif // MDC_NRM_IMPL_TYPE_PORTCONFIGOBJ_H
