/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_NRM_IMPL_TYPE_PORTCONFIGLIST_H
#define MDC_NRM_IMPL_TYPE_PORTCONFIGLIST_H
#include "ara/core/vector.h"
#include "mdc/nrm/impl_type_portconfigobj.h"

namespace mdc {
namespace nrm {
using PortConfigList = ara::core::Vector<mdc::nrm::PortConfigObj>;
} // namespace nrm
} // namespace mdc


#endif // MDC_NRM_IMPL_TYPE_PORTCONFIGLIST_H
