/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SWM_SOFTWAREMANAGERSERVICEINTERFACE_SKELETON_H
#define MDC_SWM_SOFTWAREMANAGERSERVICEINTERFACE_SKELETON_H

#include "ara/com/internal/skeleton/skeleton_adapter.h"
#include "ara/com/internal/skeleton/event_adapter.h"
#include "ara/com/internal/skeleton/field_adapter.h"
#include "ara/com/internal/skeleton/method_adapter.h"
#include "mdc/swm/softwaremanagerserviceinterface_common.h"
#include <cstdint>
#include <cfloat>
#include <cmath>

namespace mdc {
namespace swm {
namespace skeleton {
namespace events
{
}

namespace methods
{
    using GetFinggerPrintHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetHistoryHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetHistoryInfoHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetSwClusterInfoHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetVersionInfoHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using SetFinggerPrintHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetSpecificVersionInfoHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using RefreshVersionHandle = ara::com::internal::skeleton::method::MethodAdapter;
    static constexpr ara::com::internal::EntityId GetFinggerPrintId = 10835; //GetFinggerPrint_method_hash
    static constexpr ara::com::internal::EntityId GetHistoryId = 23435; //GetHistory_method_hash
    static constexpr ara::com::internal::EntityId GetHistoryInfoId = 4639; //GetHistoryInfo_method_hash
    static constexpr ara::com::internal::EntityId GetSwClusterInfoId = 25213; //GetSwClusterInfo_method_hash
    static constexpr ara::com::internal::EntityId GetVersionInfoId = 26771; //GetVersionInfo_method_hash
    static constexpr ara::com::internal::EntityId SetFinggerPrintId = 22609; //SetFinggerPrint_method_hash
    static constexpr ara::com::internal::EntityId GetSpecificVersionInfoId = 32010; //GetSpecificVersionInfo_method_hash
    static constexpr ara::com::internal::EntityId RefreshVersionId = 11944; //RefreshVersion_method_hash
}

namespace fields
{
}

class SoftwareManagerServiceInterfaceSkeleton {
private:
    std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeletonAdapter;
    void ConstructSkeleton(ara::com::MethodCallProcessingMode mode)
    {
        if (mode == ara::com::MethodCallProcessingMode::kEvent) {
            if (!(skeletonAdapter->SetMethodThreadNumber(skeletonAdapter->GetMethodThreadNumber(8), 1024))) {
#ifndef NOT_SUPPORT_EXCEPTIONS
                ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                throw ara::com::ComException(std::move(errorcode));
#else
                std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
            }
        }
        ara::core::Result<void> resultGetFinggerPrint = skeletonAdapter->InitializeMethod<ara::core::Future<GetFinggerPrintOutput>>(methods::GetFinggerPrintId);
        ThrowError(resultGetFinggerPrint);
        ara::core::Result<void> resultGetHistory = skeletonAdapter->InitializeMethod<ara::core::Future<GetHistoryOutput>>(methods::GetHistoryId);
        ThrowError(resultGetHistory);
        ara::core::Result<void> resultGetHistoryInfo = skeletonAdapter->InitializeMethod<ara::core::Future<GetHistoryInfoOutput>>(methods::GetHistoryInfoId);
        ThrowError(resultGetHistoryInfo);
        ara::core::Result<void> resultGetSwClusterInfo = skeletonAdapter->InitializeMethod<ara::core::Future<GetSwClusterInfoOutput>>(methods::GetSwClusterInfoId);
        ThrowError(resultGetSwClusterInfo);
        ara::core::Result<void> resultGetVersionInfo = skeletonAdapter->InitializeMethod<ara::core::Future<GetVersionInfoOutput>>(methods::GetVersionInfoId);
        ThrowError(resultGetVersionInfo);
        ara::core::Result<void> resultSetFinggerPrint = skeletonAdapter->InitializeMethod<ara::core::Future<SetFinggerPrintOutput>>(methods::SetFinggerPrintId);
        ThrowError(resultSetFinggerPrint);
        ara::core::Result<void> resultGetSpecificVersionInfo = skeletonAdapter->InitializeMethod<ara::core::Future<GetSpecificVersionInfoOutput>>(methods::GetSpecificVersionInfoId);
        ThrowError(resultGetSpecificVersionInfo);
        ara::core::Result<void> resultRefreshVersion = skeletonAdapter->InitializeMethod<ara::core::Future<RefreshVersionOutput>>(methods::RefreshVersionId);
        ThrowError(resultRefreshVersion);
    }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }
public:
    
    struct GetFinggerPrintOutput {
        ::mdc::swm::FinggerPrintType fingerPrint;
        ::Int32 ret;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(fingerPrint);
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(fingerPrint);
            fun(ret);
        }
    
        bool operator == (const GetFinggerPrintOutput& t) const
        {
            return (fingerPrint == t.fingerPrint) && (ret == t.ret);
        }
    };
    
    
    struct GetHistoryOutput {
        ::mdc::swm::GetHistoryVectorType history;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(history);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(history);
        }
    
        bool operator == (const GetHistoryOutput& t) const
        {
            return (history == t.history);
        }
    };
    
    
    struct GetHistoryInfoOutput {
        ::mdc::swm::SoftwarePackageHistoryRecordVector record;
        ::Int32 ret;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(record);
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(record);
            fun(ret);
        }
    
        bool operator == (const GetHistoryInfoOutput& t) const
        {
            return (record == t.record) && (ret == t.ret);
        }
    };
    
    
    struct GetSwClusterInfoOutput {
        ::mdc::swm::SwClusterInfoVectorType SwInfo;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(SwInfo);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(SwInfo);
        }
    
        bool operator == (const GetSwClusterInfoOutput& t) const
        {
            return (SwInfo == t.SwInfo);
        }
    };
    
    
    struct GetVersionInfoOutput {
        ::mdc::swm::SysVersion SysVersion;
        ::mdc::swm::Response ret;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(SysVersion);
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(SysVersion);
            fun(ret);
        }
    
        bool operator == (const GetVersionInfoOutput& t) const
        {
            return (SysVersion == t.SysVersion) && (ret == t.ret);
        }
    };
    
    
    struct SetFinggerPrintOutput {
        ::Int32 ret;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ret);
        }
    
        bool operator == (const SetFinggerPrintOutput& t) const
        {
            return (ret == t.ret);
        }
    };
    
    
    struct GetSpecificVersionInfoOutput {
        ::mdc::swm::VersionItem versionItem;
        ::mdc::swm::Response ret;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(versionItem);
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(versionItem);
            fun(ret);
        }
    
        bool operator == (const GetSpecificVersionInfoOutput& t) const
        {
            return (versionItem == t.versionItem) && (ret == t.ret);
        }
    };
    
    
    struct RefreshVersionOutput {
        ::Int32 ret;
    
        static bool IsPlane()
        {
            return true;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ret);
        }
    
        bool operator == (const RefreshVersionOutput& t) const
        {
            return (ret == t.ret);
        }
    };
    
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeleton)
            : ptr(std::move(skeleton)) {}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> GetSkeletonAdapter() 
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> ptr;
    };
    explicit SoftwareManagerServiceInterfaceSkeleton(ara::com::InstanceIdentifier instanceId,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        : skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::swm::SoftwareManagerServiceInterface::ServiceIdentifier, instanceId, mode)),
          GetFinggerPrintHandle(skeletonAdapter->GetSkeleton(), methods::GetFinggerPrintId),
          GetHistoryHandle(skeletonAdapter->GetSkeleton(), methods::GetHistoryId),
          GetHistoryInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetHistoryInfoId),
          GetSwClusterInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetSwClusterInfoId),
          GetVersionInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetVersionInfoId),
          SetFinggerPrintHandle(skeletonAdapter->GetSkeleton(), methods::SetFinggerPrintId),
          GetSpecificVersionInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetSpecificVersionInfoId),
          RefreshVersionHandle(skeletonAdapter->GetSkeleton(), methods::RefreshVersionId){
        ConstructSkeleton(mode);
    }

    explicit SoftwareManagerServiceInterfaceSkeleton(ara::core::InstanceSpecifier instanceSpec,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::swm::SoftwareManagerServiceInterface::ServiceIdentifier, instanceSpec, mode)),
          GetFinggerPrintHandle(skeletonAdapter->GetSkeleton(), methods::GetFinggerPrintId),
          GetHistoryHandle(skeletonAdapter->GetSkeleton(), methods::GetHistoryId),
          GetHistoryInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetHistoryInfoId),
          GetSwClusterInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetSwClusterInfoId),
          GetVersionInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetVersionInfoId),
          SetFinggerPrintHandle(skeletonAdapter->GetSkeleton(), methods::SetFinggerPrintId),
          GetSpecificVersionInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetSpecificVersionInfoId),
          RefreshVersionHandle(skeletonAdapter->GetSkeleton(), methods::RefreshVersionId){
        ConstructSkeleton(mode);
    }

    explicit SoftwareManagerServiceInterfaceSkeleton(ara::com::InstanceIdentifierContainer instanceContainer,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::swm::SoftwareManagerServiceInterface::ServiceIdentifier, instanceContainer, mode)),
          GetFinggerPrintHandle(skeletonAdapter->GetSkeleton(), methods::GetFinggerPrintId),
          GetHistoryHandle(skeletonAdapter->GetSkeleton(), methods::GetHistoryId),
          GetHistoryInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetHistoryInfoId),
          GetSwClusterInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetSwClusterInfoId),
          GetVersionInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetVersionInfoId),
          SetFinggerPrintHandle(skeletonAdapter->GetSkeleton(), methods::SetFinggerPrintId),
          GetSpecificVersionInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetSpecificVersionInfoId),
          RefreshVersionHandle(skeletonAdapter->GetSkeleton(), methods::RefreshVersionId){
        ConstructSkeleton(mode);
    }

    SoftwareManagerServiceInterfaceSkeleton(const SoftwareManagerServiceInterfaceSkeleton&) = delete;
    SoftwareManagerServiceInterfaceSkeleton& operator=(const SoftwareManagerServiceInterfaceSkeleton&) = delete;

    SoftwareManagerServiceInterfaceSkeleton(SoftwareManagerServiceInterfaceSkeleton&& other) = default;
    SoftwareManagerServiceInterfaceSkeleton& operator=(SoftwareManagerServiceInterfaceSkeleton&& other) = default;
    SoftwareManagerServiceInterfaceSkeleton(ConstructionToken&& token) noexcept 
        : skeletonAdapter(token.GetSkeletonAdapter()),
          GetFinggerPrintHandle(skeletonAdapter->GetSkeleton(), methods::GetFinggerPrintId),
          GetHistoryHandle(skeletonAdapter->GetSkeleton(), methods::GetHistoryId),
          GetHistoryInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetHistoryInfoId),
          GetSwClusterInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetSwClusterInfoId),
          GetVersionInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetVersionInfoId),
          SetFinggerPrintHandle(skeletonAdapter->GetSkeleton(), methods::SetFinggerPrintId),
          GetSpecificVersionInfoHandle(skeletonAdapter->GetSkeleton(), methods::GetSpecificVersionInfoId),
          RefreshVersionHandle(skeletonAdapter->GetSkeleton(), methods::RefreshVersionId){
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifier instanceId,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::swm::SoftwareManagerServiceInterface::ServiceIdentifier, instanceId, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::core::InstanceSpecifier instanceSpec,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::swm::SoftwareManagerServiceInterface::ServiceIdentifier, instanceSpec, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifierContainer instanceIdContainer,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::swm::SoftwareManagerServiceInterface::ServiceIdentifier, instanceIdContainer, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> PreConstructResult(
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter>& preSkeletonAdapter, ara::com::MethodCallProcessingMode mode)
    {
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            if (mode == ara::com::MethodCallProcessingMode::kEvent) {
                if(!preSkeletonAdapter->SetMethodThreadNumber(preSkeletonAdapter->GetMethodThreadNumber(8), 1024)) {
                    result = false;
                    ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                    initResult.EmplaceError(errorcode);
                    break;
                }
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetFinggerPrintOutput>>(methods::GetFinggerPrintId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetHistoryOutput>>(methods::GetHistoryId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetHistoryInfoOutput>>(methods::GetHistoryInfoId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetSwClusterInfoOutput>>(methods::GetSwClusterInfoId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetVersionInfoOutput>>(methods::GetVersionInfoId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<SetFinggerPrintOutput>>(methods::SetFinggerPrintId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetSpecificVersionInfoOutput>>(methods::GetSpecificVersionInfoId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<RefreshVersionOutput>>(methods::RefreshVersionId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preSkeletonAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preSkeletonAdapter));
            ara::core::Result<ConstructionToken> preResult(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            preResult.EmplaceError(errorcode);
            return preResult;
        }
    }

    virtual ~SoftwareManagerServiceInterfaceSkeleton()
    {
        StopOfferService();
    }

    void OfferService()
    {
        skeletonAdapter->RegisterMethod(&SoftwareManagerServiceInterfaceSkeleton::GetFinggerPrint, *this, methods::GetFinggerPrintId);
        skeletonAdapter->RegisterMethod(&SoftwareManagerServiceInterfaceSkeleton::GetHistory, *this, methods::GetHistoryId);
        skeletonAdapter->RegisterMethod(&SoftwareManagerServiceInterfaceSkeleton::GetHistoryInfo, *this, methods::GetHistoryInfoId);
        skeletonAdapter->RegisterMethod(&SoftwareManagerServiceInterfaceSkeleton::GetSwClusterInfo, *this, methods::GetSwClusterInfoId);
        skeletonAdapter->RegisterMethod(&SoftwareManagerServiceInterfaceSkeleton::GetVersionInfo, *this, methods::GetVersionInfoId);
        skeletonAdapter->RegisterMethod(&SoftwareManagerServiceInterfaceSkeleton::SetFinggerPrint, *this, methods::SetFinggerPrintId);
        skeletonAdapter->RegisterMethod(&SoftwareManagerServiceInterfaceSkeleton::GetSpecificVersionInfo, *this, methods::GetSpecificVersionInfoId);
        skeletonAdapter->RegisterMethod(&SoftwareManagerServiceInterfaceSkeleton::RefreshVersion, *this, methods::RefreshVersionId);
        skeletonAdapter->OfferService();
    }
    void StopOfferService()
    {
        skeletonAdapter->StopOfferService();
    }
    ara::core::Future<bool> ProcessNextMethodCall()
    {
        return skeletonAdapter->ProcessNextMethodCall();
    }
    bool SetMethodThreadNumber(const std::uint16_t& number, const std::uint16_t& queueSize)
    {
        return skeletonAdapter->SetMethodThreadNumber(number, queueSize);
    }
    virtual ara::core::Future<GetFinggerPrintOutput> GetFinggerPrint() = 0;
    virtual ara::core::Future<GetHistoryOutput> GetHistory(const ::UInt64& timestampGE, const ::UInt64& timestampLT) = 0;
    virtual ara::core::Future<GetHistoryInfoOutput> GetHistoryInfo() = 0;
    virtual ara::core::Future<GetSwClusterInfoOutput> GetSwClusterInfo() = 0;
    virtual ara::core::Future<GetVersionInfoOutput> GetVersionInfo() = 0;
    virtual ara::core::Future<SetFinggerPrintOutput> SetFinggerPrint(const ::mdc::swm::FinggerPrintType& fingerPrint) = 0;
    virtual ara::core::Future<GetSpecificVersionInfoOutput> GetSpecificVersionInfo(const ::String& location, const ::String& name) = 0;
    virtual ara::core::Future<RefreshVersionOutput> RefreshVersion(const ::Boolean& isSync) = 0;

    methods::GetFinggerPrintHandle GetFinggerPrintHandle;
    methods::GetHistoryHandle GetHistoryHandle;
    methods::GetHistoryInfoHandle GetHistoryInfoHandle;
    methods::GetSwClusterInfoHandle GetSwClusterInfoHandle;
    methods::GetVersionInfoHandle GetVersionInfoHandle;
    methods::SetFinggerPrintHandle SetFinggerPrintHandle;
    methods::GetSpecificVersionInfoHandle GetSpecificVersionInfoHandle;
    methods::RefreshVersionHandle RefreshVersionHandle;
};
} // namespace skeleton
} // namespace swm
} // namespace mdc

#endif // MDC_SWM_SOFTWAREMANAGERSERVICEINTERFACE_SKELETON_H
