/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_SWM_UPDATEMANAGERSERVICEINTERFACE_SKELETON_H
#define MDC_SWM_UPDATEMANAGERSERVICEINTERFACE_SKELETON_H

#include "ara/com/internal/skeleton/skeleton_adapter.h"
#include "ara/com/internal/skeleton/event_adapter.h"
#include "ara/com/internal/skeleton/field_adapter.h"
#include "ara/com/internal/skeleton/method_adapter.h"
#include "mdc/swm/updatemanagerserviceinterface_common.h"
#include <cstdint>
#include <cfloat>
#include <cmath>

namespace mdc {
namespace swm {
namespace skeleton {
namespace events
{
}

namespace methods
{
    using ActivateHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using FinishHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetActivationProgressHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetSwProcessProgressHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetUpdatePreCheckProgressHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetUpdatePreCheckResultHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetUpdateProgressHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using GetUpdateStatusHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using ProcessSwPackageHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using UpdateHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using UpdatePreCheckHandle = ara::com::internal::skeleton::method::MethodAdapter;
    static constexpr ara::com::internal::EntityId ActivateId = 4102; //Activate_method_hash
    static constexpr ara::com::internal::EntityId FinishId = 43324; //Finish_method_hash
    static constexpr ara::com::internal::EntityId GetActivationProgressId = 29393; //GetActivationProgress_method_hash
    static constexpr ara::com::internal::EntityId GetSwProcessProgressId = 36314; //GetSwProcessProgress_method_hash
    static constexpr ara::com::internal::EntityId GetUpdatePreCheckProgressId = 43431; //GetUpdatePreCheckProgress_method_hash
    static constexpr ara::com::internal::EntityId GetUpdatePreCheckResultId = 45144; //GetUpdatePreCheckResult_method_hash
    static constexpr ara::com::internal::EntityId GetUpdateProgressId = 34795; //GetUpdateProgress_method_hash
    static constexpr ara::com::internal::EntityId GetUpdateStatusId = 61203; //GetUpdateStatus_method_hash
    static constexpr ara::com::internal::EntityId ProcessSwPackageId = 16077; //ProcessSwPackage_method_hash
    static constexpr ara::com::internal::EntityId UpdateId = 64985; //Update_method_hash
    static constexpr ara::com::internal::EntityId UpdatePreCheckId = 2020; //UpdatePreCheck_method_hash
}

namespace fields
{
}

class UpdateManagerServiceInterfaceSkeleton {
private:
    std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeletonAdapter;
    void ConstructSkeleton(ara::com::MethodCallProcessingMode mode)
    {
        if (mode == ara::com::MethodCallProcessingMode::kEvent) {
            if (!(skeletonAdapter->SetMethodThreadNumber(skeletonAdapter->GetMethodThreadNumber(11), 1024))) {
#ifndef NOT_SUPPORT_EXCEPTIONS
                ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                throw ara::com::ComException(std::move(errorcode));
#else
                std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
            }
        }
        ara::core::Result<void> resultActivate = skeletonAdapter->InitializeMethod<ara::core::Future<ActivateOutput>>(methods::ActivateId);
        ThrowError(resultActivate);
        ara::core::Result<void> resultFinish = skeletonAdapter->InitializeMethod<ara::core::Future<FinishOutput>>(methods::FinishId);
        ThrowError(resultFinish);
        ara::core::Result<void> resultGetActivationProgress = skeletonAdapter->InitializeMethod<ara::core::Future<GetActivationProgressOutput>>(methods::GetActivationProgressId);
        ThrowError(resultGetActivationProgress);
        ara::core::Result<void> resultGetSwProcessProgress = skeletonAdapter->InitializeMethod<ara::core::Future<GetSwProcessProgressOutput>>(methods::GetSwProcessProgressId);
        ThrowError(resultGetSwProcessProgress);
        ara::core::Result<void> resultGetUpdatePreCheckProgress = skeletonAdapter->InitializeMethod<ara::core::Future<GetUpdatePreCheckProgressOutput>>(methods::GetUpdatePreCheckProgressId);
        ThrowError(resultGetUpdatePreCheckProgress);
        ara::core::Result<void> resultGetUpdatePreCheckResult = skeletonAdapter->InitializeMethod<ara::core::Future<GetUpdatePreCheckResultOutput>>(methods::GetUpdatePreCheckResultId);
        ThrowError(resultGetUpdatePreCheckResult);
        ara::core::Result<void> resultGetUpdateProgress = skeletonAdapter->InitializeMethod<ara::core::Future<GetUpdateProgressOutput>>(methods::GetUpdateProgressId);
        ThrowError(resultGetUpdateProgress);
        ara::core::Result<void> resultGetUpdateStatus = skeletonAdapter->InitializeMethod<ara::core::Future<GetUpdateStatusOutput>>(methods::GetUpdateStatusId);
        ThrowError(resultGetUpdateStatus);
        ara::core::Result<void> resultProcessSwPackage = skeletonAdapter->InitializeMethod<ara::core::Future<ProcessSwPackageOutput>>(methods::ProcessSwPackageId);
        ThrowError(resultProcessSwPackage);
        ara::core::Result<void> resultUpdate = skeletonAdapter->InitializeMethod<ara::core::Future<UpdateOutput>>(methods::UpdateId);
        ThrowError(resultUpdate);
        ara::core::Result<void> resultUpdatePreCheck = skeletonAdapter->InitializeMethod<ara::core::Future<UpdatePreCheckOutput>>(methods::UpdatePreCheckId);
        ThrowError(resultUpdatePreCheck);
    }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }
public:
    
    struct ActivateOutput {
        ::mdc::swm::Response ret;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ret);
        }
    
        bool operator == (const ActivateOutput& t) const
        {
            return (ret == t.ret);
        }
    };
    
    
    struct FinishOutput {
        ::mdc::swm::Response ret;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ret);
        }
    
        bool operator == (const FinishOutput& t) const
        {
            return (ret == t.ret);
        }
    };
    
    
    struct GetActivationProgressOutput {
        ::UInt8 process;
        ::Int32 errcode;
        ::String message;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(process);
            fun(errcode);
            fun(message);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(process);
            fun(errcode);
            fun(message);
        }
    
        bool operator == (const GetActivationProgressOutput& t) const
        {
            return (process == t.process) && (errcode == t.errcode) && (message == t.message);
        }
    };
    
    
    struct GetSwProcessProgressOutput {
        ::UInt8 progress;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(progress);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(progress);
        }
    
        bool operator == (const GetSwProcessProgressOutput& t) const
        {
            return (progress == t.progress);
        }
    };
    
    
    struct GetUpdatePreCheckProgressOutput {
        ::UInt8 process;
        ::Int32 errcode;
        ::String message;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(process);
            fun(errcode);
            fun(message);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(process);
            fun(errcode);
            fun(message);
        }
    
        bool operator == (const GetUpdatePreCheckProgressOutput& t) const
        {
            return (process == t.process) && (errcode == t.errcode) && (message == t.message);
        }
    };
    
    
    struct GetUpdatePreCheckResultOutput {
        ::mdc::swm::PreCheckResult ret;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ret);
        }
    
        bool operator == (const GetUpdatePreCheckResultOutput& t) const
        {
            return (ret == t.ret);
        }
    };
    
    
    struct GetUpdateProgressOutput {
        ::UInt8 process;
        ::Int32 errcode;
        ::String message;
        ::mdc::swm::ItemStateVector subItems;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(process);
            fun(errcode);
            fun(message);
            fun(subItems);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(process);
            fun(errcode);
            fun(message);
            fun(subItems);
        }
    
        bool operator == (const GetUpdateProgressOutput& t) const
        {
            return (process == t.process) && (errcode == t.errcode) && (message == t.message) && (subItems == t.subItems);
        }
    };
    
    
    struct GetUpdateStatusOutput {
        ::mdc::swm::PackageManagerStatusType Status;
    
        static bool IsPlane()
        {
            return true;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(Status);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(Status);
        }
    
        bool operator == (const GetUpdateStatusOutput& t) const
        {
            return (Status == t.Status);
        }
    };
    
    
    struct ProcessSwPackageOutput {
        ::Int32 ret;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ret);
        }
    
        bool operator == (const ProcessSwPackageOutput& t) const
        {
            return (ret == t.ret);
        }
    };
    
    
    struct UpdateOutput {
        ::mdc::swm::Response ret;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ret);
        }
    
        bool operator == (const UpdateOutput& t) const
        {
            return (ret == t.ret);
        }
    };
    
    
    struct UpdatePreCheckOutput {
        ::mdc::swm::Response ret;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(ret);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(ret);
        }
    
        bool operator == (const UpdatePreCheckOutput& t) const
        {
            return (ret == t.ret);
        }
    };
    
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeleton)
            : ptr(std::move(skeleton)) {}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> GetSkeletonAdapter() 
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> ptr;
    };
    explicit UpdateManagerServiceInterfaceSkeleton(ara::com::InstanceIdentifier instanceId,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        : skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::swm::UpdateManagerServiceInterface::ServiceIdentifier, instanceId, mode)),
          ActivateHandle(skeletonAdapter->GetSkeleton(), methods::ActivateId),
          FinishHandle(skeletonAdapter->GetSkeleton(), methods::FinishId),
          GetActivationProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetActivationProgressId),
          GetSwProcessProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetSwProcessProgressId),
          GetUpdatePreCheckProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdatePreCheckProgressId),
          GetUpdatePreCheckResultHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdatePreCheckResultId),
          GetUpdateProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdateProgressId),
          GetUpdateStatusHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdateStatusId),
          ProcessSwPackageHandle(skeletonAdapter->GetSkeleton(), methods::ProcessSwPackageId),
          UpdateHandle(skeletonAdapter->GetSkeleton(), methods::UpdateId),
          UpdatePreCheckHandle(skeletonAdapter->GetSkeleton(), methods::UpdatePreCheckId){
        ConstructSkeleton(mode);
    }

    explicit UpdateManagerServiceInterfaceSkeleton(ara::core::InstanceSpecifier instanceSpec,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::swm::UpdateManagerServiceInterface::ServiceIdentifier, instanceSpec, mode)),
          ActivateHandle(skeletonAdapter->GetSkeleton(), methods::ActivateId),
          FinishHandle(skeletonAdapter->GetSkeleton(), methods::FinishId),
          GetActivationProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetActivationProgressId),
          GetSwProcessProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetSwProcessProgressId),
          GetUpdatePreCheckProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdatePreCheckProgressId),
          GetUpdatePreCheckResultHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdatePreCheckResultId),
          GetUpdateProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdateProgressId),
          GetUpdateStatusHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdateStatusId),
          ProcessSwPackageHandle(skeletonAdapter->GetSkeleton(), methods::ProcessSwPackageId),
          UpdateHandle(skeletonAdapter->GetSkeleton(), methods::UpdateId),
          UpdatePreCheckHandle(skeletonAdapter->GetSkeleton(), methods::UpdatePreCheckId){
        ConstructSkeleton(mode);
    }

    explicit UpdateManagerServiceInterfaceSkeleton(ara::com::InstanceIdentifierContainer instanceContainer,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::mdc::swm::UpdateManagerServiceInterface::ServiceIdentifier, instanceContainer, mode)),
          ActivateHandle(skeletonAdapter->GetSkeleton(), methods::ActivateId),
          FinishHandle(skeletonAdapter->GetSkeleton(), methods::FinishId),
          GetActivationProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetActivationProgressId),
          GetSwProcessProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetSwProcessProgressId),
          GetUpdatePreCheckProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdatePreCheckProgressId),
          GetUpdatePreCheckResultHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdatePreCheckResultId),
          GetUpdateProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdateProgressId),
          GetUpdateStatusHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdateStatusId),
          ProcessSwPackageHandle(skeletonAdapter->GetSkeleton(), methods::ProcessSwPackageId),
          UpdateHandle(skeletonAdapter->GetSkeleton(), methods::UpdateId),
          UpdatePreCheckHandle(skeletonAdapter->GetSkeleton(), methods::UpdatePreCheckId){
        ConstructSkeleton(mode);
    }

    UpdateManagerServiceInterfaceSkeleton(const UpdateManagerServiceInterfaceSkeleton&) = delete;
    UpdateManagerServiceInterfaceSkeleton& operator=(const UpdateManagerServiceInterfaceSkeleton&) = delete;

    UpdateManagerServiceInterfaceSkeleton(UpdateManagerServiceInterfaceSkeleton&& other) = default;
    UpdateManagerServiceInterfaceSkeleton& operator=(UpdateManagerServiceInterfaceSkeleton&& other) = default;
    UpdateManagerServiceInterfaceSkeleton(ConstructionToken&& token) noexcept 
        : skeletonAdapter(token.GetSkeletonAdapter()),
          ActivateHandle(skeletonAdapter->GetSkeleton(), methods::ActivateId),
          FinishHandle(skeletonAdapter->GetSkeleton(), methods::FinishId),
          GetActivationProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetActivationProgressId),
          GetSwProcessProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetSwProcessProgressId),
          GetUpdatePreCheckProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdatePreCheckProgressId),
          GetUpdatePreCheckResultHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdatePreCheckResultId),
          GetUpdateProgressHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdateProgressId),
          GetUpdateStatusHandle(skeletonAdapter->GetSkeleton(), methods::GetUpdateStatusId),
          ProcessSwPackageHandle(skeletonAdapter->GetSkeleton(), methods::ProcessSwPackageId),
          UpdateHandle(skeletonAdapter->GetSkeleton(), methods::UpdateId),
          UpdatePreCheckHandle(skeletonAdapter->GetSkeleton(), methods::UpdatePreCheckId){
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifier instanceId,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::swm::UpdateManagerServiceInterface::ServiceIdentifier, instanceId, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::core::InstanceSpecifier instanceSpec,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::swm::UpdateManagerServiceInterface::ServiceIdentifier, instanceSpec, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifierContainer instanceIdContainer,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::mdc::swm::UpdateManagerServiceInterface::ServiceIdentifier, instanceIdContainer, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> PreConstructResult(
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter>& preSkeletonAdapter, ara::com::MethodCallProcessingMode mode)
    {
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            if (mode == ara::com::MethodCallProcessingMode::kEvent) {
                if(!preSkeletonAdapter->SetMethodThreadNumber(preSkeletonAdapter->GetMethodThreadNumber(11), 1024)) {
                    result = false;
                    ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                    initResult.EmplaceError(errorcode);
                    break;
                }
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<ActivateOutput>>(methods::ActivateId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<FinishOutput>>(methods::FinishId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetActivationProgressOutput>>(methods::GetActivationProgressId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetSwProcessProgressOutput>>(methods::GetSwProcessProgressId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetUpdatePreCheckProgressOutput>>(methods::GetUpdatePreCheckProgressId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetUpdatePreCheckResultOutput>>(methods::GetUpdatePreCheckResultId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetUpdateProgressOutput>>(methods::GetUpdateProgressId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<GetUpdateStatusOutput>>(methods::GetUpdateStatusId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<ProcessSwPackageOutput>>(methods::ProcessSwPackageId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<UpdateOutput>>(methods::UpdateId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<UpdatePreCheckOutput>>(methods::UpdatePreCheckId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preSkeletonAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preSkeletonAdapter));
            ara::core::Result<ConstructionToken> preResult(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            preResult.EmplaceError(errorcode);
            return preResult;
        }
    }

    virtual ~UpdateManagerServiceInterfaceSkeleton()
    {
        StopOfferService();
    }

    void OfferService()
    {
        skeletonAdapter->RegisterMethod(&UpdateManagerServiceInterfaceSkeleton::Activate, *this, methods::ActivateId);
        skeletonAdapter->RegisterMethod(&UpdateManagerServiceInterfaceSkeleton::Finish, *this, methods::FinishId);
        skeletonAdapter->RegisterMethod(&UpdateManagerServiceInterfaceSkeleton::GetActivationProgress, *this, methods::GetActivationProgressId);
        skeletonAdapter->RegisterMethod(&UpdateManagerServiceInterfaceSkeleton::GetSwProcessProgress, *this, methods::GetSwProcessProgressId);
        skeletonAdapter->RegisterMethod(&UpdateManagerServiceInterfaceSkeleton::GetUpdatePreCheckProgress, *this, methods::GetUpdatePreCheckProgressId);
        skeletonAdapter->RegisterMethod(&UpdateManagerServiceInterfaceSkeleton::GetUpdatePreCheckResult, *this, methods::GetUpdatePreCheckResultId);
        skeletonAdapter->RegisterMethod(&UpdateManagerServiceInterfaceSkeleton::GetUpdateProgress, *this, methods::GetUpdateProgressId);
        skeletonAdapter->RegisterMethod(&UpdateManagerServiceInterfaceSkeleton::GetUpdateStatus, *this, methods::GetUpdateStatusId);
        skeletonAdapter->RegisterMethod(&UpdateManagerServiceInterfaceSkeleton::ProcessSwPackage, *this, methods::ProcessSwPackageId);
        skeletonAdapter->RegisterMethod(&UpdateManagerServiceInterfaceSkeleton::Update, *this, methods::UpdateId);
        skeletonAdapter->RegisterMethod(&UpdateManagerServiceInterfaceSkeleton::UpdatePreCheck, *this, methods::UpdatePreCheckId);
        skeletonAdapter->OfferService();
    }
    void StopOfferService()
    {
        skeletonAdapter->StopOfferService();
    }
    ara::core::Future<bool> ProcessNextMethodCall()
    {
        return skeletonAdapter->ProcessNextMethodCall();
    }
    bool SetMethodThreadNumber(const std::uint16_t& number, const std::uint16_t& queueSize)
    {
        return skeletonAdapter->SetMethodThreadNumber(number, queueSize);
    }
    virtual ara::core::Future<ActivateOutput> Activate(const ::mdc::swm::SwNameVectorType& preActivate, const ::mdc::swm::SwNameVectorType& verify) = 0;
    virtual ara::core::Future<FinishOutput> Finish() = 0;
    virtual ara::core::Future<GetActivationProgressOutput> GetActivationProgress() = 0;
    virtual ara::core::Future<GetSwProcessProgressOutput> GetSwProcessProgress(const ::mdc::swm::TransferIdType& id) = 0;
    virtual ara::core::Future<GetUpdatePreCheckProgressOutput> GetUpdatePreCheckProgress() = 0;
    virtual ara::core::Future<GetUpdatePreCheckResultOutput> GetUpdatePreCheckResult() = 0;
    virtual ara::core::Future<GetUpdateProgressOutput> GetUpdateProgress() = 0;
    virtual ara::core::Future<GetUpdateStatusOutput> GetUpdateStatus() = 0;
    virtual ara::core::Future<ProcessSwPackageOutput> ProcessSwPackage(const ::mdc::swm::TransferIdType& id) = 0;
    virtual ara::core::Future<UpdateOutput> Update(const ::String& packagePath, const ::Int8& mode) = 0;
    virtual ara::core::Future<UpdatePreCheckOutput> UpdatePreCheck(const ::UInt8& mode, const ::String& packagePath) = 0;

    methods::ActivateHandle ActivateHandle;
    methods::FinishHandle FinishHandle;
    methods::GetActivationProgressHandle GetActivationProgressHandle;
    methods::GetSwProcessProgressHandle GetSwProcessProgressHandle;
    methods::GetUpdatePreCheckProgressHandle GetUpdatePreCheckProgressHandle;
    methods::GetUpdatePreCheckResultHandle GetUpdatePreCheckResultHandle;
    methods::GetUpdateProgressHandle GetUpdateProgressHandle;
    methods::GetUpdateStatusHandle GetUpdateStatusHandle;
    methods::ProcessSwPackageHandle ProcessSwPackageHandle;
    methods::UpdateHandle UpdateHandle;
    methods::UpdatePreCheckHandle UpdatePreCheckHandle;
};
} // namespace skeleton
} // namespace swm
} // namespace mdc

#endif // MDC_SWM_UPDATEMANAGERSERVICEINTERFACE_SKELETON_H
