/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_SM_TRIGGERINOUT_COMMON_H
#define ARA_SM_TRIGGERINOUT_COMMON_H

#include "ara/com/types.h"
#include "ara/sm/impl_type_triggerdatatype.h"
#include "ara/sm/impl_type_functiongroupinfovec.h"
#include "ara/sm/impl_type_statetransitionvec.h"
#include "ara/sm/impl_type_statetransitionresult.h"
#include "ara/sm/impl_type_resetcode.h"
#include "impl_type_string.h"
#include "ara/sm/impl_type_resetcause.h"
#include "ara/sm/impl_type_resetresult.h"

namespace ara {
namespace sm {
class TriggerInOut {
public:
    constexpr TriggerInOut() = default;
    constexpr static ara::com::ServiceIdentifierType ServiceIdentifier = ara::com::ServiceIdentifierType("/HuaweiMDC/PlatformServiceInterface/SmcServiceInterface/TriggerInOut");
    constexpr static ara::com::ServiceVersionType ServiceVersion = ara::com::ServiceVersionType("1.1");
};
} // namespace sm
} // namespace ara

#endif // ARA_SM_TRIGGERINOUT_COMMON_H
