/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef ARA_SM_TRIGGERINOUT_SKELETON_H
#define ARA_SM_TRIGGERINOUT_SKELETON_H

#include "ara/com/internal/skeleton/skeleton_adapter.h"
#include "ara/com/internal/skeleton/event_adapter.h"
#include "ara/com/internal/skeleton/field_adapter.h"
#include "ara/com/internal/skeleton/method_adapter.h"
#include "ara/sm/triggerinout_common.h"
#include <cstdint>
#include <cfloat>
#include <cmath>

namespace ara {
namespace sm {
namespace skeleton {
namespace events
{
}

namespace methods
{
    using AcquireFunctionGroupInfoHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using ProcessSyncRequestHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using ResetSystemHandle = ara::com::internal::skeleton::method::MethodAdapter;
    static constexpr ara::com::internal::EntityId AcquireFunctionGroupInfoId = 36548; //AcquireFunctionGroupInfo_method_hash
    static constexpr ara::com::internal::EntityId ProcessSyncRequestId = 8148; //ProcessSyncRequest_method_hash
    static constexpr ara::com::internal::EntityId ResetSystemId = 43154; //ResetSystem_method_hash
}

namespace fields
{
    using Notifier = ara::com::internal::skeleton::field::FieldAdapter<::ara::sm::TriggerDataType>;
    using Trigger = ara::com::internal::skeleton::field::FieldAdapter<::ara::sm::TriggerDataType>;
    static constexpr ara::com::internal::EntityId NotifierId = 54564; //Notifier_field_hash
    static constexpr ara::com::internal::EntityId NotifierGetterId = 21625; //Notifier_getter_hash
    static constexpr ara::com::internal::EntityId TriggerId = 24507; //Trigger_field_hash
    static constexpr ara::com::internal::EntityId TriggerSetterId = 57439; //Trigger_setter_hash
}

class TriggerInOutSkeleton {
private:
    std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeletonAdapter;
    void ConstructSkeleton(ara::com::MethodCallProcessingMode mode)
    {
        if (mode == ara::com::MethodCallProcessingMode::kEvent) {
            if (!(skeletonAdapter->SetMethodThreadNumber(skeletonAdapter->GetMethodThreadNumber(5), 1024))) {
#ifndef NOT_SUPPORT_EXCEPTIONS
                ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                throw ara::com::ComException(std::move(errorcode));
#else
                std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
            }
        }
        ara::core::Result<void> resultAcquireFunctionGroupInfo = skeletonAdapter->InitializeMethod<ara::core::Future<AcquireFunctionGroupInfoOutput>>(methods::AcquireFunctionGroupInfoId);
        ThrowError(resultAcquireFunctionGroupInfo);
        ara::core::Result<void> resultProcessSyncRequest = skeletonAdapter->InitializeMethod<ara::core::Future<ProcessSyncRequestOutput>>(methods::ProcessSyncRequestId);
        ThrowError(resultProcessSyncRequest);
        ara::core::Result<void> resultResetSystem = skeletonAdapter->InitializeMethod<ara::core::Future<ResetSystemOutput>>(methods::ResetSystemId);
        ThrowError(resultResetSystem);
        Notifier.SetGetterEntityId(fields::NotifierGetterId);
        ara::core::Result<void> resultNotifier = skeletonAdapter->InitializeField<::ara::sm::TriggerDataType>(Notifier);
        ThrowError(resultNotifier);
        Trigger.SetSetterEntityId(fields::TriggerSetterId);
        ara::core::Result<void> resultTrigger = skeletonAdapter->InitializeField<::ara::sm::TriggerDataType>(Trigger);
        ThrowError(resultTrigger);
    }

    void ThrowError(ara::core::Result<void>& result)
    {
        if (!(result.HasValue())) {
#ifndef NOT_SUPPORT_EXCEPTIONS
            ara::core::ErrorCode errorcode(result.Error());
            throw ara::com::ComException(std::move(errorcode));
#else
            std::cerr << "Error: Not support exception, create skeleton failed!"<< std::endl;
#endif
        }
    }
public:
    
    struct AcquireFunctionGroupInfoOutput {
        ::ara::sm::FunctionGroupInfoVec functionGroupInfoVec;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(functionGroupInfoVec);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(functionGroupInfoVec);
        }
    
        bool operator == (const AcquireFunctionGroupInfoOutput& t) const
        {
            return (functionGroupInfoVec == t.functionGroupInfoVec);
        }
    };
    
    
    struct ProcessSyncRequestOutput {
        ::ara::sm::StateTransitionResult result;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(result);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(result);
        }
    
        bool operator == (const ProcessSyncRequestOutput& t) const
        {
            return (result == t.result);
        }
    };
    
    
    struct ResetSystemOutput {
        ::ara::sm::ResetResult resetResult;
    
        static bool IsPlane()
        {
            return false;
        }
    
        using IsEnumerableTag = void;
        template<typename F>
        void enumerate(F& fun)
        {
            fun(resetResult);
        }
    
        template<typename F>
        void enumerate(F& fun) const
        {
            fun(resetResult);
        }
    
        bool operator == (const ResetSystemOutput& t) const
        {
            return (resetResult == t.resetResult);
        }
    };
    
    class ConstructionToken {
    public:
        ConstructionToken(std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> skeleton)
            : ptr(std::move(skeleton)) {}
        ConstructionToken(ConstructionToken&& other) : ptr(std::move(other.ptr)) {}
        ConstructionToken& operator=(ConstructionToken && other)
        {
            if (&other != this) {
                ptr = std::move(other.ptr);
            }
            return *this;
        }
        ConstructionToken(const ConstructionToken&) = delete;
        ConstructionToken& operator = (const ConstructionToken&) = delete;
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> GetSkeletonAdapter() 
        {
            return std::move(ptr);
        }
    private:
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> ptr;
        fields::Notifier Notifier;
        fields::Trigger Trigger;
    };
    explicit TriggerInOutSkeleton(ara::com::InstanceIdentifier instanceId,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        : skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::ara::sm::TriggerInOut::ServiceIdentifier, instanceId, mode)),
          AcquireFunctionGroupInfoHandle(skeletonAdapter->GetSkeleton(), methods::AcquireFunctionGroupInfoId),
          ProcessSyncRequestHandle(skeletonAdapter->GetSkeleton(), methods::ProcessSyncRequestId),
          ResetSystemHandle(skeletonAdapter->GetSkeleton(), methods::ResetSystemId),
          Notifier(skeletonAdapter->GetSkeleton(), fields::NotifierId),
          Trigger(skeletonAdapter->GetSkeleton(), fields::TriggerId) {
        ConstructSkeleton(mode);
    }

    explicit TriggerInOutSkeleton(ara::core::InstanceSpecifier instanceSpec,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::ara::sm::TriggerInOut::ServiceIdentifier, instanceSpec, mode)),
          AcquireFunctionGroupInfoHandle(skeletonAdapter->GetSkeleton(), methods::AcquireFunctionGroupInfoId),
          ProcessSyncRequestHandle(skeletonAdapter->GetSkeleton(), methods::ProcessSyncRequestId),
          ResetSystemHandle(skeletonAdapter->GetSkeleton(), methods::ResetSystemId),
          Notifier(skeletonAdapter->GetSkeleton(), fields::NotifierId),
          Trigger(skeletonAdapter->GetSkeleton(), fields::TriggerId) {
        ConstructSkeleton(mode);
    }

    explicit TriggerInOutSkeleton(ara::com::InstanceIdentifierContainer instanceContainer,
                           ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        :skeletonAdapter(std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(::ara::sm::TriggerInOut::ServiceIdentifier, instanceContainer, mode)),
          AcquireFunctionGroupInfoHandle(skeletonAdapter->GetSkeleton(), methods::AcquireFunctionGroupInfoId),
          ProcessSyncRequestHandle(skeletonAdapter->GetSkeleton(), methods::ProcessSyncRequestId),
          ResetSystemHandle(skeletonAdapter->GetSkeleton(), methods::ResetSystemId),
          Notifier(skeletonAdapter->GetSkeleton(), fields::NotifierId),
          Trigger(skeletonAdapter->GetSkeleton(), fields::TriggerId) {
        ConstructSkeleton(mode);
    }

    TriggerInOutSkeleton(const TriggerInOutSkeleton&) = delete;
    TriggerInOutSkeleton& operator=(const TriggerInOutSkeleton&) = delete;

    TriggerInOutSkeleton(TriggerInOutSkeleton&& other) = default;
    TriggerInOutSkeleton& operator=(TriggerInOutSkeleton&& other) = default;
    TriggerInOutSkeleton(ConstructionToken&& token) noexcept 
        : skeletonAdapter(token.GetSkeletonAdapter()),
          AcquireFunctionGroupInfoHandle(skeletonAdapter->GetSkeleton(), methods::AcquireFunctionGroupInfoId),
          ProcessSyncRequestHandle(skeletonAdapter->GetSkeleton(), methods::ProcessSyncRequestId),
          ResetSystemHandle(skeletonAdapter->GetSkeleton(), methods::ResetSystemId),
          Notifier(skeletonAdapter->GetSkeleton(), fields::NotifierId),
          Trigger(skeletonAdapter->GetSkeleton(), fields::TriggerId) {
        Notifier.SetGetterEntityId(fields::NotifierGetterId);
        Trigger.SetSetterEntityId(fields::TriggerSetterId);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifier instanceId,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::ara::sm::TriggerInOut::ServiceIdentifier, instanceId, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::core::InstanceSpecifier instanceSpec,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::ara::sm::TriggerInOut::ServiceIdentifier, instanceSpec, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> Preconstruct(
        ara::com::InstanceIdentifierContainer instanceIdContainer,
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
    {
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter> preSkeletonAdapter =
            std::make_unique<ara::com::internal::skeleton::SkeletonAdapter>(
                ::ara::sm::TriggerInOut::ServiceIdentifier, instanceIdContainer, mode);
        return PreConstructResult(preSkeletonAdapter, mode);
    }

    static ara::core::Result<ConstructionToken> PreConstructResult(
        std::unique_ptr<ara::com::internal::skeleton::SkeletonAdapter>& preSkeletonAdapter, ara::com::MethodCallProcessingMode mode)
    {
        bool result = true;
        ara::core::Result<void> initResult;
        do {
            if (mode == ara::com::MethodCallProcessingMode::kEvent) {
                if(!preSkeletonAdapter->SetMethodThreadNumber(preSkeletonAdapter->GetMethodThreadNumber(5), 1024)) {
                    result = false;
                    ara::core::ErrorCode errorcode(ara::com::ComErrc::kNetworkBindingFailure);
                    initResult.EmplaceError(errorcode);
                    break;
                }
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<AcquireFunctionGroupInfoOutput>>(methods::AcquireFunctionGroupInfoId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<ProcessSyncRequestOutput>>(methods::ProcessSyncRequestId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            initResult = preSkeletonAdapter->InitializeMethod<ara::core::Future<ResetSystemOutput>>(methods::ResetSystemId);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::Notifier Notifier(preSkeletonAdapter->GetSkeleton(), fields::NotifierId);
            Notifier.SetGetterEntityId(fields::NotifierGetterId);
            initResult = preSkeletonAdapter->InitializeField<::ara::sm::TriggerDataType>(Notifier);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
            fields::Trigger Trigger(preSkeletonAdapter->GetSkeleton(), fields::TriggerId);
            Trigger.SetSetterEntityId(fields::TriggerSetterId);
            initResult = preSkeletonAdapter->InitializeField<::ara::sm::TriggerDataType>(Trigger);
            if (!initResult.HasValue()) {
                result = false;
                break;
            }
        } while(false);
        
        if (result == true) {
            ConstructionToken token(std::move(preSkeletonAdapter));
            return ara::core::Result<ConstructionToken>(std::move(token));
        } else {
            ConstructionToken token(std::move(preSkeletonAdapter));
            ara::core::Result<ConstructionToken> preResult(std::move(token));
            ara::core::ErrorCode errorcode(initResult.Error());
            preResult.EmplaceError(errorcode);
            return preResult;
        }
    }

    virtual ~TriggerInOutSkeleton()
    {
        StopOfferService();
    }

    void OfferService()
    {
        skeletonAdapter->RegisterMethod(&TriggerInOutSkeleton::AcquireFunctionGroupInfo, *this, methods::AcquireFunctionGroupInfoId);
        skeletonAdapter->RegisterMethod(&TriggerInOutSkeleton::ProcessSyncRequest, *this, methods::ProcessSyncRequestId);
        skeletonAdapter->RegisterMethod(&TriggerInOutSkeleton::ResetSystem, *this, methods::ResetSystemId);
        Notifier.VerifyValidity();
        Trigger.VerifyValidity();
        skeletonAdapter->OfferService();
    }
    void StopOfferService()
    {
        skeletonAdapter->StopOfferService();
        Notifier.ResetInitState();
        Trigger.ResetInitState();
    }
    ara::core::Future<bool> ProcessNextMethodCall()
    {
        return skeletonAdapter->ProcessNextMethodCall();
    }
    bool SetMethodThreadNumber(const std::uint16_t& number, const std::uint16_t& queueSize)
    {
        return skeletonAdapter->SetMethodThreadNumber(number, queueSize);
    }
    virtual ara::core::Future<AcquireFunctionGroupInfoOutput> AcquireFunctionGroupInfo() = 0;
    virtual ara::core::Future<ProcessSyncRequestOutput> ProcessSyncRequest(const ::ara::sm::StateTransitionVec& stateTrans) = 0;
    virtual ara::core::Future<ResetSystemOutput> ResetSystem(const ::ara::sm::ResetCode& resetCode, const ::String& user, const ::ara::sm::ResetCause& resetCause) = 0;

    methods::AcquireFunctionGroupInfoHandle AcquireFunctionGroupInfoHandle;
    methods::ProcessSyncRequestHandle ProcessSyncRequestHandle;
    methods::ResetSystemHandle ResetSystemHandle;
    fields::Notifier Notifier;
    fields::Trigger Trigger;
};
} // namespace skeleton
} // namespace sm
} // namespace ara

#endif // ARA_SM_TRIGGERINOUT_SKELETON_H
