/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_MNT_IMPL_TYPE_HCFIJOBINFOSTRUCT_H
#define MDC_MNT_IMPL_TYPE_HCFIJOBINFOSTRUCT_H
#include <cfloat>
#include <cmath>
#include "impl_type_string.h"

namespace mdc {
namespace mnt {
struct HcfiJobInfoStruct {
    ::String module;
    ::String task;
    ::String job;

    static bool IsPlane()
    {
        return false;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(module);
        fun(task);
        fun(job);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(module);
        fun(task);
        fun(job);
    }

    bool operator == (const ::mdc::mnt::HcfiJobInfoStruct& t) const
    {
        return (module == t.module) && (task == t.task) && (job == t.job);
    }
};
} // namespace mnt
} // namespace mdc


#endif // MDC_MNT_IMPL_TYPE_HCFIJOBINFOSTRUCT_H
