/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_MNT_IMPL_TYPE_HCFIDAGINFO_H
#define MDC_MNT_IMPL_TYPE_HCFIDAGINFO_H
#include <cfloat>
#include <cmath>
#include "impl_type_uint64_t.h"
#include "mdc/mnt/impl_type_hcfidagvector.h"

namespace mdc {
namespace mnt {
struct HcfiDagInfo {
    ::uint64_t pid;
    ::mdc::mnt::HcfiDagVector dags;

    static bool IsPlane()
    {
        return false;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(pid);
        fun(dags);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(pid);
        fun(dags);
    }

    bool operator == (const ::mdc::mnt::HcfiDagInfo& t) const
    {
        return (pid == t.pid) && (dags == t.dags);
    }
};
} // namespace mnt
} // namespace mdc


#endif // MDC_MNT_IMPL_TYPE_HCFIDAGINFO_H
