/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_MNT_IMPL_TYPE_HCFISTATEVENTSTRUCT_H
#define MDC_MNT_IMPL_TYPE_HCFISTATEVENTSTRUCT_H
#include <cfloat>
#include <cmath>
#include "impl_type_string.h"
#include "impl_type_uint32_t.h"
#include "mdc/mnt/impl_type_hcfijobinfovector.h"
#include "mdc/mnt/impl_type_uint64vector.h"

namespace mdc {
namespace mnt {
struct HcfiStatEventStruct {
    ::String action;
    ::uint32_t quantity;
    ::mdc::mnt::HcfiJobInfoVector jobList;
    ::mdc::mnt::Uint64Vector pid;

    static bool IsPlane()
    {
        return false;
    }


    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun)
    {
        fun(action);
        fun(quantity);
        fun(jobList);
        fun(pid);
    }

    template<typename F>
    void enumerate(F& fun) const
    {
        fun(action);
        fun(quantity);
        fun(jobList);
        fun(pid);
    }

    bool operator == (const ::mdc::mnt::HcfiStatEventStruct& t) const
    {
        return (action == t.action) && (quantity == t.quantity) && (jobList == t.jobList) && (pid == t.pid);
    }
};
} // namespace mnt
} // namespace mdc


#endif // MDC_MNT_IMPL_TYPE_HCFISTATEVENTSTRUCT_H
