/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef MDC_MNT_IMPL_TYPE_HCFIDAGVECTOR_H
#define MDC_MNT_IMPL_TYPE_HCFIDAGVECTOR_H
#include "ara/core/vector.h"
#include "mdc/mnt/impl_type_hcfidagstruct.h"

namespace mdc {
namespace mnt {
using HcfiDagVector = ara::core::Vector<mdc::mnt::HcfiDagStruct>;
} // namespace mnt
} // namespace mdc


#endif // MDC_MNT_IMPL_TYPE_HCFIDAGVECTOR_H
