/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#include "ara/actcompensation/actcompensationserviceinterface_proxy.h"
#include "ara/chassis/chassisreportserviceinterface_proxy.h"
#include "ara/dataflow/dataflowserviceinterface_skeleton.h"
#include "ara/rdetect/radardetectserviceinterface_skeleton.h"
#include "ara/rtrack/radartrackserviceinterface_skeleton.h"
#include "ara/timedelay/timedelayserviceinterface_skeleton.h"
#include "mdc/config/server/configserverserviceinterface_proxy.h"
#include "mdc/fm/fmreporteventservice_proxy.h"
#include "mdc/mdccanrx/canrxserviceinterface_proxy.h"
#include "mdc/mnt/mntdelayserviceinterface_proxy.h"
#include "mdc/nrm/nrmc/nrmcenterserviceinterface_proxy.h"
